#!/usr/bin/env bash

# Serve the rendered Verso blueprint over HTTP for local viewing.
#
# Usage: ./scripts/serve.sh [PORT]        (default port 8080)
#        BUILD=1 ./scripts/serve.sh       rebuild the site first
#
# The site is generated by ./scripts/ci-pages.sh into _out/site/html-multi.
# Subpages carry a <base href> pointing back at that directory, so the server
# root must be html-multi itself, not _out or the package root.

set -euo pipefail

cd "$(dirname "$0")/.."

PORT="${1:-8080}"
SITE="_out/site/html-multi"

if [[ "${BUILD:-0}" != "0" || ! -f "$SITE/index.html" ]]; then
  ./scripts/ci-pages.sh
fi

echo "Serving $SITE at http://localhost:$PORT/ (Ctrl-C to stop)"
exec python3 -m http.server "$PORT" --bind 127.0.0.1 --directory "$SITE"
