/-
Copyright (c) 2026 Kevin Buzzard. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kevin Buzzard
-/
module

public import FLT.Deformations.RepresentationTheory.AbsoluteGaloisGroup
public import FLT.GaloisRepresentation.Cyclotomic
public import Mathlib.NumberTheory.Cyclotomic.CyclotomicCharacter
import Mathlib.NumberTheory.Cyclotomic.Basic

/-!
# The mod-`ℓ` cyclotomic character of an absolute Galois group

For a characteristic-zero field `F`, we package Mathlib's `modularCyclotomicCharacter` of the
algebraic closure `Fᵃˡᵍ` as a monoid homomorphism

  `modCycChar ℓ F : Γ F →* (ZMod ℓ)ˣ`

on the absolute Galois group `Γ F := Fᵃˡᵍ ≃ₐ[F] Fᵃˡᵍ`, characterised by
`σ ζ = ζ ^ (modCycChar ℓ F σ).val` for every `ℓ`-th root of unity `ζ` of `Fᵃˡᵍ`.

Main results:
* `modCycChar_spec`, `modCycChar_unique` : the defining property;
* `isOpen_ker_modCycChar` : the kernel is an open subgroup of `Γ F` (it contains the fixing
  subgroup of the finite extension `F(ζ_ℓ)`);
* `modCycChar_absoluteGaloisGroup_map` : compatibility with the restriction map
  `Γ F' → Γ F` induced by a field embedding `F →+* F'` (used to compare the cyclotomic
  characters of `ℚ` and of `ℚ_ℓ`).
-/

@[expose] public section

open IntermediateField

local notation3 "Γ" K:max => Field.absoluteGaloisGroup K
local notation3 K:max "ᵃˡᵍ" => AlgebraicClosure K

namespace CyclotomicAbsIrred

variable (ℓ : ℕ) [NeZero ℓ] (F : Type) [Field F] [CharZero F]

instance : CharZero (Fᵃˡᵍ) := charZero_of_injective_algebraMap (algebraMap F (Fᵃˡᵍ)).injective

/-- The mod-`ℓ` cyclotomic character of the absolute Galois group of a characteristic zero
field `F`, characterised by `σ ζ = ζ ^ (modCycChar ℓ F σ).val` for `ℓ`-th roots of
unity `ζ` in the algebraic closure of `F`. -/
noncomputable def modCycChar : Γ F →* (ZMod ℓ)ˣ :=
  (modularCyclotomicCharacter (Fᵃˡᵍ) (IsAlgClosed.card_rootsOfUnity (Fᵃˡᵍ) ℓ)).comp
    (MonoidHom.mk' (fun g => g.toRingEquiv) (fun _ _ => rfl))

variable {ℓ F}

lemma modCycChar_spec (σ : Γ F) {t : (Fᵃˡᵍ)ˣ} (ht : t ∈ rootsOfUnity ℓ (Fᵃˡᵍ)) :
    σ (t : (Fᵃˡᵍ)) = (t : (Fᵃˡᵍ)) ^ ((modCycChar ℓ F σ) : ZMod ℓ).val :=
  modularCyclotomicCharacter.spec (Fᵃˡᵍ) (IsAlgClosed.card_rootsOfUnity (Fᵃˡᵍ) ℓ)
    σ.toRingEquiv ht

lemma modCycChar_unique (σ : Γ F) {c : ZMod ℓ}
    (hc : ∀ t ∈ rootsOfUnity ℓ (Fᵃˡᵍ), σ.toRingEquiv (t : (Fᵃˡᵍ)) = (t : (Fᵃˡᵍ)) ^ c.val) :
    c = modCycChar ℓ F σ :=
  modularCyclotomicCharacter.unique (Fᵃˡᵍ) (IsAlgClosed.card_rootsOfUnity (Fᵃˡᵍ) ℓ)
    σ.toRingEquiv hc

variable (ℓ F) in
/-- The kernel of the mod-`ℓ` cyclotomic character is open: it contains the (open) fixing
subgroup of the finite subextension generated by a primitive `ℓ`-th root of unity. -/
theorem isOpen_ker_modCycChar (hℓ : 1 < ℓ) :
    IsOpen ((modCycChar ℓ F).ker : Set (Γ F)) := by
  obtain ⟨ζ, hζ⟩ : ∃ ζ : (Fᵃˡᵍ), IsPrimitiveRoot ζ ℓ :=
    IsCyclotomicExtension.exists_isPrimitiveRoot (Fᵃˡᵍ) _ (show _ ∈ ⊤ by simp) (NeZero.ne ℓ)
  have hint : IsIntegral F ζ := (Algebra.IsAlgebraic.isAlgebraic ζ).isIntegral
  have hfd : FiniteDimensional F F⟮ζ⟯ := IntermediateField.adjoin.finiteDimensional hint
  refine Subgroup.isOpen_mono (H₁ := F⟮ζ⟯.fixingSubgroup) ?_ F⟮ζ⟯.fixingSubgroup_isOpen
  intro σ hσ
  rw [MonoidHom.mem_ker]
  have hσζ : σ ζ = ζ :=
    hσ ⟨ζ, IntermediateField.mem_adjoin_simple_self F ζ⟩
  have : (1 : ZMod ℓ) = modCycChar ℓ F σ := by
    apply modCycChar_unique
    intro t ht
    rw [mem_rootsOfUnity] at ht
    obtain ⟨i, -, hi⟩ := hζ.eq_pow_of_pow_eq_one
      (show ((t : (Fᵃˡᵍ)ˣ) : (Fᵃˡᵍ)) ^ ℓ = 1 by
        rw [← Units.val_pow_eq_pow_val, ht, Units.val_one])
    rw [ZMod.val_one_eq_one_mod, Nat.mod_eq_of_lt hℓ]
    change σ _ = _
    rw [← hi, map_pow, hσζ, pow_one]
  exact (Units.ext (by exact this.symm))

/-- Compatibility of the mod-`ℓ` cyclotomic character with the map of absolute Galois groups
induced by an embedding of characteristic-zero fields: the cyclotomic character of `F` evaluated
on the restriction of `σ : Γ F'` equals the cyclotomic character of `F'` on `σ`. -/
theorem modCycChar_absoluteGaloisGroup_map [NumberField F]
    {F' : Type} [Field F'] [CharZero F'] (f : F →+* F') (σ : Γ F') :
    modCycChar ℓ F (Field.absoluteGaloisGroup.map f σ) = modCycChar ℓ F' σ := by
  apply Units.ext
  symm
  apply modCycChar_unique
  intro t ht
  set j : (Fᵃˡᵍ) →+* (F'ᵃˡᵍ) := AlgebraicClosure.map f with hj
  have hjinj : Function.Injective j := j.injective
  have hjt : Units.map j t ∈ rootsOfUnity ℓ (F'ᵃˡᵍ) := by
    rw [mem_rootsOfUnity] at ht ⊢
    rw [← map_pow, ht, map_one]
  have hspec := modCycChar_spec σ hjt
  apply hjinj
  rw [map_pow]
  have hlift : j ((Field.absoluteGaloisGroup.map f σ) (t : (Fᵃˡᵍ))) = σ (j (t : (Fᵃˡᵍ))) :=
    Field.absoluteGaloisGroup.lift_map f σ (t : (Fᵃˡᵍ))
  have htoRing : ((Field.absoluteGaloisGroup.map f) σ).toRingEquiv (t : (Fᵃˡᵍ)) =
      ((Field.absoluteGaloisGroup.map f) σ) (t : (Fᵃˡᵍ)) := rfl
  rw [htoRing, hlift]
  simpa using hspec

end CyclotomicAbsIrred

end
