/-
Copyright (c) 2026 Duxing Yang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Duxing Yang
-/
module

public import Mathlib.Data.Fintype.Parity
public import Mathlib.LinearAlgebra.Matrix.SpecialLinearGroup
public import Mathlib.LinearAlgebra.SpecialLinearGroup
public import FLT.KnownIn1980s.PGL2.FiniteSubgroups.PGLBasic

/-!
# Basics on `SL₂`, its centre, and the image of `PSL₂` in `PGL₂`

This file proves the general facts about `SL₂(F)` and `PSL₂(F)` over a field `F`
needed for Dickson's classification of finite subgroups of `PGL₂(𝔽̄_p)`:

* `SL2.closure_elementary_eq_top`: `SL₂(F)` is generated by the elementary matrices
  `E12 a` and `E21 b`;
* `SL2ToPGL_ker_eq_center` and `SL2_center_card`: the kernel of `SL₂(F) → PGL₂(F)` is
  the centre `{±1}`, of order 2 when `char F ≠ 2`;
* `SL2_card`: `|SL₂(F)| = (q² - 1) * q` for `F` a finite field with `q` elements;
* `PSLImageInPGL_index`: for `F` finite of odd characteristic, the image of `PSL₂(F)`
  in `PGL₂(F)` has index 2, and `index_two_subgroup_iso_PSL`: it is the unique
  subgroup of index two consisting of the classes of matrices with square determinant;
* `PSL2_ZMod3_equiv_GF31`: the identification `PSL₂(𝔽₃) ≃* A₄` obtained by letting
  `SL₂(𝔽₃)` act on the four points of `ℙ¹(𝔽₃)`.
-/

/- The code in this file was ported from Duxing Yang's `DicksonClassification` project
and does not yet follow the mathlib style conventions enforced by the linters below. -/
set_option linter.style.longLine false
set_option linter.style.emptyLine false
set_option linter.style.whitespace false
set_option linter.style.show false
set_option linter.style.openClassical false
set_option linter.style.cdot false
set_option linter.style.multiGoal false
set_option linter.style.refine false
set_option linter.style.induction false
set_option linter.unusedFintypeInType false

@[expose] public section

open scoped Classical
open Dickson Matrix

noncomputable section

variable {G : Type*} [Group G]


theorem mem_of_odd_orderOf_of_index_two (H : Subgroup G) (hH : H.index = 2)
    (g : G) (hodd : Odd (orderOf g)) : g ∈ H := by
  obtain ⟨n, hn⟩ := hodd
  have h_pow : (g ^ 2) ^ n * g = 1 := by
    rw [← pow_mul, ← pow_succ, ← hn, pow_orderOf_eq_one g]
  rw [eq_inv_of_mul_eq_one_right h_pow]
  exact H.inv_mem (H.pow_mem (Subgroup.sq_mem_of_index_two hH g) n)

section SL2Gen

variable (F : Type*) [Field F]


/-- The elementary matrix `e₁₂ a = !![1, a; 0, 1]` as an element of `SL₂(F)`. -/
def SL2.E12 (a : F) : Matrix.SpecialLinearGroup (Fin 2) F :=
  ⟨!![1, a; 0, 1], by
    rw [Matrix.det_fin_two]
    change (1 : F) * 1 - a * 0 = 1
    rw [mul_zero, sub_zero, mul_one]⟩

/-- The elementary matrix `e₂₁ b = !![1, 0; b, 1]` as an element of `SL₂(F)`. -/
def SL2.E21 (b : F) : Matrix.SpecialLinearGroup (Fin 2) F :=
  ⟨!![1, 0; b, 1], by
    rw [Matrix.det_fin_two]
    change (1 : F) * 1 - 0 * b = 1
    rw [zero_mul, sub_zero, mul_one]⟩


theorem SL2.closure_elementary_eq_top :
    Subgroup.closure (Set.range (SL2.E12 F) ∪ Set.range (SL2.E21 F)) = ⊤ := by
  refine eq_top_iff.mpr fun g _ ↦ ?_
  let H := Subgroup.closure (Set.range (SL2.E12 F) ∪ Set.range (SL2.E21 F))
  have h12 : ∀ x, SL2.E12 F x ∈ H := fun x ↦ Subgroup.subset_closure (Or.inl ⟨x, rfl⟩)
  have h21 : ∀ x, SL2.E21 F x ∈ H := fun x ↦ Subgroup.subset_closure (Or.inr ⟨x, rfl⟩)

  have step : ∀ (M : Matrix.SpecialLinearGroup (Fin 2) F), M.1 1 0 ≠ 0 → M ∈ H := by
    intro M hM
    have eq_M : M = SL2.E12 F ((M.1 0 0 - 1) / M.1 1 0) * SL2.E21 F (M.1 1 0) *
        SL2.E12 F ((M.1 1 1 - 1) / M.1 1 0) := by
      ext i j
      match i, j with
      | 0, 0 =>
        simp only [Matrix.SpecialLinearGroup.coe_mul, Matrix.mul_apply, Fin.sum_univ_two,
          Matrix.of_apply, Matrix.cons_val', Matrix.cons_val_zero, Matrix.cons_val_one, mul_zero,
          mul_one, one_mul, add_zero, zero_add, SL2.E12, SL2.E21]
        rw [div_mul_cancel₀ _ hM]
        ring
      | 0, 1 =>
        simp only [Matrix.SpecialLinearGroup.coe_mul, Matrix.mul_apply, Fin.sum_univ_two,
          Matrix.of_apply, Matrix.cons_val', Matrix.cons_val_zero, Matrix.cons_val_one, mul_one,
          one_mul, zero_add, SL2.E12, SL2.E21]
        rw [div_mul_cancel₀ _ hM, ← mul_div_assoc, ← add_div]
        rw [show (1 + (M.1 0 0 - 1)) * (M.1 1 1 - 1) + (M.1 0 0 - 1) = M.1 0 1 * M.1 1 0 by
          have hd := M.property
          rw [Matrix.det_fin_two] at hd
          calc (1 + (M.1 0 0 - 1)) * (M.1 1 1 - 1) + (M.1 0 0 - 1)
              = M.1 0 0 * M.1 1 1 - 1 := by ring
            _ = M.1 0 0 * M.1 1 1 - (M.1 0 0 * M.1 1 1 - M.1 0 1 * M.1 1 0) := by rw [hd]
            _ = M.1 0 1 * M.1 1 0 := by ring]
        rw [mul_div_cancel_right₀ _ hM]
      | 1, 0 =>
        simp only [Matrix.SpecialLinearGroup.coe_mul, Matrix.mul_apply, Fin.sum_univ_two,
          Matrix.of_apply, Matrix.cons_val', Matrix.cons_val_zero, Matrix.cons_val_one, mul_zero,
          zero_mul, mul_one, one_mul, add_zero, zero_add, SL2.E12, SL2.E21]
      | 1, 1 =>
        simp only [Matrix.SpecialLinearGroup.coe_mul, Matrix.mul_apply, Fin.sum_univ_two,
          Matrix.of_apply, Matrix.cons_val', Matrix.cons_val_zero, Matrix.cons_val_one, zero_mul,
          mul_one, one_mul, zero_add, SL2.E12, SL2.E21]
        rw [mul_comm (M.1 1 0) ((M.1 1 1 - 1) / M.1 1 0), div_mul_cancel₀ _ hM]
        ring
    rw [eq_M]
    exact Subgroup.mul_mem _ (Subgroup.mul_mem _ (h12 _) (h21 _)) (h12 _)

  by_cases hg : g.1 1 0 = 0
  · refine (inv_mul_cancel_left (SL2.E21 F 1) g).symm ▸ Subgroup.mul_mem _
      (Subgroup.inv_mem _ (h21 1)) (step _ ?_)
    simp only [Matrix.SpecialLinearGroup.coe_mul, SL2.E21, Matrix.mul_apply, Fin.sum_univ_two,
      Matrix.of_apply, Matrix.cons_val', Matrix.cons_val_zero, Matrix.cons_val_one, mul_zero,
      one_mul, hg, add_zero]
    intro h_zero
    have hd := g.property
    rw [Matrix.det_fin_two, h_zero, hg] at hd
    simp only [mul_zero, zero_mul, sub_zero] at hd
    exact zero_ne_one hd
  · exact step g hg

end SL2Gen

section PGLOrder

variable (p : ℕ) [Fact (Nat.Prime p)] [h_odd : Fact (p > 2)]


/-- The natural homomorphism `SL₂(F) → PGL₂(F)` sending a matrix to the class of its
image in `GL₂(F)`. -/
def SL2ToPGL (F : Type*) [Field F] : Matrix.SpecialLinearGroup (Fin 2) F →* PGLOf F :=
  (QuotientGroup.mk' _).comp Matrix.SpecialLinearGroup.toGL


/-- The image of `PSL₂(F)` inside `PGL₂(F)`, namely the range of `SL2ToPGL F`. -/
def PSLImageInPGL (F : Type*) [Field F] : Subgroup (PGLOf F) :=
  (SL2ToPGL F).range

omit h_odd in
theorem PGL.orderOf_E12_image (F : Type*) [Field F] [CharP F p] (a : F) (ha : a ≠ 0) :
    orderOf (SL2ToPGL F (SL2.E12 F a)) = p := by
  refine' orderOf_eq_prime _ _
  · have h_exp : ∀ n : ℕ, (SL2.E12 F a) ^ n = SL2.E12 F (((n : ℕ) : F) * a) := by
      intro n
      induction n with
      | zero =>
        rw [pow_zero]
        ext i j
        change (1 : Matrix (Fin 2) (Fin 2) F) i j = !![1, ((0 : ℕ) : F) * a; 0, 1] i j
        rw [Matrix.one_fin_two, Nat.cast_zero, zero_mul]
      | succ n ih =>
        rw [pow_succ, ih]
        ext i j
        change (!![1, ((n : ℕ) : F) * a; 0, 1] * !![1, a; 0, 1] : Matrix (Fin 2) (Fin 2) F) i j =
               !![1, ((n + 1 : ℕ) : F) * a; 0, 1] i j
        simp only [Matrix.mul_apply, Fin.sum_univ_two]
        match i, j with
        | 0, 0 => change (1 : F) * 1 + (((n : ℕ) : F) * a) * 0 = 1; ring
        | 0, 1 => change (1 : F) * a + (((n : ℕ) : F) * a) * 1 = (((n + 1 : ℕ) : F) * a); rw [Nat.cast_add, Nat.cast_one]; ring
        | 1, 0 => change (0 : F) * 1 + 1 * 0 = 0; ring
        | 1, 1 => change (0 : F) * a + 1 * 1 = 1; ring

    rw [← map_pow, h_exp, CharP.cast_eq_zero F p, zero_mul]
    have h_one : SL2.E12 F 0 = 1 := by
      ext i j
      change !![1, (0 : F); 0, 1] i j = (1 : Matrix (Fin 2) (Fin 2) F) i j
      rw [Matrix.one_fin_two]
    rw [h_one, map_one]

  · intro h_eq_one
    have h_center : Matrix.SpecialLinearGroup.toGL (SL2.E12 F a) ∈ Subgroup.center (GL (Fin 2) F) := by
      rw [SL2ToPGL, MonoidHom.comp_apply] at h_eq_one
      have h_ker : _ ∈ MonoidHom.ker _ := MonoidHom.mem_ker.mpr h_eq_one
      rwa [QuotientGroup.ker_mk'] at h_ker

    let M : Matrix.GeneralLinearGroup (Fin 2) F :=
      Matrix.GeneralLinearGroup.mkOfDetNeZero !![1, 0; 1, 1] (by
        rw [Matrix.det_fin_two]
        have h_det : (1 : F) * 1 - 0 * 1 = 1 := by ring
        exact h_det.symm ▸ one_ne_zero)

    have h_comm := Subgroup.mem_center_iff.mp h_center M
    have h_eq : ((Matrix.SpecialLinearGroup.toGL (SL2.E12 F a) * M : GL (Fin 2) F) : Matrix (Fin 2) (Fin 2) F) 0 0 =
                ((M * Matrix.SpecialLinearGroup.toGL (SL2.E12 F a) : GL (Fin 2) F) : Matrix (Fin 2) (Fin 2) F) 0 0 := by rw [h_comm]
    change (!![1, a; 0, 1] * !![1, 0; 1, 1] : Matrix (Fin 2) (Fin 2) F) 0 0 =
           (!![1, 0; 1, 1] * !![1, a; 0, 1] : Matrix (Fin 2) (Fin 2) F) 0 0 at h_eq

    simp only [Matrix.mul_apply, Fin.sum_univ_two] at h_eq
    change (1 : F) * 1 + a * 1 = (1 : F) * 1 + 0 * 0 at h_eq

    apply ha
    calc a = ((1 : F) * 1 + a * 1) - 1 * 1 := by ring
         _ = ((1 : F) * 1 + 0 * 0) - 1 * 1 := by rw [h_eq]
         _ = 0                             := by ring


@[nolint unusedArguments]
theorem PSLImageInPGL_le_of_index_two (F : Type*) [Field F] [CharP F p] [Fintype F]
    (H : Subgroup (PGLOf F)) (hH : H.index = 2) :
    PSLImageInPGL F ≤ H := by
  have hp_prime : Nat.Prime p := (inferInstance : Fact (Nat.Prime p)).out
  have hp_gt_2 : p > 2 := (inferInstance : Fact (p > 2)).out

  have h_order_p' : ∀ b : F, b ≠ 0 → orderOf (SL2ToPGL F (SL2.E21 F b)) = p := fun b hb ↦ by
    refine' orderOf_eq_prime _ _
    · have h_exp : ∀ n : ℕ, (SL2.E21 F b) ^ n = SL2.E21 F (n * b) := by
        intro n; induction n with
        | zero =>
          ext i j; change (1 : Matrix (Fin 2) (Fin 2) F) i j = !![1, 0; ((0 : ℕ) : F) * b, 1] i j
          rw [Matrix.one_fin_two, Nat.cast_zero, zero_mul]
        | succ n ih =>
          rw [pow_succ, ih]; ext i j
          change (!![1, 0; ((n : ℕ) : F) * b, 1] * !![1, 0; b, 1] : Matrix (Fin 2) (Fin 2) F) i j =
                 !![1, 0; ((n + 1 : ℕ) : F) * b, 1] i j
          simp only [Matrix.mul_apply, Fin.sum_univ_two]
          match i, j with
          | 0, 0 => change (1 : F) * 1 + 0 * b = 1; ring
          | 0, 1 => change (1 : F) * 0 + 0 * 1 = 0; ring
          | 1, 0 => change (((n : ℕ) : F) * b) * 1 + 1 * b = (((n + 1 : ℕ) : F) * b); rw [Nat.cast_add, Nat.cast_one]; ring
          | 1, 1 => change (((n : ℕ) : F) * b) * 0 + 1 * 1 = 1; ring
      rw [← map_pow, h_exp, CharP.cast_eq_zero F p, zero_mul]
      suffices SL2.E21 F 0 = 1 by rw [this, map_one]
      ext i j; change !![1, 0; (0 : F), 1] i j = (1 : Matrix (Fin 2) (Fin 2) F) i j; rw [Matrix.one_fin_two]
    · intro h_eq_one
      let M : GL (Fin 2) F := Matrix.GeneralLinearGroup.mkOfDetNeZero !![1, 1; 0, 1] (by
        rw [Matrix.det_fin_two]; exact (by ring : (1 : F) * 1 - 1 * 0 = 1).symm ▸ one_ne_zero)
      have h_center : Matrix.SpecialLinearGroup.toGL (SL2.E21 F b) ∈ Subgroup.center (GL (Fin 2) F) := by
        rwa [SL2ToPGL, MonoidHom.comp_apply, ← MonoidHom.mem_ker, QuotientGroup.ker_mk'] at h_eq_one
      have h_eq : ((Matrix.SpecialLinearGroup.toGL (SL2.E21 F b) * M : GL (Fin 2) F) : Matrix (Fin 2) (Fin 2) F) 0 0 =
                  ((M * Matrix.SpecialLinearGroup.toGL (SL2.E21 F b) : GL (Fin 2) F) : Matrix (Fin 2) (Fin 2) F) 0 0 := by
        rw [Subgroup.mem_center_iff.mp h_center M]
      change (!![1, 0; b, 1] * !![1, 1; 0, 1] : Matrix (Fin 2) (Fin 2) F) 0 0 =
             (!![1, 1; 0, 1] * !![1, 0; b, 1] : Matrix (Fin 2) (Fin 2) F) 0 0 at h_eq
      simp only [Matrix.mul_apply, Fin.sum_univ_two] at h_eq
      change (1 : F) * 1 + 0 * 0 = (1 : F) * 1 + 1 * b at h_eq
      apply hb
      calc b = ((1 : F) * 1 + 1 * b) - 1 * 1 := by ring
           _ = ((1 : F) * 1 + 0 * 0) - 1 * 1 := by rw [← h_eq]
           _ = 0                             := by ring

  rintro _ ⟨m, rfl⟩
  apply Subgroup.mem_closure.mp (SL2.closure_elementary_eq_top F ▸ Subgroup.mem_top m) (H.comap (SL2ToPGL F))
  rintro _ (⟨a, rfl⟩ | ⟨b, rfl⟩)
  · by_cases ha : a = 0
    · suffices SL2.E12 F a = 1 by rw [this]; exact Subgroup.one_mem _
      rw [ha]; ext i j; change !![1, (0 : F); 0, 1] i j = (1 : Matrix (Fin 2) (Fin 2) F) i j; rw [Matrix.one_fin_two]
    · exact mem_of_odd_orderOf_of_index_two H hH _
        (by rw [PGL.orderOf_E12_image p F a ha]; exact Nat.Prime.odd_of_ne_two hp_prime (ne_of_gt hp_gt_2))
  · by_cases hb : b = 0
    · suffices SL2.E21 F b = 1 by rw [this]; exact Subgroup.one_mem _
      rw [hb]; ext i j; change !![1, 0; (0 : F), 1] i j = (1 : Matrix (Fin 2) (Fin 2) F) i j; rw [Matrix.one_fin_two]
    · exact mem_of_odd_orderOf_of_index_two H hH _
        (by rw [h_order_p' b hb]; exact Nat.Prime.odd_of_ne_two hp_prime (ne_of_gt hp_gt_2))


theorem SL2ToPGL_ker_eq_center (F : Type*) [Field F] :
    MonoidHom.ker (SL2ToPGL F) = Subgroup.center (Matrix.SpecialLinearGroup (Fin 2) F) := by
  ext m
  constructor
  · intro h
    rw [MonoidHom.mem_ker] at h
    change (m.toGL : PGLOf F) = 1 at h
    rw [QuotientGroup.eq_one_iff, Subgroup.mem_center_iff] at h
    rw [Subgroup.mem_center_iff]
    intro g
    apply Subtype.ext
    exact congr_arg Units.val (h g.toGL)
  · intro hm
    rw [Subgroup.mem_center_iff] at hm
    rw [MonoidHom.mem_ker]
    change (m.toGL : PGLOf F) = 1
    rw [QuotientGroup.eq_one_iff, Subgroup.mem_center_iff]
    intro g
    have h1 : !![(1 : F), 1; 0, 1] * m.val = m.val * !![(1 : F), 1; 0, 1] :=
      congr_arg Subtype.val (hm (SL2.E12 F 1))
    have h2 : !![(1 : F), 0; 1, 1] * m.val = m.val * !![(1 : F), 0; 1, 1] :=
      congr_arg Subtype.val (hm (SL2.E21 F 1))

    have m10 : (m.val) 1 0 = 0 := by
      have h := congr_fun (congr_fun h1 0) 0
      simp only [Matrix.mul_apply, Fin.sum_univ_two] at h
      change (1 : F) * m.val 0 0 + 1 * m.val 1 0 = m.val 0 0 * 1 + m.val 0 1 * 0 at h
      simp only [mul_one, mul_zero, one_mul, add_zero] at h
      exact add_left_cancel (h.trans (add_zero _).symm)

    have m01 : (m.val) 0 1 = 0 := by
      have h := congr_fun (congr_fun h2 0) 0
      simp only [Matrix.mul_apply, Fin.sum_univ_two] at h
      change (1 : F) * m.val 0 0 + 0 * m.val 1 0 = m.val 0 0 * 1 + m.val 0 1 * 1 at h
      simp only [mul_one, zero_mul, one_mul, add_zero] at h
      exact (add_left_cancel ((add_zero _).trans h)).symm

    have m11 : (m.val) 1 1 = (m.val) 0 0 := by
      have h := congr_fun (congr_fun h1 0) 1
      simp only [Matrix.mul_apply, Fin.sum_univ_two] at h
      change (1 : F) * m.val 0 1 + 1 * m.val 1 1 = m.val 0 0 * 1 + m.val 0 1 * 1 at h
      simp only [m01, mul_one, mul_zero, one_mul, add_zero, zero_add] at h
      exact h

    apply Units.ext
    change g.val * m.val = m.val * g.val
    rw [← Matrix.ext_iff, Fin.forall_fin_two]
    refine ⟨?_, ?_⟩
    · rw [Fin.forall_fin_two]
      refine ⟨?_, ?_⟩
      · simp only [Matrix.mul_apply, Fin.sum_univ_two]
        change g.val 0 0 * m.val 0 0 + g.val 0 1 * m.val 1 0 = m.val 0 0 * g.val 0 0 + m.val 0 1 * g.val 1 0
        simp only [m10, m01, zero_mul, add_zero, mul_comm]
      · simp only [Matrix.mul_apply, Fin.sum_univ_two]
        change g.val 0 0 * m.val 0 1 + g.val 0 1 * m.val 1 1 = m.val 0 0 * g.val 0 1 + m.val 0 1 * g.val 1 1
        simp only [m01, m11, zero_mul, add_zero, zero_add, mul_comm]
    · rw [Fin.forall_fin_two]
      refine ⟨?_, ?_⟩
      · simp only [Matrix.mul_apply, Fin.sum_univ_two]
        change g.val 1 0 * m.val 0 0 + g.val 1 1 * m.val 1 0 = m.val 1 0 * g.val 0 0 + m.val 1 1 * g.val 1 0
        simp only [m10, m11, zero_mul, add_zero, zero_add, mul_comm]
      · simp only [Matrix.mul_apply, Fin.sum_univ_two]
        change g.val 1 0 * m.val 0 1 + g.val 1 1 * m.val 1 1 = m.val 1 0 * g.val 0 1 + m.val 1 1 * g.val 1 1
        simp only [m01, m10, zero_mul, zero_add, mul_comm]

omit [Fact (Nat.Prime p)] in
theorem SL2_center_card (F : Type*) [Field F] [CharP F p] :
    Nat.card (Subgroup.center (Matrix.SpecialLinearGroup (Fin 2) F)) = 2 := by
  have hp_gt_2 : p > 2 := (inferInstance : Fact (p > 2)).out
  have h_center : Subgroup.center (Matrix.SpecialLinearGroup (Fin 2) F) = Subgroup.zpowers (-1 : Matrix.SpecialLinearGroup (Fin 2) F) := by
    refine' le_antisymm _ _
    · intro g hg
      rw [Subgroup.mem_center_iff] at hg
      have h1 : !![(1 : F), 1; 0, 1] * g.val = g.val * !![(1 : F), 1; 0, 1] :=
        congr_arg Subtype.val (hg (SL2.E12 F 1))
      have h2 : !![(1 : F), 0; 1, 1] * g.val = g.val * !![(1 : F), 0; 1, 1] :=
        congr_arg Subtype.val (hg (SL2.E21 F 1))

      have eq_10 : (g.val) 1 0 = 0 := by
        have h := congr_fun (congr_fun h1 0) 0
        simp only [Matrix.mul_apply, Fin.sum_univ_two] at h
        change (1 : F) * g.val 0 0 + 1 * g.val 1 0 = g.val 0 0 * 1 + g.val 0 1 * 0 at h
        simp only [mul_one, mul_zero, one_mul, add_zero] at h
        exact add_left_cancel (h.trans (add_zero _).symm)

      have eq_01 : (g.val) 0 1 = 0 := by
        have h := congr_fun (congr_fun h2 0) 0
        simp only [Matrix.mul_apply, Fin.sum_univ_two] at h
        change (1 : F) * g.val 0 0 + 0 * g.val 1 0 = g.val 0 0 * 1 + g.val 0 1 * 1 at h
        simp only [mul_one, zero_mul, one_mul, add_zero] at h
        exact (add_left_cancel ((add_zero _).trans h)).symm

      have eq_11 : (g.val) 1 1 = (g.val) 0 0 := by
        have h := congr_fun (congr_fun h1 0) 1
        simp only [Matrix.mul_apply, Fin.sum_univ_two] at h
        change (1 : F) * g.val 0 1 + 1 * g.val 1 1 = g.val 0 0 * 1 + g.val 0 1 * 1 at h
        simp only [eq_01, mul_one, mul_zero, one_mul, add_zero, zero_add] at h
        exact h

      have hc : g.val = (g.val 0 0) • (1 : Matrix (Fin 2) (Fin 2) F) := by
        ext i j
        match i, j with
        | 0, 0 => change g.val 0 0 = g.val 0 0 * 1; exact (mul_one _).symm
        | 0, 1 => change g.val 0 1 = g.val 0 0 * 0; exact eq_01.trans (mul_zero _).symm
        | 1, 0 => change g.val 1 0 = g.val 0 0 * 0; exact eq_10.trans (mul_zero _).symm
        | 1, 1 => change g.val 1 1 = g.val 0 0 * 1; exact eq_11.trans (mul_one _).symm

      have h_det : (g.val 0 0) ^ 2 = 1 := by
        have hd := g.2
        change Matrix.det g.val = 1 at hd
        rw [hc, Matrix.det_smul] at hd
        change (g.val 0 0) ^ 2 * Matrix.det 1 = 1 at hd
        rw [Matrix.det_one, mul_one] at hd
        exact hd

      rcases eq_or_eq_neg_of_sq_eq_sq _ _ (h_det.trans (one_pow 2).symm) with h | h
      · have hg1 : g = 1 := Subtype.ext (by rw [hc, h, one_smul]; rfl)
        rw [hg1]
        exact Subgroup.one_mem _
      · have hg_1 : g = -1 := Subtype.ext (by rw [hc, h, neg_smul, one_smul]; rfl)
        rw [hg_1]
        exact Subgroup.mem_zpowers _

    · rw [Subgroup.zpowers_le, Subgroup.mem_center_iff]
      intro m
      apply Subtype.ext
      change m.val * (-1 : Matrix (Fin 2) (Fin 2) F) = (-1 : Matrix (Fin 2) (Fin 2) F) * m.val
      simp only [neg_mul, mul_neg, one_mul, mul_one]

  rw [h_center, Nat.card_zpowers]
  refine' orderOf_eq_prime _ _
  · apply Subtype.ext
    change ((-1 : Matrix.SpecialLinearGroup (Fin 2) F) ^ 2).val = (1 : Matrix (Fin 2) (Fin 2) F)
    rw [pow_two]
    change (-1 : Matrix (Fin 2) (Fin 2) F) * -1 = 1
    simp only [mul_neg, mul_one, neg_neg]
  · intro h
    have h0 : (-1 : F) = 1 := congr_arg (fun m : Matrix.SpecialLinearGroup (Fin 2) F ↦ (m : Matrix (Fin 2) (Fin 2) F) 0 0) h
    have h2 : (2 : F) = 0 :=
      calc (2 : F) = 1 - (-1 : F) := by ring
           _ = 1 - 1 := by rw [h0]
           _ = 0 := by ring
    exact Nat.not_dvd_of_pos_of_lt (by omega) hp_gt_2 (CharP.cast_eq_zero_iff F p 2 |>.mp h2)



theorem SL2_card (F : Type*) [Field F] [Fintype F] (hcard : Fintype.card F ≥ 2) :
    Nat.card (Matrix.SpecialLinearGroup (Fin 2) F) =
      Fintype.card F * (Fintype.card F ^ 2 - 1) := by
  have h_det_surj : Function.Surjective (Matrix.GeneralLinearGroup.det : Matrix.GeneralLinearGroup (Fin 2) F →* Fˣ) := fun x ↦
    ⟨⟨Matrix.diagonal ![x.val, 1], Matrix.diagonal ![(x⁻¹).val, 1],
      by
        rw [Matrix.diagonal_mul_diagonal, ← Matrix.diagonal_one]
        refine congr_arg Matrix.diagonal (by
          ext i
          match i with
          | 0 => change x.val * x.inv = 1; exact x.val_inv
          | 1 => exact mul_one (1 : F)),
      by
        rw [Matrix.diagonal_mul_diagonal, ← Matrix.diagonal_one]
        refine congr_arg Matrix.diagonal (by
          ext i
          match i with
          | 0 => change x.inv * x.val = 1; exact x.inv_val
          | 1 => exact mul_one (1 : F))⟩,
     by
       ext
       change Matrix.det (Matrix.diagonal ![x.val, 1]) = x.val
       rw [Matrix.det_diagonal, Fin.prod_univ_succ, Fin.prod_univ_succ, Fintype.prod_empty]
       change x.val * (1 * 1) = x.val
       rw [mul_one, mul_one]⟩

  have h_det_kernel : Nat.card (MonoidHom.ker (Matrix.GeneralLinearGroup.det : Matrix.GeneralLinearGroup (Fin 2) F →* Fˣ)) = Nat.card (Matrix.SpecialLinearGroup (Fin 2) F) := by
    refine Nat.card_congr (Equiv.ofBijective (fun x ↦ ⟨x.1.val, congr_arg Units.val x.2⟩) ⟨?_, ?_⟩)
    · rintro ⟨m1, h1⟩ ⟨m2, h2⟩ eq
      exact Subtype.ext (Units.ext (congr_arg Subtype.val eq))
    · intro x
      exact ⟨⟨⟨x.1, (x⁻¹ : Matrix.SpecialLinearGroup (Fin 2) F).1, congr_arg Subtype.val (mul_inv_cancel x), congr_arg Subtype.val (inv_mul_cancel x)⟩, Units.ext x.prop⟩, Subtype.ext rfl⟩

  have h_top_card : Nat.card (⊤ : Subgroup Fˣ) = Fintype.card F - 1 := by
    have e : (⊤ : Subgroup Fˣ) ≃ Fˣ := ⟨fun x ↦ x.1, fun x ↦ ⟨x, trivial⟩, fun _ ↦ Subtype.ext rfl, fun _ ↦ rfl⟩
    rw [Nat.card_congr e, Nat.card_eq_fintype_card, Fintype.card_units]

  have h_iso := Subgroup.card_mul_index (MonoidHom.ker (Matrix.GeneralLinearGroup.det : Matrix.GeneralLinearGroup (Fin 2) F →* Fˣ))
  rw [Subgroup.index_ker, MonoidHom.range_eq_top.mpr h_det_surj, h_det_kernel, h_top_card, Matrix.card_GL_field,
    Fin.prod_univ_succ, Fin.prod_univ_succ, Fintype.prod_empty] at h_iso
  change Nat.card (Matrix.SpecialLinearGroup (Fin 2) F) * (Fintype.card F - 1) = (Fintype.card F ^ 2 - Fintype.card F ^ 0) * ((Fintype.card F ^ 2 - Fintype.card F ^ 1) * 1) at h_iso
  rw [pow_zero, pow_one, mul_one] at h_iso
  rw [show (Fintype.card F ^ 2 - 1) * (Fintype.card F ^ 2 - Fintype.card F) = (Fintype.card F * (Fintype.card F ^ 2 - 1)) * (Fintype.card F - 1) from calc
    _ = (Fintype.card F ^ 2 - 1) * (Fintype.card F * Fintype.card F - Fintype.card F * 1) := by rw [sq, mul_one]
    _ = (Fintype.card F ^ 2 - 1) * (Fintype.card F * (Fintype.card F - 1)) := by rw [← Nat.mul_sub_left_distrib]
    _ = (Fintype.card F ^ 2 - 1) * Fintype.card F * (Fintype.card F - 1) := by rw [← mul_assoc]
    _ = Fintype.card F * (Fintype.card F ^ 2 - 1) * (Fintype.card F - 1) := by rw [mul_comm (Fintype.card F ^ 2 - 1) _]] at h_iso

  exact Nat.eq_of_mul_eq_mul_right (by omega) h_iso




omit [Fact (Nat.Prime p)] in
theorem PSLImageInPGL_index (F : Type*) [Field F] [CharP F p] [Fintype F]
    (hcard : Fintype.card F ≥ 5) :
    (PSLImageInPGL F).index = 2 := by
  have h_card_PSL : Nat.card (PSLImageInPGL F) * 2 = Fintype.card F * (Fintype.card F ^ 2 - 1) := by
    have h1 := Subgroup.card_mul_index (MonoidHom.ker (SL2ToPGL F))
    rw [Subgroup.index_ker, SL2ToPGL_ker_eq_center, SL2_center_card, SL2_card F (le_trans (by norm_num : 2 ≤ 5) hcard)] at h1
    change 2 * Nat.card (PSLImageInPGL F) = _ at h1
    exact Eq.trans (mul_comm _ 2) h1

  have h2 := Subgroup.index_mul_card (PSLImageInPGL F)
  rw [card_PGL2, ← h_card_PSL, mul_comm] at h2
  have h_pos : 0 < Nat.card (PSLImageInPGL F) :=
    Nat.pos_of_ne_zero fun h ↦ by
      have hC : 0 < Fintype.card F * (Fintype.card F ^ 2 - 1) := mul_pos (lt_of_lt_of_le (by norm_num : 0 < 5) hcard) (Nat.sub_pos_of_lt (by nlinarith only [hcard]))
      rw [h, zero_mul] at h_card_PSL
      exact ne_of_gt hC h_card_PSL.symm
  exact Nat.eq_of_mul_eq_mul_left h_pos h2


theorem index_two_subgroup_iso_PSL (F : Type*) [Field F] [CharP F p] [Fintype F]
    (hcard : Fintype.card F ≥ 5)
    (H : Subgroup (PGLOf F)) (hH : H.index = 2) :
    Nonempty (H ≃* Matrix.ProjectiveSpecialLinearGroup (Fin 2) F) := by
  have h_le := PSLImageInPGL_le_of_index_two p F H hH
  have h_idx := PSLImageInPGL_index p F hcard
  have h_eq : PSLImageInPGL F = H := SetLike.ext' <| Set.eq_of_subset_of_card_le h_le <| by
    rw [← Nat.card_eq_fintype_card, ← Nat.card_eq_fintype_card]
    have h := (Subgroup.card_mul_index H).trans (Subgroup.card_mul_index (PSLImageInPGL F)).symm
    rw [hH, h_idx] at h
    exact (Nat.eq_of_mul_eq_mul_right (by norm_num) h).le
  let iso : ↥(PSLImageInPGL F) ≃* Matrix.ProjectiveSpecialLinearGroup (Fin 2) F :=
    by convert (QuotientGroup.quotientKerEquivRange (SL2ToPGL F)).symm <;>
      first
      | rfl
      | exact (SL2ToPGL_ker_eq_center F).symm
  exact ⟨(MulEquiv.subgroupCongr h_eq.symm).trans iso⟩

end PGLOrder

noncomputable section A4PSL2

lemma PSL2_ZMod3_equiv_GF31 :
    Nonempty (ProjectiveSpecialLinearGroup (Fin 2) (ZMod 3) ≃*
      ProjectiveSpecialLinearGroup (Fin 2) (GaloisField 3 1)) := by
  let e := (GaloisField.equivZmodP 3).symm.toRingEquiv
  let slMap : SpecialLinearGroup (Fin 2) (ZMod 3) ≃* SpecialLinearGroup (Fin 2) (GaloisField 3 1) := {
    toFun := SpecialLinearGroup.map e.toRingHom
    invFun := SpecialLinearGroup.map e.symm.toRingHom
    left_inv := fun x ↦ Subtype.ext (Matrix.ext fun i j ↦ e.symm_apply_apply (x.1 i j))
    right_inv := fun x ↦ Subtype.ext (Matrix.ext fun i j ↦ e.apply_symm_apply (x.1 i j))
    map_mul' := (SpecialLinearGroup.map e.toRingHom).map_mul
  }
  refine ⟨QuotientGroup.congr _ _ slMap ?_⟩
  ext h
  simp only [Subgroup.mem_map, Subgroup.mem_center_iff]
  constructor
  · rintro ⟨g, hg, rfl⟩ x
    change x * slMap g = slMap g * x
    rw [← slMap.apply_symm_apply x, ← map_mul, ← map_mul]
    exact congr_arg slMap (hg (slMap.symm x))
  · intro hh
    refine ⟨slMap.symm h, fun x ↦ slMap.injective ?_, slMap.apply_symm_apply h⟩
    rw [map_mul, map_mul, slMap.apply_symm_apply]
    exact hh (slMap x)

/-- The special linear group `SL₂(𝔽₃)`. -/
abbrev SL2F3 := SpecialLinearGroup (Fin 2) (ZMod 3)
/-- The projective special linear group `PSL₂(𝔽₃)`. -/
abbrev PSL2F3 := ProjectiveSpecialLinearGroup (Fin 2) (ZMod 3)

/-- A choice of representative vector in `𝔽₃²` for each of the four points of `ℙ¹(𝔽₃)`. -/
def p1Rep : Fin 4 → Fin 2 → ZMod 3
  | 0 => ![1, 0] | 1 => ![0, 1] | 2 => ![1, 1] | 3 => ![1, 2]

/-- In `ZMod 3` every element is its own inverse, so we can use `v 0 * v 1` in place of
`v 0 * (v 1)⁻¹` (the latter does not reduce definitionally, since `ZMod.inv` is defined
via `Nat.gcdA`). -/
def p1Proj (v : Fin 2 → ZMod 3) : Fin 4 :=
  if v 1 = 0 then 0
  else let r := v 0 * v 1
    if r = 0 then 1 else if r = 1 then 2 else 3

/-- The action of a matrix `M` on the four points of `ℙ¹(𝔽₃)`, obtained by applying `M`
to a representative vector and projecting back. -/
def p1Act (M : Matrix (Fin 2) (Fin 2) (ZMod 3)) : Fin 4 → Fin 4 :=
  fun p ↦ p1Proj (M.mulVec (p1Rep p))

lemma p1Proj_smul (c : ZMod 3) (hc : c ≠ 0) (v : Fin 2 → ZMod 3) :
    p1Proj (c • v) = p1Proj v := by
  have hc2 : c * c = 1 := by
    fin_cases c
    · exact absurd rfl hc
    · decide
    · decide
  simp only [p1Proj, Pi.smul_apply, smul_eq_mul,
    show c * v 1 = 0 ↔ v 1 = 0 by simp only [mul_eq_zero, hc, false_or],
    show c * v 0 * (c * v 1) = v 0 * v 1 by
      rw [show c * v 0 * (c * v 1) = c * c * (v 0 * v 1) by ring, hc2, one_mul]
  ]

lemma p1Rep_p1Proj_scalar (a b : ZMod 3) (hab : ¬(a = 0 ∧ b = 0)) :
    ∃ c : ZMod 3, c ≠ 0 ∧ p1Rep (p1Proj ![a, b]) = c • ![a, b] := by
  match a, b with
  | 0, 0 => exact absurd ⟨rfl, rfl⟩ hab
  | 0, 1 | 1, 0 | 1, 1 | 1, 2 =>
    exact ⟨1, one_ne_zero, by ext i; fin_cases i <;> decide⟩
  | 0, 2 | 2, 0 | 2, 1 | 2, 2 =>
    exact ⟨2, fun h ↦ one_ne_zero (congrArg (fun x : ZMod 3 ↦ x * 2) h),
      by ext i; fin_cases i <;> decide⟩

lemma sl2_mulVec_ne_zero (M : SL2F3) (v : Fin 2 → ZMod 3) (hv : v ≠ 0) :
    M.1.mulVec v ≠ 0 := by
  intro h
  exact hv (mulVec_injective_of_isUnit (by rw [Matrix.isUnit_iff_isUnit_det, M.prop]; exact isUnit_one) (by rw [h, mulVec_zero]))

lemma p1Rep_ne_zero (p : Fin 4) : p1Rep p ≠ 0 := by
  intro h
  match p with
  | 0 => exact absurd (congr_fun h 0) nofun
  | 1 => exact absurd (congr_fun h 1) nofun
  | 2 => exact absurd (congr_fun h 0) nofun
  | 3 => exact absurd (congr_fun h 0) nofun

lemma p1Proj_mulVec_rep_proj (M : Matrix (Fin 2) (Fin 2) (ZMod 3))
    (w : Fin 2 → ZMod 3) (hw : w ≠ 0) :
    p1Proj (M.mulVec (p1Rep (p1Proj w))) = p1Proj (M.mulVec w) := by
  rcases p1Rep_p1Proj_scalar (w 0) (w 1) (fun ⟨h0, h1⟩ ↦ hw (funext fun i => match i with | 0 => h0 | 1 => h1)) with ⟨c, hc, hrep⟩
  rw [(funext fun i ↦ match i with | 0 => rfl | 1 => rfl : w = ![w 0, w 1]), hrep, mulVec_smul, p1Proj_smul _ hc]

instance sl2F3MulAction : MulAction SL2F3 (Fin 4) where
  smul M x := p1Act M.1 x
  one_smul x := by fin_cases x <;> decide
  mul_smul M N x := by
    show p1Act (M.1 * N.1) x = p1Act M.1 (p1Act N.1 x)
    simp only [p1Act, ← mulVec_mulVec]
    exact (p1Proj_mulVec_rep_proj M.1 _ (sl2_mulVec_ne_zero N (p1Rep x) (p1Rep_ne_zero x))).symm

/-- The permutation representation `SL₂(𝔽₃) → S₄` induced by the action on `ℙ¹(𝔽₃)`. -/
def sl2F3ToPermHom : SL2F3 →* Equiv.Perm (Fin 4) := MulAction.toPermHom _ _

/-- The upper elementary generator `!![1, 1; 0, 1]` of `SL₂(𝔽₃)`. -/
def U₁ : SL2F3 := ⟨!![1, 1; 0, 1], by rw [det_fin_two]; rfl⟩
/-- The lower elementary generator `!![1, 0; 1, 1]` of `SL₂(𝔽₃)`. -/
def L₁ : SL2F3 := ⟨!![1, 0; 1, 1], by rw [det_fin_two]; rfl⟩

lemma central_is_scalar (M : SL2F3) (hU : U₁ * M = M * U₁) (hL : L₁ * M = M * L₁) :
    M.1 1 0 = 0 ∧ M.1 0 1 = 0 ∧ M.1 0 0 = M.1 1 1 := by
  have hU00 : (U₁.1 * M.1) 0 0 = (M.1 * U₁.1) 0 0 := congr_fun (congr_fun (congr_arg Subtype.val hU) 0) 0
  have hU01 : (U₁.1 * M.1) 0 1 = (M.1 * U₁.1) 0 1 := congr_fun (congr_fun (congr_arg Subtype.val hU) 0) 1
  have hL00 : (L₁.1 * M.1) 0 0 = (M.1 * L₁.1) 0 0 := congr_fun (congr_fun (congr_arg Subtype.val hL) 0) 0
  simp only [U₁, L₁, mul_apply, Fin.sum_univ_two, of_apply, cons_val', cons_val_zero,
    cons_val_one, empty_val', one_mul, mul_one, zero_mul, mul_zero] at hU00 hU01 hL00
  have h2 : M.1 0 1 = 0 := (add_left_cancel hL00).symm
  rw [h2, zero_add, add_zero] at hU01
  exact ⟨add_left_cancel hU00, h2, hU01.symm⟩

lemma scalar_det_one_pm_one (M : SL2F3)
    (h10 : M.1 1 0 = 0) (h01 : M.1 0 1 = 0) (h_diag : M.1 0 0 = M.1 1 1) :
    M = 1 ∨ M = -1 := by
  have hdet := M.prop
  rw [det_fin_two, h01, h10, mul_zero, sub_zero, h_diag, ← sq] at hdet
  rcases sq_eq_one_iff.mp hdet with ha | ha
  · left
    ext i j
    exact match i, j with
    | 0, 0 => h_diag.trans ha
    | 0, 1 => h01
    | 1, 0 => h10
    | 1, 1 => ha
  · right
    ext i j
    exact match i, j with
    | 0, 0 => h_diag.trans ha
    | 0, 1 => h01
    | 1, 0 => h10
    | 1, 1 => ha

lemma kernel_is_scalar (M : SL2F3)
    (h0 : p1Act M.1 0 = 0) (h1 : p1Act M.1 1 = 1) (h2 : p1Act M.1 2 = 2) :
    M.1 1 0 = 0 ∧ M.1 0 1 = 0 ∧ M.1 0 0 = M.1 1 1 := by
  simp only [p1Act, p1Proj, p1Rep, mulVec, dotProduct, Fin.sum_univ_two,
    cons_val_zero, cons_val_one, mul_one, mul_zero, add_zero, zero_add] at h0 h1 h2
  have hM10 : M.1 1 0 = 0 := by
    split at h0
    · rename_i h; exact h
    · split at h0
      · contradiction
      · split at h0 <;> contradiction
  have hM11 : M.1 1 1 ≠ 0 := by
    split at h1
    · contradiction
    · rename_i h; exact h
  simp only [hM11, ↓reduceIte] at h1
  have hM01 : M.1 0 1 = 0 := by
    split at h1
    · rename_i h; exact (mul_eq_zero.mp h).resolve_right hM11
    · split at h1 <;> contradiction
  refine ⟨hM10, hM01, ?_⟩
  rw [hM10, zero_add, hM01, add_zero] at h2
  simp only [hM11, ↓reduceIte] at h2
  split at h2
  · contradiction
  · split at h2
    · rename_i h
      have hsq : ∀ b : ZMod 3, b ≠ 0 → b * b = 1 := by decide
      calc M.1 0 0 = M.1 0 0 * (M.1 1 1 * M.1 1 1) := by rw [hsq _ hM11, mul_one]
        _ = (M.1 0 0 * M.1 1 1) * M.1 1 1 := by ring
        _ = M.1 1 1 := by rw [h, one_mul]
    · contradiction

lemma sl2F3_ker_eq_center : sl2F3ToPermHom.ker = Subgroup.center SL2F3 := by
    ext M
    rw [MonoidHom.mem_ker, Subgroup.mem_center_iff]
    constructor
    · intro hM
      have hact : ∀ x, p1Act M.1 x = x := fun x ↦ Equiv.ext_iff.mp hM x
      have ⟨h10, h01, hd⟩ := kernel_is_scalar M (hact 0) (hact 1) (hact 2)
      rcases scalar_det_one_pm_one M h10 h01 hd with rfl | rfl
      · exact fun N ↦ by rw [one_mul, mul_one]
      · exact fun N ↦ by rw [neg_mul, mul_neg, one_mul, mul_one]
    · intro hM
      have ⟨h10, h01, h_diag⟩ := central_is_scalar M (hM U₁) (hM L₁)
      rcases scalar_det_one_pm_one M h10 h01 h_diag with rfl | rfl
      · exact map_one sl2F3ToPermHom
      · exact Equiv.ext fun x => by fin_cases x <;> decide

theorem A4_iso_PSL2_F3 :
    Nonempty (alternatingGroup (Fin 4) ≃* ProjectiveSpecialLinearGroup (Fin 2) (ZMod 3)) := by
  let f : SL2F3 →* alternatingGroup (Fin 4) :=
    sl2F3ToPermHom.codRestrict _
      (fun M ↦ by rw [Equiv.Perm.mem_alternatingGroup]; fin_cases M <;> decide)
  have h_ker : f.ker = Subgroup.center SL2F3 := by
    rw [MonoidHom.ker_codRestrict, sl2F3_ker_eq_center]
  let F : PSL2F3 →* alternatingGroup (Fin 4) :=
    QuotientGroup.lift _ f (le_of_eq h_ker.symm)
  have h_inj : Function.Injective F := by
    rw [← MonoidHom.ker_eq_bot_iff]
    change (QuotientGroup.lift _ f _).ker = ⊥
    rw [QuotientGroup.ker_lift, h_ker, QuotientGroup.map_mk'_self]
  have card_PSL2F3 : Nat.card PSL2F3 = 12 := by
    haveI : Fact ((3 : ℕ) > 2) := ⟨by norm_num⟩
    show Nat.card (SL2F3 ⧸ Subgroup.center SL2F3) = 12
    have h3 := Subgroup.card_eq_card_quotient_mul_card_subgroup (Subgroup.center SL2F3)
    rw [SL2_center_card 3 (ZMod 3), (Nat.card_eq_fintype_card.trans rfl : Nat.card SL2F3 = 24)] at h3
    omega
  have h_surj : Function.Surjective F :=
    (Finite.injective_iff_surjective_of_equiv <| Fintype.equivOfCardEq <| by
      rw [← Nat.card_eq_fintype_card, card_PSL2F3, card_alternatingGroup, Fintype.card_fin]; rfl).mp h_inj
  exact ⟨(MulEquiv.ofBijective F ⟨h_inj, h_surj⟩).symm⟩

theorem A4_iso_PSL2_GF31 :
    Nonempty (alternatingGroup (Fin 4) ≃* ProjectiveSpecialLinearGroup (Fin 2) (GaloisField 3 1)) := by
  obtain ⟨e1⟩ := A4_iso_PSL2_F3
  obtain ⟨e2⟩ := PSL2_ZMod3_equiv_GF31
  exact ⟨e1.trans e2⟩

end A4PSL2

end
