/-
Copyright (c) 2025 Jack McCarthy. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jack McCarthy
-/
module

public import Mathlib.GroupTheory.OrderOfElement
public import Mathlib.Tactic.Group

/-!
# Basic group-theoretic helper lemmas

This file contains small general-purpose lemmas about finite groups, subgroup
cardinalities, subgroups of subgroups, quotient-group cardinalities, and finite
sums over subtypes.

More specialised material about cosets, conjugacy, nilpotent groups, and double
cosets is developed in separate files.
-/

@[expose] public section

namespace Slop
open Slop

universe u v
variable {G : Type u} {H : Type v} [Group G] [Group H]


namespace Subgroup

/--
A subgroup different from `⊥` contains an element different from `1`.
-/
theorem exists_mem_ne_one_of_ne_bot {H : Subgroup G} (h : H ≠ ⊥) :
    ∃ x ∈ H, x ≠ 1 := by
  by_contra h_all
  push Not at h_all
  apply h
  ext x
  rw [Subgroup.mem_bot]
  constructor
  · intro hx; exact h_all x hx
  · rintro rfl; exact H.one_mem

/--
If `H ≤ K`, then the subgroup of `K` induced by `H` is multiplicatively
equivalent to `H`.

This is the equivalence between viewing `H` as a subgroup of the ambient group
and viewing it as a subgroup of the intermediate subgroup `K`.
-/
def subgroupOfEquiv {H K : Subgroup G} (h : H ≤ K) :
    H.subgroupOf K ≃* H where
  toFun x := ⟨x.1.1, x.2⟩
  invFun x := ⟨⟨x.1, h x.2⟩, x.2⟩
  left_inv _ := rfl
  right_inv _ := rfl
  map_mul' _ _ := rfl

/-- The forward map of `Subgroup.subgroupOfEquiv` preserves the underlying element of `G`. -/
@[simp]
theorem subgroupOfEquiv_apply {H K : Subgroup G} (hHK : H ≤ K) (x : H.subgroupOf K) :
    (Subgroup.subgroupOfEquiv hHK x : G) = (x : K) := rfl

/-- The inverse map of `Subgroup.subgroupOfEquiv` preserves the underlying element of `G`. -/
@[simp]
theorem subgroupOfEquiv_symm_apply {H K : Subgroup G} (hHK : H ≤ K) (h : H) :
    ((Subgroup.subgroupOfEquiv hHK).symm h : K) = (h : G) := rfl

/--
Mapping a subgroup of `K` into the ambient group through `K.subtype` and then
pulling it back to `K` recovers the original subgroup.
-/
@[simp]
lemma subgroupOf_map_subtype_eq_self {K : Subgroup G} (H : Subgroup K) :
    (H.map K.subtype).subgroupOf K = H := by
  ext x
  constructor
  · rintro ⟨y, hy, hxy⟩
    exact Subtype.ext hxy ▸ hy
  · intro hx
    exact ⟨x, hx, rfl⟩

/--
The cyclic subgroup generated by `a` is contained in the centralizer of `a`.
-/
lemma zpowers_le_centralizer (a : G) :
    Subgroup.zpowers a ≤ Subgroup.centralizer {a} := by
  rw [Subgroup.zpowers_le]
  intro x hx
  rw [Set.mem_singleton_iff.mp hx]

lemma natCard_lt_natCard_of_ne_top
    [Finite G] (H : Subgroup G) (hH : H ≠ ⊤) :
    Nat.card H < Nat.card G := by
  have h_ne : (H : Set G) ≠ Set.univ := by
    intro contra
    apply hH
    exact Subgroup.coe_eq_univ.mp contra
  exact Set.ncard_lt_card h_ne

end Subgroup


/--
If `K` is a nontrivial normal subgroup of a finite group `G`, then the quotient
`G ⧸ K` has strictly smaller cardinality than `G`.
-/
lemma QuotientGroup.natCard_quotient_lt_natCard_of_ne_bot
    {G : Type u} [Group G] [Finite G]
    (K : Subgroup G) [K.Normal] (hK : K ≠ ⊥) :
    Nat.card (G ⧸ K) < Nat.card G := by
  letI : Fintype G := Fintype.ofFinite G
  letI : Fintype K := Fintype.ofFinite K
  letI : Fintype (G ⧸ K) := Fintype.ofFinite (G ⧸ K)
  haveI: Nontrivial K := (Subgroup.nontrivial_iff_ne_bot K).mpr hK
  have hKcard : 1 < Fintype.card K := Fintype.one_lt_card
  have hquot_pos : 0 < Fintype.card (G ⧸ K) := Fintype.card_pos_iff.mpr ⟨1⟩
  have hcard :
      Fintype.card G =
        Fintype.card (G ⧸ K) * Fintype.card K := by
    simpa [Nat.card_eq_fintype_card] using
      (Subgroup.card_eq_card_quotient_mul_card_subgroup K)
  have hlt_fintype :
      Fintype.card (G ⧸ K) < Fintype.card G := by
    calc
      Fintype.card (G ⧸ K)
          = Fintype.card (G ⧸ K) * 1 := by rw [mul_one]
      _ < Fintype.card (G ⧸ K) * Fintype.card K :=
            Nat.mul_lt_mul_of_pos_left hKcard hquot_pos
      _ = Fintype.card G := hcard.symm
  simpa [Nat.card_eq_fintype_card] using hlt_fintype

lemma Subgroup.commute_subtype_iff
    {H : Subgroup G} (x y : H) :
    Commute ((x : H) : G) ((y : H) : G) ↔ Commute x y := by
  constructor
  · intro h
    apply Subtype.ext
    exact h.eq
  · intro h
    exact h.map (Subgroup.subtype H)

/--
The two ways of viewing `A ∩ B`, either as a subgroup of `A` or as a subgroup
of `B`, are multiplicatively equivalent.
-/
def Subgroup.comapSubtypeCommEquiv
    (A B : Subgroup G) :
    Subgroup.comap (Subgroup.subtype A) B ≃*
      Subgroup.comap (Subgroup.subtype B) A where
  toFun x := by
    refine ⟨⟨((x : A) : G), x.property⟩, ?_⟩
    exact (x : A).property
  invFun x := by
    refine ⟨⟨((x : B) : G), x.property⟩, ?_⟩
    exact (x : B).property
  left_inv := by
    intro x
    ext
    rfl
  right_inv := by
    intro x
    ext
    rfl
  map_mul' := by
    intro x y
    ext
    rfl

end Slop
