/-
# Irreducible ↔ absolutely irreducible, given a 1-dimensional fixed space

This file states (with `sorry`ed proofs) Proposition 1.2 / Theorem 1.3 of the
blueprint "Odd_Rep_Irreducible" (July 6, 2026), together with all the
supporting lemmas from the blueprint:

* `OddRep.exists_smul_eq_of_commute`        — Lemma 1.4  (`End_G(V) = k`)
* `OddRep.adjoinRange_eq_top`               — Lemma 1.5  (Jacobson density: `A = End_k(V)`)
* `OddRep.adjoinRange_baseChange_eq_top`    — Lemma 1.6  (base change of `A = End_k(V)`)
* `OddRep.smul_tmul_mem_range_iff`          — Fact 1.1   (`l·e ∩ V = k·e` inside `V_l`)
* `OddRep.isIrreducible_of_adjoinRange_eq_top` — step (iv) of the blueprint
* `OddRep.isIrreducible_of_baseChange`      — descent of irreducibility (easy direction)
* `OddRep.isIrreducible_iff_isAbsolutelyIrreducible` — Proposition 1.2 / Theorem 1.3

Conventions:
* Representations are `Representation k G V := G →* (V →ₗ[k] V)` as in Mathlib.
* All new definitions live in the `OddRep` namespace to avoid clashing with
  declarations such as `Representation.IsIrreducible` that exist in current
  Mathlib / FLT.  If the library notions agree with the ones below, the
  statements can later be re-phrased in terms of the library definitions.
* "Absolutely irreducible" is defined here as: the base change to
  `AlgebraicClosure k` is irreducible.  (The blueprint's proof in fact shows
  irreducibility after base change to *any* field extension `l/k`; this is
  recorded separately as
  `OddRep.isIrreducible_baseChange_of_finrank_fixedSpace_eq_one`.)
-/

import Mathlib

open scoped TensorProduct

open Module

namespace OddRep

variable {k : Type*} [Field k]
variable {G : Type*} [Monoid G]
variable {V : Type*} [AddCommGroup V] [Module k V]

/-! ## Definitions -/

/-- A `k`-subspace `W ⊆ V` is invariant under the representation `ρ`. -/
def IsInvariant (ρ : Representation k G V) (W : Submodule k V) : Prop :=
  ∀ g : G, ∀ v ∈ W, ρ g v ∈ W

/-- A representation is irreducible if `V ≠ 0` and the only invariant subspaces
are `⊥` and `⊤`. -/
def IsIrreducible (ρ : Representation k G V) : Prop :=
  Nontrivial V ∧ ∀ W : Submodule k V, IsInvariant ρ W → W = ⊥ ∨ W = ⊤

/-- The fixed subspace `V^g = {v : ρ(g) v = v}` of a single group element. -/
def fixedSpace (ρ : Representation k G V) (g : G) : Submodule k V :=
  LinearMap.ker (ρ g - LinearMap.id)

/-- Base change of a representation along a field extension `l/k`:
`G` acts on `l ⊗[k] V` by `1 ⊗ ρ(g)`. -/
noncomputable def baseChange (l : Type*) [Field l] [Algebra k l]
    (ρ : Representation k G V) : Representation l G (l ⊗[k] V) where
  toFun g := (ρ g).baseChange l
  map_one' := by sorry
  map_mul' := by sorry

/-- The `k`-subalgebra `A ⊆ End_k(V)` generated by the image of `ρ`. -/
def adjoinRange (ρ : Representation k G V) : Subalgebra k (Module.End k V) :=
  Algebra.adjoin k (Set.range ρ)

/-- A representation is absolutely irreducible if it remains irreducible after
base change to an algebraic closure of `k`. -/
def IsAbsolutelyIrreducible (ρ : Representation k G V) : Prop :=
  IsIrreducible (baseChange (AlgebraicClosure k) ρ)

variable (ρ : Representation k G V)

/-! ## Fact 1.1 : `l·e ∩ V = k·e` inside `V_l` -/

/-- **Fact 1.1.** If `e ≠ 0` in `V`, then for `c : l`, the element `c ⊗ e` of
`l ⊗[k] V` lies in the image of the canonical map `V → l ⊗[k] V`, `v ↦ 1 ⊗ v`,
if and only if `c` comes from `k`. -/
lemma smul_tmul_mem_range_iff (l : Type*) [Field l] [Algebra k l]
    {e : V} (he : e ≠ 0) (c : l) :
    c ⊗ₜ[k] e ∈ LinearMap.range (TensorProduct.mk k l V 1) ↔
      ∃ a : k, algebraMap k l a = c := by
  sorry

/-! ## Lemma 1.4 : `End_G(V) = k` -/

/-- **Lemma 1.4.** If `ρ` is irreducible and some `g : G` has a one-dimensional
fixed subspace, then every `G`-equivariant endomorphism of `V` is scalar. -/
lemma exists_smul_eq_of_commute
    (hirr : IsIrreducible ρ)
    {g : G} (hg : finrank k (fixedSpace ρ g) = 1)
    (T : Module.End k V) (hT : ∀ h : G, Commute (ρ h) T) :
    ∃ μ : k, T = μ • (1 : Module.End k V) := by
  sorry

/-! ## Lemma 1.5 : Jacobson density, `A = End_k(V)` -/

/-- **Lemma 1.5.** Let `A ⊆ End_k(V)` be the `k`-algebra generated by `ρ(G)`.
If `V` is finite-dimensional, `ρ` is irreducible, and every `G`-equivariant
endomorphism of `V` is scalar, then `A = End_k(V)`. -/
lemma adjoinRange_eq_top [FiniteDimensional k V]
    (hirr : IsIrreducible ρ)
    (hEnd : ∀ T : Module.End k V, (∀ h : G, Commute (ρ h) T) →
      ∃ μ : k, T = μ • (1 : Module.End k V)) :
    adjoinRange ρ = ⊤ := by
  obtain ⟨hnt, hsub⟩ := hirr
  haveI : Nontrivial V := hnt
  set A := adjoinRange ρ with hA
  -- `ρ g` lies in `A` for every `g`.
  have hρmem : ∀ g : G, ρ g ∈ A := fun g => Algebra.subset_adjoin ⟨g, rfl⟩
  -- The action of an element of `A` on `V` is application of the endomorphism.
  have hsmul : ∀ (a : A) (v : V), a • v = (a : Module.End k V) v := fun _ _ => rfl
  -- The scalar `μ : k`, viewed inside `A`, acts as `μ • ·`.
  have halg : ∀ (μ : k) (v : V),
      (⟨algebraMap k (Module.End k V) μ, A.algebraMap_mem μ⟩ : A) • v = μ • v := by
    intro μ v
    show (algebraMap k (Module.End k V) μ) v = μ • v
    simp [Module.algebraMap_end_apply]
  -- Scaling by `μ : k` is an `A`-linear endomorphism of `V`
  -- (elements of `A` are `k`-linear, so they commute with `k`-scalars).
  let scal : k → Module.End A V := fun μ =>
    { toFun := fun v => μ • v
      map_add' := fun a b => smul_add μ a b
      map_smul' := fun a v => ((a : Module.End k V).map_smul μ v).symm }
  -- Step 1: `V` is a simple `A`-module: a nonzero proper `A`-submodule would be
  -- a nonzero proper `G`-invariant `k`-subspace, contradicting irreducibility.
  haveI hAsimple : IsSimpleModule A V := by
    haveI : Nontrivial (Submodule A V) := by
      obtain ⟨v, hv⟩ := exists_ne (0 : V)
      refine ⟨⊥, ⊤, fun hbt => hv ?_⟩
      have hmem : v ∈ (⊥ : Submodule A V) := by rw [hbt]; exact Submodule.mem_top
      simpa using hmem
    rw [isSimpleModule_iff]
    refine ⟨fun W => ?_⟩
    -- view `W` as a `k`-subspace of `V`
    let Wk : Submodule k V :=
      { carrier := (W : Set V)
        add_mem' := fun ha hb => W.add_mem ha hb
        zero_mem' := W.zero_mem
        smul_mem' := fun μ {v} hv => by
          have h1 := W.smul_mem
            (⟨algebraMap k (Module.End k V) μ, A.algebraMap_mem μ⟩ : A) hv
          rwa [halg] at h1 }
    have hWk : IsInvariant ρ Wk := by
      intro g v hv
      exact W.smul_mem (⟨ρ g, hρmem g⟩ : A) hv
    rcases hsub Wk hWk with hbot | htop
    · left
      rw [Submodule.eq_bot_iff] at hbot ⊢
      exact fun v hv => hbot v hv
    · right
      rw [Submodule.eq_top_iff'] at htop ⊢
      exact fun v => htop v
  -- Step 2: every `A`-linear endomorphism of `V` is a `k`-scalar (uses `hEnd`).
  have hEnd' : ∀ f : Module.End A V, ∃ μ : k, ∀ v : V, f v = μ • v := by
    intro f
    -- `f` is in particular `k`-linear ...
    let fk : Module.End k V :=
      { toFun := f
        map_add' := fun a b => f.map_add a b
        map_smul' := fun μ v => by
          have h1 := f.map_smul
            (⟨algebraMap k (Module.End k V) μ, A.algebraMap_mem μ⟩ : A) v
          rw [halg, halg] at h1
          simpa using h1 }
    -- ... and commutes with every `ρ h`, since `ρ h ∈ A`.
    have hcomm : ∀ h : G, Commute (ρ h) fk := by
      intro h
      show ρ h * fk = fk * ρ h
      refine LinearMap.ext fun v => ?_
      show ρ h (f v) = f (ρ h v)
      exact (f.map_smul (⟨ρ h, hρmem h⟩ : A) v).symm
    have hfk : ∀ w : V, fk w = f w := fun _ => rfl
    obtain ⟨μ, hμ⟩ := hEnd fk hcomm
    refine ⟨μ, fun v => ?_⟩
    have h1 := LinearMap.congr_fun hμ v
    rw [hfk] at h1
    simpa using h1
  -- Step 3: `V` is module-finite over `End_A(V)`: a finite `k`-spanning set
  -- still spans, because `k`-scalars act through `End_A(V)` via `scal`.
  haveI : Module.Finite (Module.End A V) V := by
    obtain ⟨s, hs⟩ := Module.Finite.fg_top (R := k) (M := V)
    refine ⟨⟨s, ?_⟩⟩
    rw [eq_top_iff]
    rintro v -
    have hv : v ∈ Submodule.span k (s : Set V) := by rw [hs]; exact Submodule.mem_top
    induction hv using Submodule.span_induction with
    | mem x hx => exact Submodule.subset_span hx
    | zero => exact Submodule.zero_mem _
    | add x y _ _ h₁ h₂ => exact Submodule.add_mem _ h₁ h₂
    | smul μ x _ h₁ => exact Submodule.smul_mem _ (scal μ) h₁
  -- Step 4: the double centralizer theorem (a packaging of `jacobson_density`):
  -- every `End_{End_A(V)}(V)`-endomorphism of `V` is given by an element of `A`.
  have hsurj : Function.Surjective (Module.toModuleEnd (Module.End A V) (S := A) V) :=
    Module.Finite.toModuleEnd_moduleEnd_surjective
  rw [eq_top_iff]
  intro T _
  -- Any `T ∈ End_k(V)` is `End_A(V)`-linear, since `End_A(V)` consists of
  -- `k`-scalars by Step 2.
  let T' : Module.End (Module.End A V) V :=
    { toFun := T
      map_add' := fun a b => T.map_add a b
      map_smul' := fun g v => by
        obtain ⟨μ, hμ⟩ := hEnd' g
        show T (g v) = g (T v)
        rw [hμ, hμ, T.map_smul] }
  obtain ⟨a, ha⟩ := hsurj T'
  -- The element `a : A` produced by surjectivity is equal to `T` in `End_k(V)`.
  have haT : (a : Module.End k V) = T :=
    LinearMap.ext fun v => LinearMap.congr_fun ha v
  rw [← haT]
  exact a.2

/-! ## Lemma 1.6 : base change of `A = End_k(V)` -/

/-- **Lemma 1.6.** If the `k`-algebra generated by `ρ(G)` is all of `End_k(V)`,
then after base change along any field extension `l/k`, the `l`-algebra
generated by `(ρ.baseChange l)(G)` is all of `End_l(l ⊗[k] V)`. -/
lemma adjoinRange_baseChange_eq_top [FiniteDimensional k V]
    (l : Type*) [Field l] [Algebra k l]
    (h : adjoinRange ρ = ⊤) :
    adjoinRange (baseChange l ρ) = ⊤ := by
  sorry

/-! ## Step (iv) : fullness of `A` implies irreducibility -/

/-- If the algebra generated by `ρ(G)` is all of `End_k(V)` (and `V ≠ 0`), then
`ρ` is irreducible: any nonzero invariant subspace `W` contains, for `0 ≠ w ∈ W`
and any `v`, an element `T w = v` with `T ∈ A`, hence `W = ⊤`. -/
lemma isIrreducible_of_adjoinRange_eq_top [Nontrivial V]
    (h : adjoinRange ρ = ⊤) :
    IsIrreducible ρ := by
  sorry

/-! ## Descent of irreducibility (the easy direction) -/

/-- If the base change of `ρ` along some field extension `l/k` is irreducible,
then `ρ` itself is irreducible (an invariant subspace `W ⊊ V` gives rise to the
invariant subspace `l ⊗[k] W ⊊ l ⊗[k] V`). -/
lemma isIrreducible_of_baseChange (l : Type*) [Field l] [Algebra k l]
    (h : IsIrreducible (baseChange l ρ)) :
    IsIrreducible ρ := by
  sorry

/-! ## Main results -/

/-- The quantitative version of the hard direction: under the hypotheses of
Theorem 1.3, the base change of `ρ` to *any* field extension `l/k` is
irreducible. -/
theorem isIrreducible_baseChange_of_finrank_fixedSpace_eq_one
    [FiniteDimensional k V]
    (l : Type*) [Field l] [Algebra k l]
    (hirr : IsIrreducible ρ)
    {g : G} (hg : finrank k (fixedSpace ρ g) = 1) :
    IsIrreducible (baseChange l ρ) := by
  sorry

/-- **Proposition 1.2 / Theorem 1.3.** Let `V` be a finite-dimensional vector
space over `k` and `ρ : G →* GL(V)` a representation.  If some `g : G` has a
one-dimensional fixed subspace `V^g`, then `V` is irreducible if and only if it
is absolutely irreducible. -/
theorem isIrreducible_iff_isAbsolutelyIrreducible
    [FiniteDimensional k V]
    {g : G} (hg : finrank k (fixedSpace ρ g) = 1) :
    IsIrreducible ρ ↔ IsAbsolutelyIrreducible ρ := by
  unfold IsAbsolutelyIrreducible
  constructor
  · -- hard direction: irreducible ⇒ irreducible after base change to `k̄`
    intro hirr
    exact isIrreducible_baseChange_of_finrank_fixedSpace_eq_one ρ
      (AlgebraicClosure k) hirr hg
  · -- easy direction: irreducibility descends along `k → k̄`
    intro habs
    exact isIrreducible_of_baseChange ρ (AlgebraicClosure k) habs

end OddRep
