/-
# Irreducible ↔ absolutely irreducible, given a 1-dimensional fixed space

This file states (with `sorry`ed proofs) Proposition 1.2 / Theorem 1.3 of the
blueprint "Odd_Rep_Irreducible" (July 6, 2026), together with all the
supporting lemmas from the blueprint:

* `OddRep.exists_smul_eq_of_commute`        — Lemma 1.4  (`End_G(V) = k`)
* `OddRep.adjoinRange_eq_top`               — Lemma 1.5  (Jacobson density: `A = End_k(V)`)
* `OddRep.adjoinRange_baseChange_eq_top`    — Lemma 1.6  (base change of `A = End_k(V)`)
* `OddRep.smul_tmul_mem_range_iff`          — Fact 1.1   (`l·e ∩ V = k·e` inside `V_l`)
* `OddRep.isIrreducible_of_adjoinRange_eq_top` — step (iv) of the blueprint
* `OddRep.isIrreducible_of_baseChange`      — descent of irreducibility (easy direction)
* `OddRep.isIrreducible_iff_isAbsolutelyIrreducible` — Proposition 1.2 / Theorem 1.3

Conventions:
* Representations are `Representation k G V := G →* (V →ₗ[k] V)` as in Mathlib.
* All new definitions live in the `OddRep` namespace to avoid clashing with
  declarations such as `Representation.IsIrreducible` that exist in current
  Mathlib / FLT.  If the library notions agree with the ones below, the
  statements can later be re-phrased in terms of the library definitions.
* "Absolutely irreducible" is defined here as: the base change to
  `AlgebraicClosure k` is irreducible.  (The blueprint's proof in fact shows
  irreducibility after base change to *any* field extension `l/k`; this is
  recorded separately as
  `OddRep.isIrreducible_baseChange_of_finrank_fixedSpace_eq_one`.)
-/

import Mathlib

open scoped TensorProduct

open Module

namespace OddRep

variable {k : Type*} [Field k]
variable {G : Type*} [Monoid G]
variable {V : Type*} [AddCommGroup V] [Module k V]

/-! ## Definitions -/

/-- A `k`-subspace `W ⊆ V` is invariant under the representation `ρ`. -/
def IsInvariant (ρ : Representation k G V) (W : Submodule k V) : Prop :=
  ∀ g : G, ∀ v ∈ W, ρ g v ∈ W

/-- A representation is irreducible if `V ≠ 0` and the only invariant subspaces
are `⊥` and `⊤`. -/
def IsIrreducible (ρ : Representation k G V) : Prop :=
  Nontrivial V ∧ ∀ W : Submodule k V, IsInvariant ρ W → W = ⊥ ∨ W = ⊤

/-- The fixed subspace `V^g = {v : ρ(g) v = v}` of a single group element. -/
def fixedSpace (ρ : Representation k G V) (g : G) : Submodule k V :=
  LinearMap.ker (ρ g - LinearMap.id)

/-- Base change of a representation along a field extension `l/k`:
`G` acts on `l ⊗[k] V` by `1 ⊗ ρ(g)`. -/
noncomputable def baseChange (l : Type*) [Field l] [Algebra k l]
    (ρ : Representation k G V) : Representation l G (l ⊗[k] V) where
  toFun g := (ρ g).baseChange l
  map_one' := by sorry
  map_mul' := by sorry

/-- The `k`-subalgebra `A ⊆ End_k(V)` generated by the image of `ρ`. -/
def adjoinRange (ρ : Representation k G V) : Subalgebra k (Module.End k V) :=
  Algebra.adjoin k (Set.range ρ)

/-- A representation is absolutely irreducible if it remains irreducible after
base change to an algebraic closure of `k`. -/
def IsAbsolutelyIrreducible (ρ : Representation k G V) : Prop :=
  IsIrreducible (baseChange (AlgebraicClosure k) ρ)

variable (ρ : Representation k G V)

/-! ## Fact 1.1 : `l·e ∩ V = k·e` inside `V_l` -/

/-- **Fact 1.1.** If `e ≠ 0` in `V`, then for `c : l`, the element `c ⊗ e` of
`l ⊗[k] V` lies in the image of the canonical map `V → l ⊗[k] V`, `v ↦ 1 ⊗ v`,
if and only if `c` comes from `k`. -/
lemma smul_tmul_mem_range_iff (l : Type*) [Field l] [Algebra k l]
    {e : V} (he : e ≠ 0) (c : l) :
    c ⊗ₜ[k] e ∈ LinearMap.range (TensorProduct.mk k l V 1) ↔
      ∃ a : k, algebraMap k l a = c := by
  sorry

/-! ## Lemma 1.4 : `End_G(V) = k` -/

/-- **Lemma 1.4.** If `ρ` is irreducible and some `g : G` has a one-dimensional
fixed subspace, then every `G`-equivariant endomorphism of `V` is scalar. -/
lemma exists_smul_eq_of_commute
    (hirr : IsIrreducible ρ)
    {g : G} (hg : finrank k (fixedSpace ρ g) = 1)
    (T : Module.End k V) (hT : ∀ h : G, Commute (ρ h) T) :
    ∃ μ : k, T = μ • (1 : Module.End k V) := by
  sorry

/-! ## Lemma 1.5 : Jacobson density, `A = End_k(V)` -/

/-- **Lemma 1.5.** Let `A ⊆ End_k(V)` be the `k`-algebra generated by `ρ(G)`.
If `V` is finite-dimensional, `ρ` is irreducible, and every `G`-equivariant
endomorphism of `V` is scalar, then `A = End_k(V)`. -/
lemma adjoinRange_eq_top [FiniteDimensional k V]
    (hirr : IsIrreducible ρ)
    (hEnd : ∀ T : Module.End k V, (∀ h : G, Commute (ρ h) T) →
      ∃ μ : k, T = μ • (1 : Module.End k V)) :
    adjoinRange ρ = ⊤ := by
  sorry

/-! ## Lemma 1.6 : base change of `A = End_k(V)` -/

/-- **Lemma 1.6.** If the `k`-algebra generated by `ρ(G)` is all of `End_k(V)`,
then after base change along any field extension `l/k`, the `l`-algebra
generated by `(ρ.baseChange l)(G)` is all of `End_l(l ⊗[k] V)`. -/
lemma adjoinRange_baseChange_eq_top [FiniteDimensional k V]
    (l : Type*) [Field l] [Algebra k l]
    (h : adjoinRange ρ = ⊤) :
    adjoinRange (baseChange l ρ) = ⊤ := by
  sorry

/-! ## Step (iv) : fullness of `A` implies irreducibility -/

/-- If the algebra generated by `ρ(G)` is all of `End_k(V)` (and `V ≠ 0`), then
`ρ` is irreducible: any nonzero invariant subspace `W` contains, for `0 ≠ w ∈ W`
and any `v`, an element `T w = v` with `T ∈ A`, hence `W = ⊤`. -/
lemma isIrreducible_of_adjoinRange_eq_top [Nontrivial V]
    (h : adjoinRange ρ = ⊤) :
    IsIrreducible ρ := by
  sorry

/-! ## Descent of irreducibility (the easy direction) -/

/-- If the base change of `ρ` along some field extension `l/k` is irreducible,
then `ρ` itself is irreducible (an invariant subspace `W ⊊ V` gives rise to the
invariant subspace `l ⊗[k] W ⊊ l ⊗[k] V`). -/
lemma isIrreducible_of_baseChange (l : Type*) [Field l] [Algebra k l]
    (h : IsIrreducible (baseChange l ρ)) :
    IsIrreducible ρ := by
  sorry

/-! ## Main results -/

/-- The quantitative version of the hard direction: under the hypotheses of
Theorem 1.3, the base change of `ρ` to *any* field extension `l/k` is
irreducible. -/
theorem isIrreducible_baseChange_of_finrank_fixedSpace_eq_one
    [FiniteDimensional k V]
    (l : Type*) [Field l] [Algebra k l]
    (hirr : IsIrreducible ρ)
    {g : G} (hg : finrank k (fixedSpace ρ g) = 1) :
    IsIrreducible (baseChange l ρ) := by
  sorry

/-- **Proposition 1.2 / Theorem 1.3.** Let `V` be a finite-dimensional vector
space over `k` and `ρ : G →* GL(V)` a representation.  If some `g : G` has a
one-dimensional fixed subspace `V^g`, then `V` is irreducible if and only if it
is absolutely irreducible. -/
theorem isIrreducible_iff_isAbsolutelyIrreducible
    [FiniteDimensional k V]
    {g : G} (hg : finrank k (fixedSpace ρ g) = 1) :
    IsIrreducible ρ ↔ IsAbsolutelyIrreducible ρ := by
  unfold IsAbsolutelyIrreducible
  constructor
  · -- hard direction: irreducible ⇒ irreducible after base change to `k̄`
    intro hirr
    exact isIrreducible_baseChange_of_finrank_fixedSpace_eq_one ρ
      (AlgebraicClosure k) hirr hg
  · -- easy direction: irreducibility descends along `k → k̄`
    intro habs
    exact isIrreducible_of_baseChange ρ (AlgebraicClosure k) habs

end OddRep
