/-
# Irreducible ↔ absolutely irreducible, given a 1-dimensional fixed space

This file states (with `sorry`ed proofs) Proposition 1.2 / Theorem 1.3 of the
blueprint "Odd_Rep_Irreducible" (July 6, 2026), together with all the
supporting lemmas from the blueprint:

* `OddRep.exists_smul_eq_of_commute`        — Lemma 1.4  (`End_G(V) = k`)
* `OddRep.adjoinRange_eq_top`               — Lemma 1.5  (Jacobson density: `A = End_k(V)`)
* `OddRep.adjoinRange_baseChange_eq_top`    — Lemma 1.6  (base change of `A = End_k(V)`)
* `OddRep.smul_tmul_mem_range_iff`          — Fact 1.1   (`l·e ∩ V = k·e` inside `V_l`)
* `OddRep.isIrreducible_of_adjoinRange_eq_top` — step (iv) of the blueprint
* `OddRep.isIrreducible_of_baseChange`      — descent of irreducibility (easy direction)
* `OddRep.isIrreducible_iff_isAbsolutelyIrreducible` — Proposition 1.2 / Theorem 1.3

Conventions:
* Representations are `Representation k G V := G →* (V →ₗ[k] V)` as in Mathlib.
* All new definitions live in the `OddRep` namespace to avoid clashing with
  declarations such as `Representation.IsIrreducible` that exist in current
  Mathlib / FLT.  If the library notions agree with the ones below, the
  statements can later be re-phrased in terms of the library definitions.
* "Absolutely irreducible" is defined here as: the base change to
  `AlgebraicClosure k` is irreducible.  (The blueprint's proof in fact shows
  irreducibility after base change to *any* field extension `l/k`; this is
  recorded separately as
  `OddRep.isIrreducible_baseChange_of_finrank_fixedSpace_eq_one`.)
-/

import Mathlib

open scoped TensorProduct

open Module

namespace OddRep

variable {k : Type*} [Field k]
variable {G : Type*} [Monoid G]
variable {V : Type*} [AddCommGroup V] [Module k V]

/-! ## Definitions -/

/-- A `k`-subspace `W ⊆ V` is invariant under the representation `ρ`. -/
def IsInvariant (ρ : Representation k G V) (W : Submodule k V) : Prop :=
  ∀ g : G, ∀ v ∈ W, ρ g v ∈ W

/-- A representation is irreducible if `V ≠ 0` and the only invariant subspaces
are `⊥` and `⊤`. -/
def IsIrreducible (ρ : Representation k G V) : Prop :=
  Nontrivial V ∧ ∀ W : Submodule k V, IsInvariant ρ W → W = ⊥ ∨ W = ⊤

/-- The fixed subspace `V^g = {v : ρ(g) v = v}` of a single group element. -/
def fixedSpace (ρ : Representation k G V) (g : G) : Submodule k V :=
  LinearMap.ker (ρ g - LinearMap.id)

/-- Base change of a representation along a field extension `l/k`:
`G` acts on `l ⊗[k] V` by `1 ⊗ ρ(g)`. -/
noncomputable def baseChange (l : Type*) [Field l] [Algebra k l]
    (ρ : Representation k G V) : Representation l G (l ⊗[k] V) where
  toFun g := (ρ g).baseChange l
  map_one' := by
    change (ρ 1).baseChange l = 1
    have h1 : ρ 1 = LinearMap.id := by rw [map_one]; rfl
    rw [h1, LinearMap.baseChange_id]
    rfl
  map_mul' := fun g h => by
    change (ρ (g * h)).baseChange l = (ρ g).baseChange l * (ρ h).baseChange l
    have h1 : ρ (g * h) = (ρ g).comp (ρ h) := by rw [map_mul]; rfl
    rw [h1, LinearMap.baseChange_comp]
    rfl

/-- The `k`-subalgebra `A ⊆ End_k(V)` generated by the image of `ρ`. -/
def adjoinRange (ρ : Representation k G V) : Subalgebra k (Module.End k V) :=
  Algebra.adjoin k (Set.range ρ)

/-- A representation is absolutely irreducible if it remains irreducible after
base change to an algebraic closure of `k`. -/
def IsAbsolutelyIrreducible (ρ : Representation k G V) : Prop :=
  IsIrreducible (baseChange (AlgebraicClosure k) ρ)

variable (ρ : Representation k G V)

/-! ## Fact 1.1 : `l·e ∩ V = k·e` inside `V_l` -/

/-- **Fact 1.1.** If `e ≠ 0` in `V`, then for `c : l`, the element `c ⊗ e` of
`l ⊗[k] V` lies in the image of the canonical map `V → l ⊗[k] V`, `v ↦ 1 ⊗ v`,
if and only if `c` comes from `k`. -/
lemma smul_tmul_mem_range_iff (l : Type*) [Field l] [Algebra k l]
    {e : V} (he : e ≠ 0) (c : l) :
    c ⊗ₜ[k] e ∈ LinearMap.range (TensorProduct.mk k l V 1) ↔
      ∃ a : k, algebraMap k l a = c := by
  constructor
  · -- Forward: if `c ⊗ₜ e = 1 ⊗ₜ w`, apply `id ⊗ φ` for a functional `φ` with `φ e = 1`.
    rintro ⟨w, hw⟩
    -- `hw : 1 ⊗ₜ w = c ⊗ₜ e`
    obtain ⟨φ, hφ⟩ := Module.Projective.exists_dual_eq_one k he
    -- `ψ : l ⊗[k] V → l`, `x ⊗ₜ v ↦ φ v • x`.
    set ψ : l ⊗[k] V →ₗ[k] l :=
      (TensorProduct.rid k l).toLinearMap ∘ₗ LinearMap.lTensor l φ with hψ
    refine ⟨φ w, ?_⟩
    have key := congrArg ψ hw
    simp only [hψ, LinearMap.coe_comp, Function.comp_apply, TensorProduct.mk_apply,
      LinearMap.lTensor_tmul, LinearEquiv.coe_coe, TensorProduct.rid_tmul] at key
    -- `key : φ w • (1 : l) = φ e • c`
    rw [hφ, one_smul] at key
    rw [Algebra.algebraMap_eq_smul_one]
    exact key
  · -- Reverse: `algebraMap k l a ⊗ₜ e = 1 ⊗ₜ (a • e)`.
    rintro ⟨a, rfl⟩
    refine ⟨a • e, ?_⟩
    rw [TensorProduct.mk_apply, TensorProduct.tmul_smul, TensorProduct.smul_tmul',
      Algebra.algebraMap_eq_smul_one]

/-! ## Lemma 1.4 : `End_G(V) = k` -/

/-- **Lemma 1.4.** If `ρ` is irreducible and some `g : G` has a one-dimensional
fixed subspace, then every `G`-equivariant endomorphism of `V` is scalar. -/
lemma exists_smul_eq_of_commute
    (hirr : IsIrreducible ρ)
    {g : G} (hg : finrank k (fixedSpace ρ g) = 1)
    (T : Module.End k V) (hT : ∀ h : G, Commute (ρ h) T) :
    ∃ μ : k, T = μ • (1 : Module.End k V) := by
  obtain ⟨-, hsub⟩ := hirr
  -- Membership in the fixed space, in applied form.
  have hfix : ∀ v : V, v ∈ fixedSpace ρ g ↔ ρ g v = v := fun v => by
    simp [fixedSpace, LinearMap.mem_ker, LinearMap.sub_apply, LinearMap.id_apply,
      sub_eq_zero]
  -- `T` preserves the fixed space, because it commutes with `ρ g`.
  have hTfix : ∀ v ∈ fixedSpace ρ g, T v ∈ fixedSpace ρ g := by
    intro v hv
    rw [hfix] at hv ⊢
    have hc := LinearMap.congr_fun (hT g) v
    simp only [Module.End.mul_apply] at hc
    -- hc : ρ g (T v) = T (ρ g v)
    rw [hc, hv]
  -- Pick a nonzero vector spanning the one-dimensional fixed space.
  rw [finrank_eq_one_iff'] at hg
  obtain ⟨v, hv0, hspan⟩ := hg
  have hv0' : (v : V) ≠ 0 := fun h => hv0 (Subtype.ext h)
  -- `T v` lies in the fixed space, hence is a multiple `μ • v` of `v`.
  obtain ⟨μ, hμ⟩ := hspan ⟨T (v : V), hTfix (v : V) v.2⟩
  have hμ' : μ • (v : V) = T (v : V) := by
    have h1 := congrArg Subtype.val hμ
    simpa using h1
  refine ⟨μ, ?_⟩
  -- The kernel of `T - μ` is `G`-invariant ...
  have hKinv : IsInvariant ρ (LinearMap.ker (T - μ • (1 : Module.End k V))) := by
    intro h w hw
    rw [LinearMap.mem_ker] at hw ⊢
    have hc := LinearMap.congr_fun (hT h) w
    simp only [Module.End.mul_apply] at hc
    -- hc : ρ h (T w) = T (ρ h w)
    simp only [LinearMap.sub_apply, LinearMap.smul_apply, Module.End.one_apply] at hw ⊢
    -- hw : T w - μ • w = 0 ; goal : T (ρ h w) - μ • ρ h w = 0
    rw [← hc, ← map_smul, ← map_sub, hw, map_zero]
  -- ... and contains the nonzero vector `v`, hence equals `⊤` by irreducibility.
  have hvK : (v : V) ∈ LinearMap.ker (T - μ • (1 : Module.End k V)) := by
    rw [LinearMap.mem_ker]
    simp only [LinearMap.sub_apply, LinearMap.smul_apply, Module.End.one_apply]
    rw [← hμ']
    exact sub_self _
  rcases hsub _ hKinv with hbot | htop
  · exfalso
    rw [hbot] at hvK
    exact hv0' (by simpa using hvK)
  · -- the kernel is everything, so `T = μ • 1`
    refine LinearMap.ext fun w => ?_
    have hw : w ∈ LinearMap.ker (T - μ • (1 : Module.End k V)) := by
      rw [htop]; exact Submodule.mem_top
    rw [LinearMap.mem_ker] at hw
    simp only [LinearMap.sub_apply, LinearMap.smul_apply, Module.End.one_apply] at hw
    simpa [sub_eq_zero] using hw

/-! ## Lemma 1.5 : Jacobson density, `A = End_k(V)` -/

/-- **Lemma 1.5.** Let `A ⊆ End_k(V)` be the `k`-algebra generated by `ρ(G)`.
If `V` is finite-dimensional, `ρ` is irreducible, and every `G`-equivariant
endomorphism of `V` is scalar, then `A = End_k(V)`. -/
lemma adjoinRange_eq_top [FiniteDimensional k V]
    (hirr : IsIrreducible ρ)
    (hEnd : ∀ T : Module.End k V, (∀ h : G, Commute (ρ h) T) →
      ∃ μ : k, T = μ • (1 : Module.End k V)) :
    adjoinRange ρ = ⊤ := by
  obtain ⟨hnt, hsub⟩ := hirr
  haveI : Nontrivial V := hnt
  set A := adjoinRange ρ with hA
  -- `ρ g` lies in `A` for every `g`.
  have hρmem : ∀ g : G, ρ g ∈ A := fun g => Algebra.subset_adjoin ⟨g, rfl⟩
  -- The action of an element of `A` on `V` is application of the endomorphism.
  have hsmul : ∀ (a : A) (v : V), a • v = (a : Module.End k V) v := fun _ _ => rfl
  -- The scalar `μ : k`, viewed inside `A`, acts as `μ • ·`.
  have halg : ∀ (μ : k) (v : V),
      (⟨algebraMap k (Module.End k V) μ, A.algebraMap_mem μ⟩ : A) • v = μ • v := by
    intro μ v
    change (algebraMap k (Module.End k V) μ) v = μ • v
    simp [Module.algebraMap_end_apply]
  -- Scaling by `μ : k` is an `A`-linear endomorphism of `V`
  -- (elements of `A` are `k`-linear, so they commute with `k`-scalars).
  let scal : k → Module.End A V := fun μ =>
    { toFun := fun v => μ • v
      map_add' := fun a b => smul_add μ a b
      map_smul' := fun a v => ((a : Module.End k V).map_smul μ v).symm }
  -- Step 1: `V` is a simple `A`-module: a nonzero proper `A`-submodule would be
  -- a nonzero proper `G`-invariant `k`-subspace, contradicting irreducibility.
  haveI hAsimple : IsSimpleModule A V := by
    haveI : Nontrivial (Submodule A V) := by
      obtain ⟨v, hv⟩ := exists_ne (0 : V)
      refine ⟨⊥, ⊤, fun hbt => hv ?_⟩
      have hmem : v ∈ (⊥ : Submodule A V) := by rw [hbt]; exact Submodule.mem_top
      simpa using hmem
    rw [isSimpleModule_iff]
    refine ⟨fun W => ?_⟩
    -- view `W` as a `k`-subspace of `V`
    let Wk : Submodule k V :=
      { carrier := (W : Set V)
        add_mem' := fun ha hb => W.add_mem ha hb
        zero_mem' := W.zero_mem
        smul_mem' := fun μ {v} hv => by
          have h1 := W.smul_mem
            (⟨algebraMap k (Module.End k V) μ, A.algebraMap_mem μ⟩ : A) hv
          rwa [halg] at h1 }
    have hWk : IsInvariant ρ Wk := by
      intro g v hv
      exact W.smul_mem (⟨ρ g, hρmem g⟩ : A) hv
    rcases hsub Wk hWk with hbot | htop
    · left
      rw [Submodule.eq_bot_iff] at hbot ⊢
      exact fun v hv => hbot v hv
    · right
      rw [Submodule.eq_top_iff'] at htop ⊢
      exact fun v => htop v
  -- Step 2: every `A`-linear endomorphism of `V` is a `k`-scalar (uses `hEnd`).
  have hEnd' : ∀ f : Module.End A V, ∃ μ : k, ∀ v : V, f v = μ • v := by
    intro f
    -- `f` is in particular `k`-linear ...
    let fk : Module.End k V :=
      { toFun := f
        map_add' := fun a b => f.map_add a b
        map_smul' := fun μ v => by
          have h1 := f.map_smul
            (⟨algebraMap k (Module.End k V) μ, A.algebraMap_mem μ⟩ : A) v
          rw [halg, halg] at h1
          simp [h1] }
    -- ... and commutes with every `ρ h`, since `ρ h ∈ A`.
    have hcomm : ∀ h : G, Commute (ρ h) fk := by
      intro h
      change ρ h * fk = fk * ρ h
      refine LinearMap.ext fun v => ?_
      change ρ h (f v) = f (ρ h v)
      exact (f.map_smul (⟨ρ h, hρmem h⟩ : A) v).symm
    have hfk : ∀ w : V, fk w = f w := fun _ => rfl
    obtain ⟨μ, hμ⟩ := hEnd fk hcomm
    refine ⟨μ, fun v => ?_⟩
    have h1 := LinearMap.congr_fun hμ v
    rw [hfk] at h1
    simpa using h1
  -- Step 3: `V` is module-finite over `End_A(V)`: a finite `k`-spanning set
  -- still spans, because `k`-scalars act through `End_A(V)` via `scal`.
  haveI : Module.Finite (Module.End A V) V := by
    obtain ⟨s, hs⟩ := Module.Finite.fg_top (R := k) (M := V)
    refine ⟨⟨s, ?_⟩⟩
    rw [eq_top_iff]
    rintro v -
    have hv : v ∈ Submodule.span k (s : Set V) := by rw [hs]; exact Submodule.mem_top
    induction hv using Submodule.span_induction with
    | mem x hx => exact Submodule.subset_span hx
    | zero => exact Submodule.zero_mem _
    | add x y _ _ h₁ h₂ => exact Submodule.add_mem _ h₁ h₂
    | smul μ x _ h₁ => exact Submodule.smul_mem _ (scal μ) h₁
  -- Step 4: the double centralizer theorem (a packaging of `jacobson_density`):
  -- every `End_{End_A(V)}(V)`-endomorphism of `V` is given by an element of `A`.
  have hsurj : Function.Surjective (Module.toModuleEnd (Module.End A V) (S := A) V) :=
    Module.Finite.toModuleEnd_moduleEnd_surjective
  rw [eq_top_iff]
  intro T _
  -- Any `T ∈ End_k(V)` is `End_A(V)`-linear, since `End_A(V)` consists of
  -- `k`-scalars by Step 2.
  let T' : Module.End (Module.End A V) V :=
    { toFun := T
      map_add' := fun a b => T.map_add a b
      map_smul' := fun g v => by
        obtain ⟨μ, hμ⟩ := hEnd' g
        change T (g v) = g (T v)
        rw [hμ, hμ, T.map_smul] }
  obtain ⟨a, ha⟩ := hsurj T'
  -- The element `a : A` produced by surjectivity is equal to `T` in `End_k(V)`.
  have haT : (a : Module.End k V) = T :=
    LinearMap.ext fun v => LinearMap.congr_fun ha v
  rw [← haT]
  exact a.2

/-! ## Lemma 1.6 : base change of `A = End_k(V)` -/

/-- **Lemma 1.6.** If the `k`-algebra generated by `ρ(G)` is all of `End_k(V)`,
then after base change along any field extension `l/k`, the `l`-algebra
generated by `(ρ.baseChange l)(G)` is all of `End_l(l ⊗[k] V)`. -/
lemma adjoinRange_baseChange_eq_top [FiniteDimensional k V]
    (l : Type*) [Field l] [Algebra k l]
    (h : adjoinRange ρ = ⊤) :
    adjoinRange (baseChange l ρ) = ⊤ := by
  classical
  -- `E : End_k V →ₐ[k] End_l (l ⊗ V)`, `T ↦ T.baseChange l` (base change of endomorphisms).
  set E : Module.End k V →ₐ[k] Module.End l (l ⊗[k] V) :=
    Module.End.baseChangeHom k l V with hE
  have hEapp : ∀ T : Module.End k V, E T = LinearMap.baseChange l T := fun T => rfl
  -- The generators base change correctly: `(baseChange l ρ) g = E (ρ g)`.
  have hgen : ∀ g : G, baseChange l ρ g = E (ρ g) := fun g => by rw [hEapp]; rfl
  -- Step 1 : since `A = End_k V = ⊤`, every `E T` lies in `B := adjoinRange (baseChange l ρ)`.
  have hrange : ∀ T : Module.End k V, E T ∈ adjoinRange (baseChange l ρ) := by
    have hmap : (adjoinRange ρ).map E ≤
        Subalgebra.restrictScalars k (adjoinRange (baseChange l ρ)) := by
      rw [adjoinRange, ← Algebra.adjoin_image]
      apply Algebra.adjoin_le
      rintro _ ⟨_, ⟨g, rfl⟩, rfl⟩
      simp only [SetLike.mem_coe, Subalgebra.mem_restrictScalars]
      rw [← hgen g]
      exact Algebra.subset_adjoin (Set.mem_range_self g)
    intro T
    have hTmem : E T ∈ (adjoinRange ρ).map E :=
      Subalgebra.mem_map.mpr ⟨T, by rw [h]; exact Algebra.mem_top, rfl⟩
    have := hmap hTmem
    rwa [Subalgebra.mem_restrictScalars] at this
  -- Step 2 : the images `E (b.end ij)` of the matrix-unit basis of `End_k V` are a basis of
  -- `End_l (l ⊗ V)`, so `E` has `l`-dense image; combined with Step 1 this forces `B = ⊤`.
  set ι := Module.Free.ChooseBasisIndex k V with hι
  set b : Basis ι k V := Module.Free.chooseBasis k V with hb
  set bl : Basis ι l (l ⊗[k] V) := Algebra.TensorProduct.basis l b with hbl
  have hsub : Set.range ⇑bl.end ⊆ Set.range ⇑E := by
    rintro _ ⟨ij, rfl⟩
    exact ⟨b.end ij, by rw [hEapp]; exact b.baseChange_end (A := l) ij⟩
  have hspan : Submodule.span l (Set.range ⇑E) = ⊤ := by
    rw [eq_top_iff, ← bl.end.span_eq]
    exact Submodule.span_mono hsub
  -- Conclude.
  rw [eq_top_iff]
  intro x _
  have hxspan : x ∈ Submodule.span l (Set.range ⇑E) := by rw [hspan]; exact Submodule.mem_top
  have hle : Submodule.span l (Set.range ⇑E) ≤
      Subalgebra.toSubmodule (adjoinRange (baseChange l ρ)) := by
    rw [Submodule.span_le]
    rintro _ ⟨T, rfl⟩
    exact hrange T
  exact hle hxspan

/-! ## Step (iv) : fullness of `A` implies irreducibility -/

/-- If the algebra generated by `ρ(G)` is all of `End_k(V)` (and `V ≠ 0`), then
`ρ` is irreducible: any nonzero invariant subspace `W` contains, for `0 ≠ w ∈ W`
and any `v`, an element `T w = v` with `T ∈ A`, hence `W = ⊤`. -/
lemma isIrreducible_of_adjoinRange_eq_top [Nontrivial V]
    (h : adjoinRange ρ = ⊤) :
    IsIrreducible ρ := by
  refine ⟨inferInstance, fun W hW => ?_⟩
  -- `W` is stable under the whole algebra generated by `ρ(G)` ...
  have hWA : ∀ T : Module.End k V, T ∈ adjoinRange ρ → ∀ w ∈ W, T w ∈ W := by
    intro T hT
    have hT' : T ∈ Algebra.adjoin k (Set.range ⇑ρ) := hT
    clear hT
    induction hT' using Algebra.adjoin_induction with
    | mem x hx =>
        obtain ⟨g, rfl⟩ := hx
        exact hW g
    | algebraMap r =>
        intro w hw
        have h1 : (algebraMap k (Module.End k V) r) w = r • w := by
          simp [Module.algebraMap_end_apply]
        rw [h1]
        exact W.smul_mem r hw
    | add x y _ _ ihx ihy =>
        intro w hw
        rw [LinearMap.add_apply]
        exact W.add_mem (ihx w hw) (ihy w hw)
    | mul x y _ _ ihx ihy =>
        intro w hw
        rw [Module.End.mul_apply]
        exact ihx _ (ihy w hw)
  -- ... hence under every endomorphism of `V`, since the algebra is everything.
  have hWall : ∀ T : Module.End k V, ∀ w ∈ W, T w ∈ W := fun T =>
    hWA T (by rw [h]; exact Algebra.mem_top)
  rcases eq_or_ne W ⊥ with hbot | hne
  · exact Or.inl hbot
  · right
    obtain ⟨w, hwW, hw0⟩ := (Submodule.ne_bot_iff W).mp hne
    rw [Submodule.eq_top_iff']
    intro v
    -- Choose a linear functional not vanishing on `w`.
    obtain ⟨φ, hφ0⟩ : ∃ φ : Module.Dual k V, φ w ≠ 0 := by
      by_contra hall
      push Not at hall
      apply hw0
      rw [← Module.forall_dual_apply_eq_zero_iff k]
      exact hall
    -- The endomorphism `x ↦ ((φ w)⁻¹ * φ x) • v` maps `w` to `v`, and it
    -- preserves `W`, so `v ∈ W`.
    have hTw : (((φ w)⁻¹ • φ).smulRight v) w = v := by
      simp [LinearMap.smulRight_apply, LinearMap.smul_apply, smul_eq_mul,
        inv_mul_cancel₀ hφ0]
    have h2 := hWall (((φ w)⁻¹ • φ).smulRight v) w hwW
    rwa [hTw] at h2

/-! ## Descent of irreducibility (the easy direction) -/

/-- If the base change of `ρ` along some field extension `l/k` is irreducible,
then `ρ` itself is irreducible (an invariant subspace `W ⊊ V` gives rise to the
invariant subspace `l ⊗[k] W ⊊ l ⊗[k] V`). -/
lemma isIrreducible_of_baseChange (l : Type*) [Field l] [Algebra k l]
    (h : IsIrreducible (baseChange l ρ)) :
    IsIrreducible ρ := by
  refine ⟨?_, ?_⟩
  · -- `Nontrivial V` : otherwise `l ⊗[k] V` would be trivial, contradicting `h.1`.
    by_contra hV
    rw [not_nontrivial_iff_subsingleton] at hV
    haveI : Subsingleton V := hV
    haveI : Subsingleton (l ⊗[k] V) := by
      refine ⟨fun a b => ?_⟩
      have hz : ∀ x : l ⊗[k] V, x = 0 := fun x => by
        induction x using TensorProduct.induction_on with
        | zero => rfl
        | tmul a v => rw [Subsingleton.elim v (0 : V), TensorProduct.tmul_zero]
        | add a b ha hb => rw [ha, hb, add_zero]
      rw [hz a, hz b]
    exact not_nontrivial_iff_subsingleton.mpr inferInstance h.1
  · -- Any invariant `W` gives an invariant `l ⊗[k] W`, which is `⊥`/`⊤` by `h`; descend.
    intro W hW
    have hinv : IsInvariant (baseChange l ρ) (W.baseChange l) := by
      intro g x hx
      change LinearMap.baseChange l (ρ g) x ∈ W.baseChange l
      rw [Submodule.baseChange_eq_span] at hx
      induction hx using Submodule.span_induction with
      | mem y hy =>
        obtain ⟨w, hw, rfl⟩ := hy
        simp only [TensorProduct.mk_apply, LinearMap.baseChange_tmul]
        exact Submodule.tmul_mem_baseChange_of_mem 1 (hW g w hw)
      | zero => rw [map_zero]; exact Submodule.zero_mem _
      | add a b _ _ ha hb => rw [map_add]; exact Submodule.add_mem _ ha hb
      | smul c a _ ha => rw [map_smul]; exact Submodule.smul_mem _ c ha
    rcases h.2 (W.baseChange l) hinv with hb | ht
    · exact Or.inl <| Submodule.baseChange_injective (A := l)
        (hb.trans (Submodule.baseChange_bot (R := k) (M := V) (A := l)).symm)
    · exact Or.inr <| Submodule.baseChange_injective (A := l)
        (ht.trans (Submodule.baseChange_top (R := k) (M := V) (A := l)).symm)

/-! ## Main results -/

/-- The quantitative version of the hard direction: under the hypotheses of
Theorem 1.3, the base change of `ρ` to *any* field extension `l/k` is
irreducible. -/
theorem isIrreducible_baseChange_of_finrank_fixedSpace_eq_one
    [FiniteDimensional k V]
    (l : Type*) [Field l] [Algebra k l]
    (hirr : IsIrreducible ρ)
    {g : G} (hg : finrank k (fixedSpace ρ g) = 1) :
    IsIrreducible (baseChange l ρ) := by
  sorry

/-- **Proposition 1.2 / Theorem 1.3.** Let `V` be a finite-dimensional vector
space over `k` and `ρ : G →* GL(V)` a representation.  If some `g : G` has a
one-dimensional fixed subspace `V^g`, then `V` is irreducible if and only if it
is absolutely irreducible. -/
theorem isIrreducible_iff_isAbsolutelyIrreducible
    [FiniteDimensional k V]
    {g : G} (hg : finrank k (fixedSpace ρ g) = 1) :
    IsIrreducible ρ ↔ IsAbsolutelyIrreducible ρ := by
  unfold IsAbsolutelyIrreducible
  constructor
  · -- hard direction: irreducible ⇒ irreducible after base change to `k̄`
    intro hirr
    exact isIrreducible_baseChange_of_finrank_fixedSpace_eq_one ρ
      (AlgebraicClosure k) hirr hg
  · -- easy direction: irreducibility descends along `k → k̄`
    intro habs
    exact isIrreducible_of_baseChange ρ (AlgebraicClosure k) habs

end OddRep
