/-
Copyright (c) 2026 Kevin Buzzard. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Michael Stoll, Claude
-/
module

public import FLT.Mathlib.RingTheory.DiscreteValuationRing.AdjoinRoot
public import FLT.Mathlib.RingTheory.DiscreteValuationRing.Separable

import Mathlib.Algebra.Polynomial.Eval.Irreducible
import Mathlib.RingTheory.Polynomial.GaussLemma

/-!
# Unramified lifts of separable residue field extensions

A finite separable extension `k'` of the residue field `k` of a discrete valuation ring `R`
(with fraction field `K`) lifts to an *unramified* extension `L/K` of the same degree: writing
`k' = k[X]/(p̄)` via a power basis (primitive element), we lift `p̄` to a monic `P ∈ R[X]` and set
`L = K[X]/(P)`. The integral extension `S = R[X]/(P)` is again a discrete valuation ring, with
`S/πS ≅ k[X]/(p̄) = k'` — so its maximal ideal is generated by a uniformizer `π` of `R`
(ramification index `1`) and its residue field is `k'`.

The ingredients — `AdjoinRoot.isDiscreteValuationRing_of_irreducible_map_residue` (`R[X]/(P)` is
an unramified discrete valuation ring for monic `P` with irreducible reduction, in
`FLT.Mathlib.RingTheory.AdjoinRoot`) and the separability transfer
`Polynomial.Monic.separable_map_algebraMap_of_separable_map_residue` (in
`FLT.Mathlib.RingTheory.DiscreteValuationRing.Basic`) — are assembled here into

* `exists_unramified_extension_of_residueField` : the lifting theorem.

The quadratic case of the lifting theorem is the local-field input to
`WeierstrassCurve.exists_quadraticTwist_hasSplitMultiplicativeReduction`.
-/

@[expose] public section

universe u

open IsLocalRing Polynomial

variable {R : Type u} [CommRing R] [IsDomain R] [IsDiscreteValuationRing R]
variable {K : Type u} [Field K] [Algebra R K] [IsFractionRing R K]

open AdjoinRoot in
/-- **Unramified lifting, arbitrary degree.** A finite separable extension `k'` of the residue
field of a discrete valuation ring `R` lifts to an unramified extension `L` of its fraction field
`K`: there is a finite separable extension `L/K` with `[L : K] = [k' : k]` and a discrete
valuation ring `S` with fraction field `L`, containing `R` via a local homomorphism, whose residue
field is `k'`. (The residue degree being `[L : K]` forces ramification index `1`.) -/
theorem exists_unramified_extension_of_residueField
    (k' : Type u) [Field k'] [Algebra (ResidueField R) k']
    [FiniteDimensional (ResidueField R) k'] [Algebra.IsSeparable (ResidueField R) k'] :
    ∃ (L : Type u) (_ : Field L) (_ : Algebra K L) (_ : FiniteDimensional K L)
      (_ : Algebra.IsSeparable K L) (_ : Algebra R L) (_ : IsScalarTower R K L) (S : Type u)
      (_ : CommRing S) (_ : IsDomain S) (_ : IsDiscreteValuationRing S) (_ : Algebra R S)
      (_ : Module.Finite R S) (_ : Algebra S L) (_ : IsScalarTower R S L) (_ : IsFractionRing S L)
      (_ : IsLocalHom (algebraMap R S)),
      Module.finrank K L = Module.finrank (ResidueField R) k'
        ∧ Nonempty (ResidueField S ≃ₐ[ResidueField R] k') := by
  -- `k' = k[X]/(pbar)` for a monic separable irreducible `pbar` of degree `[k' : k]`.
  obtain ⟨pbar, hpbar_monic, hpbar_sep, hpbar_irr, hpbar_deg, ⟨hk'_equiv⟩⟩ :=
    Field.exists_monic_irreducible_adjoinRoot_algEquiv (ResidueField R) k'
  have hpbar_pos : 0 < pbar.natDegree := hpbar_deg ▸ Module.finrank_pos
  -- Lift `pbar` to a monic `P` over `R`; irreducible over `R`, hence over `K`.
  obtain ⟨P, hP_monic, hP_map, hP_deg⟩ := IsLocalRing.exists_monic_map_residue_eq hpbar_monic
  have hP_redirr : Irreducible (P.map (residue R)) := by rw [hP_map]; exact hpbar_irr
  have hP_irr : Irreducible P :=
    hP_monic.irreducible_of_irreducible_map (residue R) P hP_redirr
  have hPdeg : P.degree ≠ 0 := by
    rw [Polynomial.degree_eq_natDegree hP_monic.ne_zero, hP_deg]
    exact_mod_cast hpbar_pos.ne'
  set pK := P.map (algebraMap R K) with hpK
  have : Fact (Irreducible pK) :=
    ⟨(hP_monic.irreducible_iff_irreducible_map_fraction_map (K := K)).mp hP_irr⟩
  set L := AdjoinRoot pK
  set S := AdjoinRoot P
  have hSdom : IsDomain S := isDomain_of_prime
    (UniqueFactorizationMonoid.irreducible_iff_prime.mp hP_irr)
  -- `S = R[X]/(P)` is a discrete valuation ring, unramified over `R`.
  obtain ⟨hmS_max, hSdvr, hSlocalhom⟩ :=
    isDiscreteValuationRing_of_irreducible_map_residue hP_monic hPdeg hP_redirr
  have hmaxS : maximalIdeal S = (maximalIdeal R).map (algebraMap R S) :=
    (IsLocalRing.eq_maximalIdeal hmS_max).symm
  -- `L = K[X]/(pK)` has degree `[k' : k]` over `K`.
  have hLrank : Module.finrank K L = Module.finrank (ResidueField R) k' :=
    finrank_eq_natDegree.trans
      (by rw [hpK, hP_monic.natDegree_map, hP_deg, hpbar_deg])
  -- The `R`-algebra map `S → L` and the tower `R → S → L`.
  let algSL : Algebra S L := (map (algebraMap R K) P pK hpK.dvd).toAlgebra
  have halg : algebraMap S L = map (algebraMap R K) P pK hpK.dvd :=
    RingHom.algebraMap_toAlgebra _
  have htower : IsScalarTower R S L := IsScalarTower.of_algebraMap_eq fun r ↦ by
    rw [halg, algebraMap_eq (f := P), map_of, algebraMap_eq']
    rfl
  -- Residue field: `S/𝔪_S ≅ k[X]/(pbar) ≅ k'`, as `R`-algebra equivalences, then lift the base
  -- ring to `ResidueField R` (`extendScalarsOfSurjective`).
  let _ : Algebra R k' := ((algebraMap (ResidueField R) k').comp (residue R)).toAlgebra
  have : IsScalarTower R (ResidueField R) k' := .of_algebraMap_eq fun _ ↦ rfl
  have e : ResidueField S ≃ₐ[R] k' :=
    (residueFieldEquiv hmaxS).trans
      ((Ideal.quotientEquivAlgOfEq R (congrArg (fun q ↦ Ideal.span {q}) hP_map)).trans
        (hk'_equiv.restrictScalars R))
  exact ⟨L, inferInstance, inferInstance,
    (powerBasis (Fact.out (p := Irreducible pK)).ne_zero).finite,
    isSeparable_of_separable
      (hP_monic.separable_map_algebraMap_of_separable_map_residue
        (by rw [hP_map]; exact hpbar_sep)),
    inferInstance, inferInstance, S, inferInstance, hSdom, hSdvr, inferInstance,
    hP_monic.finite_adjoinRoot, algSL, htower,
    isFractionRing_map hPdeg hmaxS
      (by rw [halg]; exact map_comp_mk (algebraMap R K) hpK),
    hSlocalhom, hLrank, ⟨e.extendScalarsOfSurjective residue_surjective⟩⟩

end
