/-
Copyright (c) 2025 Jack McCarthy. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jack McCarthy
-/
module

public import Mathlib.Analysis.Normed.Field.Lemmas
public import Mathlib.LinearAlgebra.FreeModule.PID
public import Mathlib.RingTheory.DedekindDomain.Dvr
public import FLT.Slop.BrauerInduction.Background.ClassFun.Character.Basis
public import FLT.Slop.BrauerInduction.Background.ClassFun.Integral
public import FLT.Slop.BrauerInduction.Background.RingTheory.RootsOfUnity

@[expose] public section

/-!

# Bernstein's coefficient ring `Λ`

This file introduces the coefficient ring `Λ` used in Bernstein's proof of
Brauer induction. For a group `G` and coefficient ring `k`, `Λ` is the subring
of `k` generated by the `|G|`-th roots of unity.

The file also defines `ClassFun.HasLambdaCoords`, expressing that a class
function has coordinates in `Λ` with respect to an irreducible-character basis.

The main results are:

* `ClassFun.Lambda.moduleFinite`: `Λ` is a finitely generated `ℤ`-module.
* `ClassFun.Lambda.moduleFree`: `Λ` is a free `ℤ`-module in characteristic zero.
* `ClassFun.Lambda.one_is_primitive`: `1 : Λ` is primitive as an element of the
  `ℤ`-module `Λ`.
* `ClassFun.Lambda.char_coeffs`: the coordinates of a representation character
  in an irreducible-character basis lie in `Λ`.
* `ClassFun.HasLambdaCoords.character`: representation characters have
  `Λ`-coordinates in an irreducible-character basis.

Pure roots-of-unity facts used here are kept in
`BrauerInduction.Background.RingTheory.RootsOfUnity`.
Pointwise integer-valued class functions are developed separately in
`BrauerInduction.Background.ClassFun.Integral`.
-/

universe u v

namespace ClassFun

section Lambda

variable {G : Type v} [Group G]

/--
Bernstein's coefficient ring `Λ`: the subring of `k` generated by the
`|G|`-th roots of unity.
-/
def Lambda (k : Type u) (G : Type v) [Group G] [CommRing k] : Subring k :=
  Subring.closure (Set.range
    (fun (x : rootsOfUnity (Nat.card G) k) => (x.val : k)))

namespace Lambda

/--
Scalar multiplication by an element of `Λ` acts pointwise through its coercion
to `k`.
-/
@[simp]
lemma smul_apply {k : Type u} [CommRing k]
    (a : ClassFun.Lambda k G) (f : ClassFun k G) (x : G) :
    (a • f) x = (a : k) * f x := by
  rfl

-- Keep this instance local: globally registering this module structure tends to
-- create fragile diamonds with the existing `k`-module structure.
local instance {k : Type u} [CommRing k] (H : Subgroup G) :
    Module (Lambda k G) (ClassFun k H) :=
  Module.compHom (ClassFun k H) (Lambda k G).subtype

/--
The cyclotomic coefficient ring `Λ` is a finitely generated `ℤ`-module.
-/
noncomputable instance moduleFinite
    {k : Type u} [Field k]
    [NeZero (Nat.card G)] :
    Module.Finite ℤ (Lambda k G) := by
  let s : Set k :=
    Set.range (fun (ζ : rootsOfUnity (Nat.card G) k) => (ζ.val : k))
  letI : Fintype (rootsOfUnity (Nat.card G) k) :=
    Fintype.ofFinite _
  have h_fin : s.Finite := Set.finite_range _
  have h_int : ∀ x ∈ s, IsIntegral ℤ x := by
    rintro x ⟨ζ, rfl⟩
    exact rootsOfUnity.isIntegral_of_ne_zero
      k (Nat.card G) (NeZero.ne (Nat.card G)) ζ
  let A : Subalgebra ℤ k := Algebra.adjoin ℤ s
  haveI : Module.Finite ℤ A :=
    Algebra.finite_adjoin_of_finite_of_isIntegral h_fin h_int
  haveI : IsNoetherian ℤ A := inferInstance
  have h_le : ∀ x ∈ Lambda k G, x ∈ A := by
    intro x hx
    unfold Lambda at hx
    have h_subset : s ⊆ A.toSubring := Algebra.subset_adjoin
    exact Subring.closure_le.mpr h_subset hx
  let f : Lambda k G →ₗ[ℤ] A :=
    { toFun := fun x => ⟨x.1, h_le x.1 x.2⟩
      map_add' := fun x y => by ext; rfl
      map_smul' := fun c x => by ext; rfl }
  have h_inj : Function.Injective f := by
    intro x y h
    ext
    exact congrArg (fun a : A => a.val) h
  exact Module.Finite.of_injective f h_inj

/--
The cyclotomic coefficient ring `Λ` is a free `ℤ`-module.

This follows from finite generation and torsion-freeness over the PID `ℤ`.
-/
noncomputable instance moduleFree
    (k : Type u) [Field k] [CharZero k]
    (G : Type v) [Group G]
    [Module.Finite ℤ (Lambda k G)] : Module.Free ℤ (Lambda k G) := by
  haveI : NoZeroSMulDivisors ℤ (Lambda k G) := by
    constructor
    intro a x h_smul
    have h_field :
      (a : k) * (x : k) = 0 := by
      calc (a : k) * (x : k) = ↑(a • x) := by
            simp only [zsmul_eq_mul, Subring.coe_mul, SubringClass.coe_intCast]
        _ = (0 : Lambda k G) := by rw [h_smul]
        _ = 0 := rfl
    cases mul_eq_zero.mp h_field with
    | inl ha_zero =>
        left
        exact_mod_cast ha_zero
    | inr hx_zero =>
        right
        ext
        exact hx_zero
  obtain ⟨_, b⟩ := Module.basisOfFiniteTypeTorsionFree' (R := ℤ) (M := Lambda k G)
  exact Module.Free.of_basis b

/--
The element `1 : Λ` is primitive as a `ℤ`-module element: if `m • x = 1`,
then `m` is a unit of `ℤ`.
-/
lemma one_is_primitive
    {k : Type u} [Field k] [CharZero k] [Finite G]
    (m : ℤ) (x : Lambda k G) (h : m • x = 1) :
    IsUnit m := by
  haveI: NeZero (Nat.card G) := ⟨One.natCard_ne_zero_of_finite G⟩
  have h_field : (m : k) * (x : k) = 1 := by
    have h_coe := congrArg (fun y : Lambda k G => (y : k)) h
    simp only [Subring.coe_one, zsmul_eq_mul] at h_coe
    exact h_coe
  have hx_int : IsIntegral ℤ (x : k) := by
    have H_le : Lambda k G ≤ (integralClosure ℤ k).toSubring := by
      rw [Lambda, Subring.closure_le]
      rintro _ ⟨u, rfl⟩
      exact rootsOfUnity.isIntegral k G u
    exact H_le x.property
  have hm_neq_zero : (m : k) ≠ 0 := by
    intro hz
    rw [hz, zero_mul] at h_field
    exact zero_ne_one h_field
  have hx_eq : (x : k) = (m : k)⁻¹ := by
    apply eq_inv_of_mul_eq_one_left
    simpa [mul_comm] using h_field
  rw [hx_eq] at hx_int
  have h_rat : (m : k)⁻¹ = algebraMap ℚ k ((m : ℚ)⁻¹) := by
    simp only [map_inv₀, map_intCast]
  rw [h_rat] at hx_int
  have h_int_Q : IsIntegral ℤ ((m : ℚ)⁻¹) :=
    (isIntegral_algebraMap_iff (algebraMap ℚ k).injective).mp hx_int
  have h_in_Z : ∃ z : ℤ, algebraMap ℤ ℚ z = (m : ℚ)⁻¹ :=
    IsIntegrallyClosed.isIntegral_iff.mp h_int_Q
  obtain ⟨z, hz⟩ := h_in_Z
  have hm_Q_neq_zero : (m : ℚ) ≠ 0 := by
    intro hz_Q
    have : (m : k) = 0 := by exact_mod_cast hz_Q
    exact hm_neq_zero this
  have h_zm_Q : (z : ℚ) * (m : ℚ) = 1 := by
    calc
      (z : ℚ) * (m : ℚ)
          = (m : ℚ)⁻¹ * (m : ℚ) := by
              simp only [mul_eq_mul_right_iff, hm_Q_neq_zero]
              rw [← hz]
              simp only [algebraMap_int_eq, eq_intCast, or_false]
      _ = 1 := inv_mul_cancel₀ hm_Q_neq_zero
  have h_zm_Z : z * m = 1 := by
    exact_mod_cast h_zm_Q
  rw [mul_comm] at h_zm_Z
  exact IsUnit.of_mul_eq_one z h_zm_Z

lemma rootsOfUnity_orderOf_mem_Lambda
    {k : Type u} [CommRing k] [Finite G]
    (a : G) (ζ : rootsOfUnity (orderOf a) k) :
    (((ζ : kˣ) : k)) ∈ Lambda k G := by
  have hdiv : orderOf a ∣ Nat.card G := by
    simpa using orderOf_dvd_natCard a
  rcases hdiv with ⟨m, hm⟩
  let η : rootsOfUnity (Nat.card G) k :=
    ⟨(ζ : kˣ), by
      calc
        ((ζ : kˣ) ^ Nat.card G)
            = ((ζ : kˣ) ^ orderOf a) ^ m := by
                rw [hm, pow_mul]
        _ = 1 := by
                rw [ζ.property, one_pow]⟩
  change (((ζ : kˣ) : k)) ∈
    Subring.closure (Set.range (fun x : rootsOfUnity (Nat.card G) k => ((x.val : kˣ) : k)))
  exact Subring.subset_closure ⟨η, rfl⟩

/--
The value of a linear character of a subgroup of `G` lies in Bernstein's
coefficient ring `Λ` formed using the ambient group `G`.
-/
lemma linearChar_apply_mem_Lambda
    {k : Type u} [CommRing k] [Finite G]
    (χ : G →* kˣ) (g : G) :
    ((χ g : kˣ) : k) ∈ Lambda k G := by
  letI : Fintype G := Fintype.ofFinite G
  have hg : g ^ Fintype.card G = 1 := by exact pow_card_eq_one
  have hχ_card : χ g ^ Fintype.card G = 1 := by
    calc
      χ g ^ Fintype.card G = χ (g ^ Fintype.card G) := by
        exact (map_pow χ g (Fintype.card G)).symm
      _ = χ 1 := by
        exact congrArg χ hg
      _ = 1 := by
        exact map_one χ
  have hχ : χ g ^ Nat.card G = 1 := by
    simpa [Nat.card_eq_fintype_card] using hχ_card
  let η : rootsOfUnity (Nat.card G) k :=
    ⟨χ g, hχ⟩
  change ((χ g : kˣ) : k) ∈
    Subring.closure
      (Set.range
        (fun x : rootsOfUnity (Nat.card G) k => ((x.val : kˣ) : k)))
  exact Subring.subset_closure ⟨η, rfl⟩

lemma linearChar_subgroup_apply_mem_Lambda
    {k : Type u} [CommRing k] [Finite G]
    {H : Subgroup G}
    (χ : H →* kˣ) (h : H) :
    ((χ h : kˣ) : k) ∈ Lambda k G := by
  letI : Fintype G := Fintype.ofFinite G
  have hG : (h : G) ^ Fintype.card G = 1 := by
    exact pow_card_eq_one
  have hH : h ^ Fintype.card G = 1 := by
    apply Subtype.ext
    simp
  have hχ_card : χ h ^ Fintype.card G = 1 := by
    calc
      χ h ^ Fintype.card G = χ (h ^ Fintype.card G) := by
        exact (map_pow χ h (Fintype.card G)).symm
      _ = χ 1 := by
        exact congrArg χ hH
      _ = 1 := by
        exact map_one χ
  have hχ : χ h ^ Nat.card G = 1 := by
    simpa [Nat.card_eq_fintype_card] using hχ_card
  let η : rootsOfUnity (Nat.card G) k :=
    ⟨χ h, hχ⟩
  change ((χ h : kˣ) : k) ∈
    Subring.closure
      (Set.range
        (fun x : rootsOfUnity (Nat.card G) k => ((x.val : kˣ) : k)))
  exact Subring.subset_closure ⟨η, rfl⟩

end Lambda
end Lambda

section coeffs

variable {k : Type u} [Field k]
variable {G : Type v} [Group G]

/--
The coordinates of a character in an irreducible-character basis lie in `Λ`.
-/
lemma Lambda.char_coeffs
    {k : Type u} [Field k] [CharZero k]
    {G : Type u} [Group G] [Finite G]
    (B : ClassFun.IrrepCharBasis k G)
    (U : FDRep k G) (i : B.ι) :
    B.b.repr (ClassFun.character U) i ∈ ClassFun.Lambda k G := by
  obtain ⟨m, hm⟩ := ClassFun.char_coeffs_int B U i
  rw [hm]
  have h_smul : (m : k) = m • (1 : k) := by
    exact (zsmul_one m).symm
  rw [h_smul]
  exact Subring.zsmul_mem (ClassFun.Lambda k G) (Subring.one_mem _) m

/--
A class function has `Λ`-coordinates with respect to an irreducible-character
basis if every coordinate in that basis lies in `Λ`.
-/
def HasLambdaCoords
    (B : ClassFun.IrrepCharBasis k G) (f : ClassFun k G) : Prop :=
  ∀ i : B.ι, B.b.repr f i ∈ ClassFun.Lambda k G

namespace HasLambdaCoords

/-- The zero class function has `Λ`-coordinates. -/
lemma zero
    (B : ClassFun.IrrepCharBasis k G) :
    HasLambdaCoords B 0 := by
  intro i
  simp

/-- Class functions with `Λ`-coordinates are closed under addition. -/
lemma add
    (B : ClassFun.IrrepCharBasis k G)
    {f g : ClassFun k G}
    (hf : HasLambdaCoords B f)
    (hg : HasLambdaCoords B g) :
    HasLambdaCoords B (f + g) := by
  intro i
  simp only [HasLambdaCoords, map_add, Finsupp.coe_add, Pi.add_apply] at *
  exact add_mem (hf i) (hg i)

/-- Characters have `Λ`-coordinates in an irreducible-character basis. -/
lemma character [CharZero k]
    {G : Type u} [Group G] [Finite G]
    (B : ClassFun.IrrepCharBasis k G)
    (U : FDRep k G) :
    HasLambdaCoords B (ClassFun.character U) := by
  intro i
  exact Lambda.char_coeffs B U i

/--
Class functions with `Λ`-coordinates are closed under integer scalar
multiplication.
-/
lemma zsmul
    (B : ClassFun.IrrepCharBasis k G)
    (z : ℤ) {f : ClassFun k G}
    (hf : HasLambdaCoords B f) :
    HasLambdaCoords B (z • f) := by
  intro i
  have h_zsmul_f :
      z • f = (z : k) • f :=
    Eq.symm (Int.cast_smul_eq_zsmul k z f)
  rw [h_zsmul_f, LinearEquiv.map_smul]
  change (z : k) * (B.b.repr f i) ∈ ClassFun.Lambda k G
  have h_mul_to_zsmul :
      (z : k) * (B.b.repr f i) =
        z • (B.b.repr f i) := by
    exact Eq.symm (zsmul_eq_mul (B.b.repr f i) z)
  rw [h_mul_to_zsmul]
  exact Subring.zsmul_mem (ClassFun.Lambda k G) (hf i) z

/--
Class functions with `Λ`-coordinates are closed under scalar multiplication
by elements of `Λ`.
-/
lemma smul
    (B : ClassFun.IrrepCharBasis k G)
    {a : k} (ha : a ∈ ClassFun.Lambda k G)
    {f : ClassFun k G}
    (hf : HasLambdaCoords B f) :
    HasLambdaCoords B (a • f) := by
  intro i
  rw [LinearEquiv.map_smul]
  change a * (B.b.repr f i) ∈ ClassFun.Lambda k G
  exact Subring.mul_mem _ ha (hf i)

end HasLambdaCoords
end coeffs
end ClassFun
