/-
Copyright (c) 2025 Jack McCarthy. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jack McCarthy
-/
module

public import FLT.Slop.BrauerInduction.CharacterSystem
public import Mathlib.RingTheory.RootsOfUnity.AlgebraicallyClosed
public import FLT.Slop.BrauerInduction.Background.LinearChar.Basic
public import FLT.Slop.BrauerInduction.Background.ClassFun.Zlocal
public import FLT.Slop.BrauerInduction.Background.RingTheory.RootsOfUnity
public import FLT.Slop.BrauerInduction.PElementaryGroup

/-!
# Bernstein Step 8: the elementary subgroup and the function `f_a`

For a fixed prime `p` and a `p`-regular element `a`, this file constructs
Bernstein's elementary subgroup `E(a)`, the class function `φ_a` on `E(a)`,
and the induced class function `f_a = Ind_{E(a)}^G φ_a`.

The file also proves Bernstein's character-sum formula for `φ_a`, the
membership statement `φ_a ∈ Q(E(a))`, and the support and evaluation formulas
for `f_a` needed in the local part of the proof.
-/

@[expose] public section

namespace Slop
open Slop

universe u v

open BrauerInduction

namespace BrauerInduction

section ElementarySubgroup

/-!
## The elementary subgroup `E(a)`

This section constructs Bernstein's subgroup `E(a) = Cyc a ⊔ P_of_Z p a`,
proves that it is `p`-elementary for `p`-regular `a`, and defines the
projection `E(a) → Cyc a` coming from the product decomposition.
-/

variable (p : ℕ)
variable {G : Type v} [Group G]

/--
The elementary subgroup associated to an element `a`.

It is the product of the cyclic subgroup generated by `a` and the chosen Sylow
`p`-subgroup of the centralizer of `a`.
-/
noncomputable def E_subgroup (a : G) : Subgroup G :=
  PElementary.Cyc a ⊔ PElementary.P_of_Z p a

/--
If `a` is `p`-regular, then the subgroup `E(a)` is `p`-elementary.
-/
lemma E_isPElementary
    {a : G} (ha : IsPRegular p a) :
    IsPElementary p (E_subgroup p a) :=
     ⟨PElementary.associatedSubgroup ha⟩

/-- Bernstein Step 8: E is a subgroup of the centralizer of a. -/
lemma E_le_centralizer (a : G) :
    E_subgroup p a ≤ Subgroup.centralizer {a} := by
  rw [E_subgroup, sup_le_iff]
  constructor
  · exact Subgroup.zpowers_le_centralizer a
  · exact PElementary.P_of_Z_le_Z a

/-- A helper to apply the centralizer property to elements of E. -/
lemma E_commutes_with_a (a : G)
    (y : E_subgroup p a) :
    (y : G) * a * (y : G)⁻¹ = a := by
  have hy : (y : G) ∈ Subgroup.centralizer {a} := E_le_centralizer p a y.property
  have h_comm : (y : G) * a = a * (y : G) := by exact Eq.symm (SemiconjBy.eq (hy a rfl))
  calc (y : G) * a * (y : G)⁻¹
    _ = a * (y : G) * (y : G)⁻¹ := by rw [h_comm]
    _ = a := by rw [mul_inv_cancel_right]

open PElementary in
/-- The element `a` lies in Bernstein's elementary subgroup `E(a)`. -/
lemma self_mem_E_subgroup (a : G) :
    a ∈ E_subgroup p a := by
  refine (le_sup_left : Cyc a ≤ E_subgroup p a) ?_
  exact Subgroup.mem_zpowers a

open PElementary in
/-- The element `a⁻¹` lies in Bernstein's elementary subgroup `E(a)`. -/
lemma inv_mem_E_subgroup (a : G) :
    a⁻¹ ∈ E_subgroup p a :=
  (E_subgroup p a).inv_mem (self_mem_E_subgroup p a)

/--
The cyclic factor of the associated `p`-elementary subgroup, identified with the
ambient cyclic subgroup `Cyc a`.

After the group-level refactor of `PElementary`, the cyclic factor of
`associatedSubgroup ha` is a subgroup of the group `E(a)`, not literally the
ambient subgroup `Cyc a`.  This equivalence is the canonical identification.
-/
noncomputable def E_Cyc_equiv [Fact p.Prime]
    (a : G) (ha : IsPRegular p a) :
    (PElementary.associatedSubgroup (p := p) ha).C ≃*
      PElementary.Cyc a := by
  let H : Subgroup G := E_subgroup p a
  have hC_le : PElementary.Cyc a ≤ H := by
    intro x hx
    exact Subgroup.mem_sup_left hx
  exact Subgroup.subgroupOfEquivOfLe hC_le

/--
The projection from `E(a) = Cyc a ⋅ P_Z(a)` to its cyclic factor.

This is obtained from the multiplicative equivalence
`Cyc a × P_Z(a) ≃* E(a)`, followed by the canonical identification of the
internal cyclic factor of `E(a)` with the ambient subgroup `Cyc a`.
-/
noncomputable def E_to_Cyc [Fact p.Prime]
    (a : G) (ha : IsPRegular p a) :
    E_subgroup p a →* PElementary.Cyc a := by
  let H : Subgroup G :=
    PElementary.Cyc a ⊔ PElementary.P_of_Z p a
  -- Make the domain of the hom exactly the domain expected by `associatedSubgroup`.
  change H →* PElementary.Cyc a
  let eH : PElementary p H :=
    PElementary.associatedSubgroup (p := p) ha
  let prodEquiv : H ≃* eH.C × eH.P :=
    (PElementary.mulEquivProd eH).symm
  exact
    { toFun := fun x =>
        E_Cyc_equiv (p := p) a ha ((prodEquiv x).1)

      map_one' := by
        have hfst : (prodEquiv 1).1 = 1 := by
          simp only [map_one, Prod.fst_one]
        rw [hfst]
        exact map_one (E_Cyc_equiv (p := p) a ha)

      map_mul' := by
        intro x y
        have hfst :
            (prodEquiv (x * y)).1 = (prodEquiv x).1 * (prodEquiv y).1 := by
          simp only [map_mul, Prod.fst_mul]
        rw [hfst]
        exact
          map_mul
            (E_Cyc_equiv (p := p) a ha)
            (prodEquiv x).1
            (prodEquiv y).1 }

@[simp]
lemma E_to_Cyc_apply [Fact p.Prime]
    {a : G} (ha : IsPRegular p a)
    (x : E_subgroup p a) :
    E_to_Cyc p a ha x =
      E_Cyc_equiv (p := p) a ha
        (((PElementary.mulEquivProd
          (PElementary.associatedSubgroup (p := p) ha)).symm x).1) := by
  rfl

/--
The projection `E_to_Cyc` has the same ambient value as the internal cyclic
component of the product decomposition of `E(a)`.
-/
@[simp]
lemma E_to_Cyc_apply_coe [Fact p.Prime]
    {a : G} (ha : IsPRegular p a)
    (x : E_subgroup p a) :
    ((E_to_Cyc p a ha x : PElementary.Cyc a) : G) =
      (((((PElementary.mulEquivProd
        (PElementary.associatedSubgroup (p := p) ha)).symm x).1 :
          (PElementary.associatedSubgroup (p := p) ha).C) :
          (PElementary.Cyc a ⊔ PElementary.P_of_Z p a : Subgroup G)) : G) := by
  rfl

/--
The `p`-group factor of the associated `p`-elementary subgroup, identified with
the ambient subgroup `P_of_Z p a`.
-/
noncomputable def E_P_equiv [Fact p.Prime]
    (a : G) (ha : IsPRegular p a) :
    (PElementary.associatedSubgroup (p := p) ha).P ≃*
      PElementary.P_of_Z p a := by
  let H : Subgroup G := E_subgroup p a
  have hP_le : PElementary.P_of_Z p a ≤ H := by
    intro x hx
    exact Subgroup.mem_sup_right hx
  exact Subgroup.subgroupOfEquivOfLe hP_le

open PElementary in
/--
The cardinality of `E(a)` is `orderOf a * |P_Z(a)|`.
-/
lemma E_card [Fact p.Prime] [Finite G]
    {a : G} (ha : IsPRegular p a) :
    Nat.card (E_subgroup p a) =
      orderOf a * Nat.card (P_of_Z p a) := by
  letI : Fintype G := Fintype.ofFinite G
  let H : Subgroup G := E_subgroup p a
  let eH := associatedSubgroup (p := p) ha
  let h_iso : eH.C × eH.P ≃* H := mulEquivProd eH
  have hH :
      Nat.card H = Nat.card (eH.C × eH.P) := by
    simpa using Nat.card_congr h_iso.toEquiv.symm
  have hC :
      Nat.card eH.C = orderOf a := by
    have hCcard :
        Nat.card eH.C = Nat.card (Cyc a) := by
      simpa using
        Nat.card_congr
          (E_Cyc_equiv (p := p) a ha).toEquiv
    rw [hCcard]
    simpa [Cyc] using Nat.card_zpowers a
  have hP :
      Nat.card eH.P = Nat.card (P_of_Z p a) := by
    simpa using
      Nat.card_congr
        (E_P_equiv (p := p) a ha).toEquiv
  calc
    Nat.card H
        = Nat.card (eH.C × eH.P) := hH
    _ = Nat.card eH.C * Nat.card eH.P := by
        simp
    _ = orderOf a * Nat.card (P_of_Z p a) := by
        rw [hC, hP]



end ElementarySubgroup

section CyclicCharacters

/-!
## Cyclic exponents and characters of `Cyc a`

This section chooses integer exponents for elements of the cyclic subgroup
`Cyc a` and defines the linear character `chiCyc ζ`, which sends the
distinguished generator `a` to the root of unity `ζ`.
-/

variable {k : Type u} [CommRing k]
variable {G : Type v} [Group G]

/-- Extracts the integer exponent n such that a^n = x -/
noncomputable def cycExp {a : G} (x : PElementary.Cyc a) : ℤ :=
  Classical.choose (Subgroup.mem_zpowers_iff.mp x.property)

/-- Guarantees that a ^ (cycExp x) evaluates exactly to x -/
lemma cycExp_spec {a : G} (x : PElementary.Cyc a) :
    a ^ cycExp x = (x : G) :=
  Classical.choose_spec (Subgroup.mem_zpowers_iff.mp x.property)

/--
The linear character of `Cyc a` sending `a` to a chosen `orderOf a`-th root of
unity.
-/
noncomputable def chiCyc
    {a : G} (ζ : rootsOfUnity (orderOf a) k) :
    (PElementary.Cyc a) →* kˣ where
  toFun := fun x => (ζ : kˣ) ^ cycExp x
  map_one' := by
    have hdif : a ^ cycExp 1 = 1 := cycExp_spec 1
    have hdvd : (orderOf a : ℤ) ∣ cycExp 1 := orderOf_dvd_iff_zpow_eq_one.mpr hdif
    obtain ⟨c, hc⟩ := hdvd
    have hζ : (ζ : kˣ) ^ (orderOf a : ℤ) = 1 := by
      have h_prop : (ζ : kˣ) ∈ rootsOfUnity (orderOf a) k := ζ.property
      rw [mem_rootsOfUnity] at h_prop
      exact h_prop
    calc (ζ : kˣ) ^ cycExp 1
       = (ζ : kˣ) ^ ((orderOf a : ℤ) * c) := by rw [hc]
     _ = ((ζ : kˣ) ^ (orderOf a : ℤ)) ^ c := by rw [zpow_mul]
     _ = (1 : kˣ) ^ c := by rw [hζ]
     _ = 1 := by exact one_zpow c
  map_mul' := by
    intro x y
    have hl : a ^ cycExp (x * y) = (x * y : G) := cycExp_spec (x * y)
    have hn : a ^ cycExp x = (x : G) := cycExp_spec x
    have hm : a ^ cycExp y = (y : G) := cycExp_spec y
    have hl_eq : a ^ cycExp (x * y) = a ^ (cycExp x + cycExp y) := by
      calc a ^ cycExp (x * y)
         = (x * y : G) := hl
       _ = (x : G) * (y : G) := rfl
       _ = a ^ cycExp x * a ^ cycExp y := by rw [← hn, ← hm]
       _ = a ^ (cycExp x + cycExp y) := by rw [zpow_add]
    have hdif : a ^ (cycExp (x * y) - (cycExp x + cycExp y)) = 1 := by
      calc a ^ (cycExp (x * y) - (cycExp x + cycExp y))
         = a ^ cycExp (x * y) * a ^ (-(cycExp x + cycExp y)) := by rw [sub_eq_add_neg, zpow_add]
       _ = a ^ (cycExp x + cycExp y) * (a ^ (cycExp x + cycExp y))⁻¹ := by rw [hl_eq, zpow_neg]
       _ = 1 := mul_inv_cancel _
    have hdvd : (orderOf a : ℤ) ∣ cycExp (x * y) - (cycExp x + cycExp y) :=
      orderOf_dvd_iff_zpow_eq_one.mpr hdif
    obtain ⟨c, hc⟩ := hdvd
    have hl_val : cycExp (x * y) = cycExp x + cycExp y + (orderOf a : ℤ) * c := by omega
    have hζ : (ζ : kˣ) ^ (orderOf a : ℤ) = 1 := by
      have h_prop : (ζ : kˣ) ∈ rootsOfUnity (orderOf a) k := ζ.property
      rw [mem_rootsOfUnity] at h_prop
      exact h_prop
    calc (ζ : kˣ) ^ cycExp (x * y)
     _ = (ζ : kˣ) ^ (cycExp x + cycExp y) * (ζ : kˣ) ^ ((orderOf a : ℤ) * c) := by
          rw [hl_val, zpow_add]
     _ = (ζ : kˣ) ^ (cycExp x + cycExp y) * (((ζ : kˣ) ^ (orderOf a : ℤ)) ^ c) := by rw [zpow_mul]
     _ = (ζ : kˣ) ^ (cycExp x + cycExp y) * (1 ^ c) := by rw [hζ]
     _ = (ζ : kˣ) ^ (cycExp x + cycExp y) * 1 := by
          simp only [mul_one, mul_eq_left]; exact one_zpow c
     _ = (ζ : kˣ) ^ (cycExp x + cycExp y) := by rw [mul_one]
     _ = (ζ : kˣ) ^ cycExp x * (ζ : kˣ) ^ cycExp y := by rw [zpow_add]

open PElementary in
/--
The cyclic character `χ_ζ` sends the distinguished generator `a` of `Cyc a`
to the root of unity `ζ`.
-/
lemma chiCyc_apply_generator
    {G : Type v} [Group G]
    {a : G}
    (ζ : rootsOfUnity (orderOf a) k) :
    (chiCyc (k := k) (a := a) ζ)
      (⟨a, Subgroup.mem_zpowers a⟩ : Cyc a) = ζ := by
  simp only [chiCyc, MonoidHom.coe_mk, OneHom.coe_mk]
  have h_cyc : a ^ cycExp (⟨a, Subgroup.mem_zpowers a⟩ : Cyc a) = a :=
    cycExp_spec (⟨a, Subgroup.mem_zpowers a⟩ : Cyc a)
  have h_an_one :
      a ^ (cycExp (⟨a, Subgroup.mem_zpowers a⟩ : Cyc a) - 1) = 1 := by
    rw [sub_eq_add_neg, zpow_add, h_cyc, zpow_neg_one, mul_inv_cancel]
  have h_dvd :
      (orderOf a : ℤ) ∣
        cycExp (⟨a, Subgroup.mem_zpowers a⟩ : Cyc a) - 1 :=
    orderOf_dvd_iff_zpow_eq_one.mpr h_an_one
  obtain ⟨m, hm⟩ := h_dvd
  have h_exp :
      cycExp (⟨a, Subgroup.mem_zpowers a⟩ : Cyc a) =
        1 + (orderOf a : ℤ) * m := by
    calc
      cycExp (⟨a, Subgroup.mem_zpowers a⟩ : Cyc a)
          = 1 + (cycExp (⟨a, Subgroup.mem_zpowers a⟩ : Cyc a) - 1) := by
              ring
      _ = 1 + (orderOf a : ℤ) * m := by rw [hm]
  calc
    (ζ : kˣ) ^ cycExp (⟨a, Subgroup.mem_zpowers a⟩ : Cyc a)
        = (ζ : kˣ) ^ (1 + (orderOf a : ℤ) * m) := by
            rw [h_exp]
    _ = (ζ : kˣ) ^ (1 : ℤ) *
          ((ζ : kˣ) ^ (orderOf a : ℤ)) ^ m := by
            rw [zpow_add, zpow_mul]
    _ = (ζ : kˣ) * 1 ^ m := by
            have hz : (ζ : kˣ) ^ orderOf a = 1 :=
              (mem_rootsOfUnity (orderOf a) (ζ : kˣ)).mp ζ.property
            have hz_zpow : (ζ : kˣ) ^ (orderOf a : ℤ) = 1 := by
              exact_mod_cast hz
            rw [zpow_one, hz_zpow]
    _ = (ζ : kˣ) := by
            simp only [one_zpow, mul_one]

open PElementary in
/--
The cyclic character `χ_ζ` sends the `n`th power of the distinguished generator
of `Cyc a` to `ζ ^ n`.
-/
lemma chiCyc_apply_generator_zpow
    {G : Type v} [Group G]
    {a : G}
    (ζ : rootsOfUnity (orderOf a) k)
    (n : ℤ) :
    (chiCyc (k := k) (a := a) ζ)
      ((⟨a, Subgroup.mem_zpowers a⟩ : Cyc a) ^ n) = ζ ^ n := by
  rw [map_zpow, chiCyc_apply_generator (k := k) (a := a) ζ]

lemma chiCyc_apply_mem_Lambda [Finite G]
    {a : G} (ζ : rootsOfUnity (orderOf a) k)
    (y : PElementary.Cyc a) :
    (((chiCyc (k := k) (a := a) ζ) y : kˣ) : k) ∈ ClassFun.Lambda k G := by
  exact ClassFun.Lambda.linearChar_subgroup_apply_mem_Lambda
    (k := k)
    (H := PElementary.Cyc a)
    (chiCyc (k := k) (a := a) ζ)
    y

end CyclicCharacters

section CharactersOnE

/-!
## Characters and one-dimensional representations of `E(a)`

This section extends linear characters of `Cyc a` to `E(a)` using the
projection `E_to_Cyc`.  The root-of-unity family is represented by
`psiEZeta`, and `VpsiEZeta` is the corresponding one-dimensional
representation.
-/

variable (p : ℕ) [Fact p.Prime]
variable {k : Type u} [CommRing k]
variable {G : Type v} [Group G]

/--
Extend a linear character of the cyclic factor `Cyc a` to `E(a)` by composing
with the projection `E(a) → Cyc a`.
-/
noncomputable def psiE
    (a : G) (ha : IsPRegular p a)
    (ψ : PElementary.Cyc a →* kˣ) :
    E_subgroup p a →* kˣ :=
  ψ.comp (E_to_Cyc p a ha)

/--
The one-dimensional representation of `E(a)` attached to a linear character of
the cyclic factor `Cyc a`.
-/
noncomputable def VpsiE
    (a : G) (ha : IsPRegular p a)
    (ψ : PElementary.Cyc a →* kˣ) :
    FDRep k (E_subgroup p a) :=
  FDRep.ofLinearChar (psiE (k := k) p a ha ψ)

/--
The linear character of `E(a)` obtained from the character of `Cyc a` sending
`a` to the root of unity `ζ`.
-/
noncomputable def psiEZeta
    {a : G} (ha : IsPRegular p a)
    (ζ : rootsOfUnity (orderOf a) k) :
    E_subgroup p a →* kˣ := psiE p a ha (chiCyc ζ)

/-- The corresponding one-dimensional representation of `E`. -/
noncomputable def VpsiEZeta
    {a : G} (ha : IsPRegular p a)
    (ζ : rootsOfUnity (orderOf a) k) :
    FDRep k (E_subgroup p a) :=
  FDRep.ofLinearChar (psiEZeta p ha ζ)

/--
Evaluation of `psiEZeta` is evaluation of the corresponding cyclic character on
the cyclic component of the element of `E(a)`.
-/
lemma psiE_apply_eq_chiCyc_cycPart
    {a : G} (ha : IsPRegular p a)
    (ζ : rootsOfUnity (orderOf a) k)
    (x : E_subgroup p a) :
    (psiEZeta p ha ζ) x
      =
    (chiCyc ζ) (E_to_Cyc p a ha x) := by
  simp [psiEZeta, psiE]

open PElementary in
/--
If the cyclic component of `y ∈ E(a)` is `a ^ n`, then `ψ_ζ(y) = ζ ^ n`.

This isolates the root-of-unity evaluation used in
`sum_psiEZeta_eq_zero_of_not_mem_P`.
-/
lemma psiEZeta_apply_eq_zpow_of_cycPart_eq_zpow
    {G : Type v} [Group G]
    {a : G} (ha : IsPRegular p a)
    (y : E_subgroup p a)
    {n : ℤ}
    (hn : ((E_to_Cyc p a ha y : PElementary.Cyc a) : G) = a ^ n)
    (ζ : rootsOfUnity (orderOf a) k) :
    (psiEZeta p ha ζ) y = ζ ^ n := by
  rw [psiE_apply_eq_chiCyc_cycPart p ha ζ y]
  have h_c_pow :
      E_to_Cyc p a ha y =
        (⟨a, Subgroup.mem_zpowers a⟩ : PElementary.Cyc a) ^ n := by
    ext
    exact hn
  rw [h_c_pow]
  exact chiCyc_apply_generator_zpow (k := k) (a := a) ζ n

lemma psiEZeta_apply_a_inv_mem_Lambda [Finite G]
    {a : G} (ha : IsPRegular p a)
    (ζ : rootsOfUnity (orderOf a) k)
    (haInvMem : a⁻¹ ∈ E_subgroup p a) :
    (((psiEZeta (k := k) p ha ζ)
        ⟨a⁻¹, haInvMem⟩ : kˣ) : k) ∈ ClassFun.Lambda k G := by
  have hψ :
      (psiEZeta (k := k) p ha ζ)
          ⟨a⁻¹, haInvMem⟩
        =
      (chiCyc (k := k) (a := a) ζ)
        (E_to_Cyc p a ha ⟨a⁻¹, haInvMem⟩) :=
    psiE_apply_eq_chiCyc_cycPart
      (k := k) p ha ζ ⟨a⁻¹, haInvMem⟩
  have hψk :
      (((psiEZeta (k := k) p ha ζ)
          ⟨a⁻¹, haInvMem⟩ : kˣ) : k)
        =
      (((chiCyc (k := k) (a := a) ζ)
        (E_to_Cyc p a ha ⟨a⁻¹, haInvMem⟩) : kˣ) : k) := Units.val_inj.mpr hψ
  rw [hψk]
  exact chiCyc_apply_mem_Lambda
    (k := k) ζ
    (E_to_Cyc p a ha ⟨a⁻¹, haInvMem⟩)


end CharactersOnE

end BrauerInduction

namespace ClassFun

open BrauerInduction

/--
Local finiteness instance for the roots of unity used in the Fourier expansion
of `phi_fun`.
-/
noncomputable local instance instFintypeRootsOfUnityOrderOf
    {k : Type u} [Field k]
    {G : Type v} [Group G] [Finite G]
    (a : G) :
    Fintype (rootsOfUnity (orderOf a) k) := by
  have hfin : IsOfFinOrder a := isOfFinOrder_of_finite a
  have hne0 : orderOf a ≠ 0 := (orderOf_ne_zero_iff).2 hfin
  haveI : NeZero (orderOf a) := ⟨hne0⟩
  exact Fintype.ofFinite _

section PhiExpansion

/-!
## The root-of-unity expansion of `φ_a`

This section defines `phiSum`, the character-sum expression for Bernstein's
function `φ_a`, and proves the elementary evaluations of the characters
`psiEZeta` used to identify this sum with the direct definition of `φ_a`.
-/

variable (p : ℕ) [Fact p.Prime]
variable {k : Type u} [Field k]
variable {G : Type v} [Group G]

/--
The character expansion of Bernstein's function `φ_a`.

This is the finite sum over all `orderOf a`-th roots of unity that later proves
`φ_a ∈ R_Λ(E(a))`.
-/
noncomputable def phiSum
    {a : G} (ha : IsPRegular p a) :
    ClassFun k (E_subgroup p a) := by
  have haMem : a ∈ E_subgroup p a := by
    refine (le_sup_left : PElementary.Cyc a ≤ E_subgroup p a) ?_
    refine (Subgroup.mem_zpowers_iff).2 ?_
    exact ⟨(1 : ℤ), by simp⟩
  have haInvMem : a⁻¹ ∈ E_subgroup p a :=
    (E_subgroup p a).inv_mem haMem
  have hfin : IsOfFinOrder a := IsPRegular.isOfFinOrder p ha
  have hne0 : orderOf a ≠ 0 := (orderOf_ne_zero_iff).2 hfin
  haveI : NeZero (orderOf a) := ⟨hne0⟩
  haveI : Fintype (rootsOfUnity (orderOf a) k) := Fintype.ofFinite _
  exact
    ∑ ζ : rootsOfUnity (orderOf a) k,
      (((psiEZeta p ha ζ) ⟨a⁻¹, haInvMem⟩ : kˣ) : k)
        • ClassFun.character (VpsiEZeta p ha ζ)


open PElementary in
/--
Pointwise expansion of `phiSum` as a sum of scalar multiples of linear
characters.
-/
lemma phiSum_apply_expand [Finite G]
    {a : G}
    (ha : IsPRegular p a)
    (x : E_subgroup p a) :
    phiSum (k := k) (p := p) ha x =
      ∑ ζ : rootsOfUnity (orderOf a) k,
        (((psiEZeta  (k := k) p ha ζ)
            ⟨a⁻¹, inv_mem_E_subgroup (p := p) a⟩ : kˣ) : k) *
          (((psiEZeta  (k := k) p ha ζ) x : kˣ) : k) := by
  simp only [phiSum, VpsiEZeta, FDRep.ofLinearChar,
    ClassFun.char_apply, ClassFun.sum_apply, ClassFun.smul_apply]
  apply Finset.sum_congr rfl
  intro ζ hζ
  congr 1
  simpa [FDRep.ofLinearChar] using
    FDRep.char_ofLinearChar (psiEZeta p ha ζ) x

open PElementary in
/--
In the pointwise expansion of `phiSum`, the two values of the linear character
combine to the value at the product `a⁻¹ * x`.
-/
lemma phiSum_apply_product_eq_combine [Finite G]
    {a : G} (ha : IsPRegular p a)
    (x : E_subgroup p a) :
    (∑ ζ : rootsOfUnity (orderOf a) k,
        (((psiEZeta p ha ζ)
            ⟨a⁻¹, inv_mem_E_subgroup p a⟩ : kˣ) : k) *
          (((psiEZeta p ha ζ) x : kˣ) : k))
      =
    ∑ ζ : rootsOfUnity (orderOf a) k,
        (((psiEZeta p ha ζ)
            (⟨a⁻¹, inv_mem_E_subgroup p a⟩ * x) : kˣ) : k) := by
  apply Finset.sum_congr rfl
  intro ζ _
  have hmul :
      (psiEZeta p ha ζ)
          (⟨a⁻¹, inv_mem_E_subgroup p a⟩ * x)
        =
      (psiEZeta p ha ζ) ⟨a⁻¹, inv_mem_E_subgroup p a⟩ *
        (psiEZeta p ha ζ) x := by
    exact MonoidHom.map_mul (psiEZeta p ha ζ) ⟨a⁻¹, inv_mem_E_subgroup p a⟩ x
  rw [hmul]
  simp only [Units.val_mul]

open PElementary in
lemma psiEZeta_apply_eq_one_of_mem_P [Finite G]
    {a : G} (ha : IsPRegular p a)
    (ζ : rootsOfUnity (orderOf a) k)
    (y : E_subgroup p a)
    (hyP : (y : G) ∈ P_of_Z p a) :
    psiEZeta p ha ζ y = 1 := by
  rw [psiE_apply_eq_chiCyc_cycPart p ha ζ y]
  let yG : G := (y : G)
  have hyH : yG ∈ Cyc a ⊔ P_of_Z p a := y.property
  let ySub : ↥(Cyc a ⊔ P_of_Z p a) := ⟨yG, hyH⟩
  have h_c_one_internal :
      ((mulEquivProd (associatedSubgroup ha)).symm ySub).1 = 1 := by
    let H_elem := associatedSubgroup ha
    let iso := mulEquivProd H_elem
    let pElem : H_elem.P := ⟨ySub, hyP⟩
    have h_iso_fwd : iso (1, pElem) = ySub := by
      ext
      exact one_mul yG
    have h_iso_symm := congr_arg iso.symm h_iso_fwd
    rw [MulEquiv.symm_apply_apply] at h_iso_symm
    exact congr_arg Prod.fst h_iso_symm.symm
  have h_c_one : E_to_Cyc p a ha y = 1 := by
    rw [E_to_Cyc_apply]
    exact (MulEquiv.map_eq_one_iff (E_Cyc_equiv p a ha)).mpr h_c_one_internal
  rw [h_c_one]
  exact MonoidHom.map_one (chiCyc ζ)

open PElementary in
open PElementary in
/--
The identification `E_Cyc_equiv` does not change the underlying element of `G`.

The cyclic factor of `associatedSubgroup ha` is internally a subgroup of
`E(a)`, while `E_Cyc_equiv` identifies it with the ambient cyclic subgroup
`Cyc a`. This lemma records that this identification is just the evident
inclusion at the level of elements of `G`.
-/
@[simp]
lemma E_Cyc_equiv_apply_coe
    {a : G} (ha : IsPRegular p a)
    (c : (associatedSubgroup (p := p) ha).C) :
    ((E_Cyc_equiv (p := p) a ha c : Cyc a) : G) =
      ((c : (Cyc a ⊔ P_of_Z p a : Subgroup G)) : G) := by
  rfl

open PElementary in
/--
If an element of `E(a)` is not in the `P`-part, then the sum of the
linear characters `ψ_ζ` over all roots of unity vanishes.

This is the first point in the construction where the coefficient field is
assumed algebraically closed: the proof uses the full set of `orderOf a`-th
roots of unity and the standard vanishing sum for a nontrivial power of them.
-/
lemma sum_psiEZeta_eq_zero_of_not_mem_P
    [CharZero k] [IsAlgClosed k] [Finite G]
    {a : G} (ha : IsPRegular p a)
    (y : E_subgroup p a)
    (hyP : (y : G) ∉ P_of_Z p a) :
    (∑ ζ : rootsOfUnity (orderOf a) k,
        (((psiEZeta p ha ζ) y : kˣ) : k)) = 0 := by
  let y_G : G := (y : G)
  have hy_H : y_G ∈ Cyc a ⊔ P_of_Z p a := y.property
  let y_sub : ↥(Cyc a ⊔ P_of_Z p a) := ⟨y_G, hy_H⟩
  let H_elem := associatedSubgroup ha
  let iso := mulEquivProd H_elem
  let c_sub := (iso.symm y).1
  let s_sub := (iso.symm y).2
  obtain ⟨n, hn_eq⟩ : ∃ n : ℤ, (c_sub : G) = a ^ n := by
    obtain ⟨n, hn⟩ := Subgroup.mem_zpowers_iff.mp c_sub.property
    exact ⟨n, hn.symm⟩
  have hn_toCyc : ((E_to_Cyc p a ha y : Cyc a) : G) = a ^ n := by
      have hcyc :
          ((E_to_Cyc p a ha y : Cyc a) : G) =
            (c_sub : G) := by
        simp only [E_to_Cyc_apply, E_Cyc_equiv_apply_coe, H_elem, c_sub, iso]
      exact hcyc.trans hn_eq
  obtain ⟨n, hn_eq⟩ : ∃ n : ℤ, (c_sub : G) = a ^ n := by
    obtain ⟨n, hn⟩ := Subgroup.mem_zpowers_iff.mp c_sub.property
    exact ⟨n, hn.symm⟩
  have h_ndiv : ¬ (orderOf a : ℤ) ∣ n := by
    intro h_div
    have h_an_one : a ^ n = 1 := orderOf_dvd_iff_zpow_eq_one.mp h_div
    have hc_one : (c_sub : G) = 1 := by rw [hn_eq, h_an_one]
    have h_prod : (c_sub : G) * (s_sub : G) = y_G := by
      have h_eval : (iso (c_sub, s_sub) : G) =
          (c_sub : G) * (s_sub : G) := rfl
      rw [← h_eval]
      exact congrArg Subtype.val (iso.apply_symm_apply y_sub)
    have hy_in_P : y_G ∈ P_of_Z p a := by
      have h_y_eq_u : y_G = (s_sub : G) := by
        calc
          y_G = (c_sub : G) * (s_sub : G) := h_prod.symm
          _ = 1 * (s_sub : G) := by rw [hc_one]
          _ = (s_sub : G) := one_mul _
      rw [h_y_eq_u]
      exact s_sub.property
    exact hyP hy_in_P
  have h_sum :
      (∑ ζ : rootsOfUnity (orderOf a) k,
          (((psiEZeta p ha ζ) y : kˣ) : k))
        =
      ∑ ζ : rootsOfUnity (orderOf a) k,
          (((ζ : kˣ) ^ n : kˣ) : k) := by
    apply Finset.sum_congr rfl
    intro ζ _
    have hn_toCyc : ((E_to_Cyc p a ha y : Cyc a) : G) = a ^ n := by
      simp only [E_to_Cyc_apply, E_Cyc_equiv_apply_coe]
      simpa [E_to_Cyc_apply, E_Cyc_equiv, c_sub] using hn_eq
    rw [psiEZeta_apply_eq_zpow_of_cycPart_eq_zpow
      (k := k) (p := p) ha y hn_toCyc ζ]
  rw [h_sum]
  have:  NeZero (orderOf a) := IsPRegular.neZero_orderOf p ha
  exact rootsOfUnity.sum_zpow_eq_zero_of_not_dvd (orderOf a) n h_ndiv

end PhiExpansion

section PhiFunction

/-!
## The function `φ_a` and membership in `Q(E(a))`

This section defines `phi_fun` directly, proves that it agrees with the
root-of-unity expansion `phiSum`, and packages the two membership statements
`phi_fun ∈ R_Lambda` and `phi_fun ∈ C_Z` as `phi_mem_Q`.
-/

variable (p : ℕ) [Fact p.Prime]
variable {k : Type u} [CommRing k]
variable {G : Type v} [Group G]

open Classical in
/--
Bernstein's function `φ_a` on `E(a)`.

It takes the value `orderOf a` on elements whose `p`-regular part is `a`, and
takes the value `0` elsewhere.
-/
noncomputable def phi_fun
    (k : Type u) [CommRing k] (a : G) :
  ClassFun k (E_subgroup p a) :=
  ClassFun.ofFun
    (fun x => if Group.pRegular p (x : G) = a then (orderOf a : k) else 0)
    (by
    intro x y hc
    obtain ⟨g, hg⟩ := hc
    have hy : y = g * x * g⁻¹ := by
      calc y = (y * g) * g⁻¹ := by exact (Units.eq_mul_inv_iff_mul_eq g).mpr rfl
           _ = (g * x) * g⁻¹ := by rw [hg]
           _ = g * x * g⁻¹ := by rw [mul_assoc]
    subst hy
    congr 1
    ext
    push_cast
    have h_conj : Group.pRegular p ((g : G) * (x : G) * (g : G)⁻¹) =
        (g : G) * Group.pRegular p (x : G) * (g : G)⁻¹ := by
      rw [Group.pRegular_conj]
    have h_iff :
      Group.pRegular p ((g : G) * (x : G) * (g : G)⁻¹) = a ↔ Group.pRegular p (x : G) = a := by
      constructor
      · intro h1
        have h2 : Group.pRegular p (x : G) = (g : G)⁻¹ * a * (g : G) := by
          calc Group.pRegular p (x : G)
            _ = (g : G)⁻¹ * ((g : G) * Group.pRegular p (x : G) * (g : G)⁻¹) * (g : G) := by group
            _ = (g : G)⁻¹ * a * (g : G) := by rw [← h_conj, h1]
        rw [h2]
        have h3 := E_commutes_with_a p a g⁻¹
        simp only [Subgroup.coe_inv, inv_inv] at h3
        exact h3
      · intro h1
        rw [h_conj, h1]
        exact E_commutes_with_a p a g
    exact h_iff.symm)

open Classical in
@[simp]
lemma phi_fun_apply [Finite G]
    {a : G} (x : E_subgroup p a) :
    phi_fun  p k a x =
      if Group.pRegular p (x : G) = a then (orderOf a : k) else 0 :=
  rfl

lemma phi_mem_C_Z (a : G) :
    phi_fun p k a ∈ C_Z k (E_subgroup p a) := by
  intro x
  by_cases h : Group.pRegular p (x : G) = a
  · refine ⟨(orderOf a : ℤ), ?_⟩
    simp [phi_fun, h]
  · refine ⟨0, ?_⟩
    simp [phi_fun, h]

open Classical PElementary in
/--
Bernstein's root-of-unity expansion of `φ_a`.

This identifies the direct definition `phi_fun` with the character sum `phiSum`.
-/
lemma phi_fun_eq_phiSum
    {k : Type u} [Field k] [CharZero k] [IsAlgClosed k]
    [Finite G]
    {a : G} (ha : IsPRegular p a) :
    phi_fun p k a = phiSum  (k := k) (p := p) ha := by
  ext x
  rw [phi_fun_apply (k := k) (p := p) x]
  rw [phiSum_apply_expand (k := k) (p := p) ha x]
  rw [phiSum_apply_product_eq_combine (k := k) (p := p) ha x]
  let aInvE : E_subgroup p a := ⟨a⁻¹, inv_mem_E_subgroup p a⟩
  haveI : NeZero (orderOf a) := IsPRegular.neZero_orderOf p ha
  letI : Fintype (rootsOfUnity (orderOf a) k) :=
    Fintype.ofFinite _
  by_cases h_reg : Group.pRegular p (x : G) = a
  · have h_in_P :
        ((aInvE * x : E_subgroup p a) : G) ∈ P_of_Z  p a := by
      have h_fiber := (PElementary.mem_associatedSubgroup_fiber ha x).mp h_reg
      obtain ⟨s, hs_P, h_x_eq⟩ := h_fiber
      have h_ax_eq_s : ((aInvE * x : E_subgroup p a) : G) = s := by
        push_cast
        rw [h_x_eq, inv_mul_cancel_left]
      rw [h_ax_eq_s]
      exact hs_P
    have h_psi_one :
        ∀ ζ : rootsOfUnity (orderOf a) k,
            psiEZeta p ha ζ (aInvE * x) = 1 := by
      intro ζ
      exact psiEZeta_apply_eq_one_of_mem_P
        (k := k) (p := p) ha ζ (aInvE * x) h_in_P
    have hcard :
        Fintype.card (rootsOfUnity (orderOf a) k) = orderOf a := by
      rw [← Nat.card_eq_fintype_card]
      exact HasEnoughRootsOfUnity.natCard_rootsOfUnity k (orderOf a)
    change
      (if Group.pRegular p (x : G) = a then (orderOf a : k) else 0)
        =
      ∑ ζ : rootsOfUnity (orderOf a) k, (((psiEZeta p ha ζ) (aInvE * x) : kˣ) : k)
    simp only [
      h_reg, ↓reduceIte, h_psi_one, Units.val_one,
      Finset.sum_const, Finset.card_univ, nsmul_eq_mul, mul_one
    ]
    exact_mod_cast hcard.symm
  · have h_not_in_P :
        ((aInvE * x : E_subgroup p a) : G) ∉ P_of_Z p a := by
      intro hyP
      apply h_reg
      have h_fiber := mem_associatedSubgroup_fiber ha x
      apply h_fiber.mpr
      refine ⟨((aInvE * x : E_subgroup p a) : G), hyP, ?_⟩
      change (x : G) = a * (a⁻¹ * (x : G))
      simp only [mul_inv_cancel_left]
    have hsum0 :
        (∑ ζ : rootsOfUnity (orderOf a) k,
          (((psiEZeta p ha ζ) (aInvE * x) : kˣ) : k)) = 0 :=
      sum_psiEZeta_eq_zero_of_not_mem_P
        (k := k) (p := p) ha (aInvE * x) h_not_in_P
    simp only [h_reg, ↓reduceIte]
    exact by
      simpa using hsum0.symm

/--
The character expansion `phiSum` lies in `R_Λ(E(a))`.

Concretely, `phiSum` is a `Λ`-linear combination of the characters `VpsiEZeta`,
viewed as characters of one-dimensional representations of `E(a)`.
-/
lemma phiSum_mem_R_Lambda
    {k : Type u} [Field k]
    {G : Type u} [Group G] [Finite G]
    {a : G} (ha : IsPRegular p a) :
    phiSum p ha ∈ R_Lambda k G (E_subgroup p a) := by
  dsimp [phiSum]
  have haMem : a ∈ E_subgroup p a := by
    refine (le_sup_left : PElementary.Cyc a ≤ E_subgroup p a) ?_
    refine (Subgroup.mem_zpowers_iff).2 ?_
    exact ⟨(1 : ℤ), by simp⟩
  have haInvMem : a⁻¹ ∈ E_subgroup p a :=
    (E_subgroup p a).inv_mem haMem
  change
    (Finset.univ.sum (fun ζ : rootsOfUnity (orderOf a) k =>
      (((psiEZeta p ha ζ) ⟨a⁻¹, haInvMem⟩ : kˣ) : k)
        • ClassFun.character (VpsiEZeta (k := k) p ha ζ)))
      ∈ R_Lambda k G (E_subgroup p a)
  refine Submodule.sum_mem _ ?_
  intro ζ hζ
  let c : Lambda k G :=
    ⟨(((psiEZeta (k := k) p ha ζ) ⟨a⁻¹, haInvMem⟩ : kˣ) : k),
      psiEZeta_apply_a_inv_mem_Lambda
      (k := k) p ha ζ haInvMem⟩
  change
    c • ClassFun.character (VpsiEZeta p ha ζ)
      ∈ R_Lambda k G (E_subgroup p a)
  exact Submodule.smul_mem _ c
    (R_Lambda.char_mem (k := k) (E_subgroup p a) (VpsiEZeta p ha ζ))

/-- Bernstein Step 8, Claim (i), `Λ`-character-span part. -/
lemma phi_mem_R_Lambda
    {k : Type u} [Field k] [IsAlgClosed k] [CharZero k]
    {G : Type u} [Group G] [Finite G]
    (a : G) (ha : IsPRegular p a) :
    phi_fun p k a ∈ R_Lambda k G (E_subgroup p a) := by
    have hEq : phi_fun p k a = phiSum (k := k) (p := p) ha := by
      exact phi_fun_eq_phiSum p ha
    simpa [hEq] using (phiSum_mem_R_Lambda p ha)

/-- Bernstein Step 8, Claim (i): `φ ∈ Q(E)`. -/
lemma phi_mem_Q
    {k : Type u} [Field k] [IsAlgClosed k] [CharZero k]
    {G : Type u} [Group G] [Finite G]
    (a : G) (ha : IsPRegular p a) :
    phi_fun p k a ∈ Q_sys k G (E_subgroup p a) := by
  exact ⟨
    phi_mem_R_Lambda p a ha,
    phi_mem_C_Z p a
  ⟩

end PhiFunction

section InducedFunction

/-!
## The induced class function `f_a` and its support

This section defines `f_a = Ind_{E(a)}^G φ_a` and proves the basic support
statement: `f_a x` vanishes when the `p`-regular part of `x` is not conjugate
to `a`.
-/

variable (p : ℕ)
variable {k : Type u} [Field k]
variable {G : Type v} [Group G] [Fact p.Prime]

/-- Bernstein Step 8: `f_a = Ind_E^G φ`. -/
noncomputable def f_a [Fintype G]
    (a : G) : ClassFun k G :=
  ClassFun.ind (k := k)  (E_subgroup p a)  (phi_fun p k a)

/-- Bernstein Step 8, Claim (ii), support part.

If the p-regular part of `x` is not conjugate to `a`, then the induced
function `f_a` vanishes at `x`.
-/
lemma f_a_apply_eq_zero_of_not_isConj [Fintype G]
    (a x : G)
    (hx : ¬ IsConj (Group.pRegular p x) a) :
    f_a (k := k) p a x = 0 := by
  unfold f_a
  rw [ClassFun.ind_apply]
  apply Finset.sum_eq_zero
  intro q hq
  by_cases hE : q.out⁻¹ * x * q.out ∈ E_subgroup p a
  · have hne :
        Group.pRegular p (q.out⁻¹ * x * q.out) ≠ a := by
      intro hpreg_eq
      apply hx
      have hpreg_conj :
          Group.pRegular p (q.out⁻¹ * x * q.out)
            =
          q.out⁻¹ * Group.pRegular p x * q.out := by
        simp only [Group.pRegular_conj']
      have hconj_eq :
          q.out⁻¹ * Group.pRegular p x * q.out = a := by
        rw [← hpreg_conj]
        exact hpreg_eq
      rw [isConj_iff]
      refine ⟨q.out⁻¹, ?_⟩
      rw [inv_inv]
      exact hconj_eq
    simp only [hE, ↓reduceDIte, phi_fun, ClassFun.ofFun_apply, hne, ↓reduceIte]
  · simp [hE]

/--
For a `p`-regular element `a`, the conjugate `x⁻¹ a x` contributes nontrivially
to `φ_a` exactly when `x` centralizes `a`.
-/
lemma conj_inv_mem_E_and_phi_nonzero_iff [Finite G]
    {a : G} (ha : IsPRegular p a) (x : G) :
    (x⁻¹ * a * x ∈ E_subgroup p a ∧
        Group.pRegular p (x⁻¹ * a * x) = a)
      ↔ x ∈ Subgroup.centralizer ({a} : Set G) := by
  constructor
  · rintro ⟨hxE, hreg⟩
    have hf : IsOfFinOrder a := isOfFinOrder_of_finite a
    have hpreg_conj :
        Group.pRegular p (x⁻¹ * a * x)
          =
        x⁻¹ * Group.pRegular p a * x := by
      simp only [Group.pRegular_conj']
    have hpreg_a :
        Group.pRegular p a = a :=
      Group.pRegular_eq_self_of_isPRegular p hf ha
    have hx_conj_a :
        x⁻¹ * a * x = a := by
      calc
        x⁻¹ * a * x
            = x⁻¹ * Group.pRegular p a * x := by rw [hpreg_a]
        _ = Group.pRegular p (x⁻¹ * a * x) := by rw [hpreg_conj]
        _ = a := hreg
    rw [Subgroup.mem_centralizer_iff]
    intro y hy
    rw [Set.mem_singleton_iff] at hy
    subst y
    · calc
        a * x
            = x * (x⁻¹ * a * x) := by group
        _ = x * a := by rw [hx_conj_a]
  · intro hxC
    have h_comm : x * a = a * x := by
      exact Eq.symm (SemiconjBy.eq (hxC a rfl))
    have h_eq : x⁻¹ * a * x = a := by
      calc
        x⁻¹ * a * x = x⁻¹ * (a * x) := by group
        _ = x⁻¹ * (x * a) := by rw [← h_comm]
        _ = a := by group
    refine ⟨?_, ?_⟩
    · rw [h_eq]
      apply Subgroup.mem_sup_left
      exact Subgroup.mem_zpowers a
    · rw [h_eq]
      exact Group.pRegular_eq_self_of_isPRegular p (isOfFinOrder_of_finite a) ha

end InducedFunction

section EvaluationAtA

/-!
## Evaluation of `f_a` at `a`

This section computes `f_a(a)`.  The result is expressed as Bernstein's index,
the index of the chosen Sylow `p`-subgroup in the centralizer of `a`, and is
shown to be prime to `p`.
-/

variable (p : ℕ) [Fact p.Prime]
variable {k : Type u} [Field k]
variable {G : Type v} [Group G]

/--
Closed formula for `f_a(a)` in terms of the centralizer of `a`, the subgroup
`E(a)`, and `orderOf a`.
-/
lemma f_a_apply_a_closed_form
    [CharZero k] [Fintype G]
    {a : G} (ha : IsPRegular p a) :
    f_a (k := k) p a a
      =
    (Nat.card (E_subgroup p a) : k)⁻¹
      * (Nat.card (Subgroup.centralizer ({a} : Set G)) : k)
      * (orderOf a : k) := by
  classical
  unfold f_a
  rw [ClassFun.ind_apply_eq_inv_mul_sum]
  dsimp [phi_fun]
  have h_integrand :
      (fun x : G =>
        if hx : x⁻¹ * a * x ∈ E_subgroup p a then
          if Group.pRegular p (x⁻¹ * a * x) = a
          then (orderOf a : k)
          else 0
        else 0)
      =
      (fun x : G =>
        if x ∈ Subgroup.centralizer ({a} : Set G)
        then (orderOf a : k)
        else 0) := by
    ext x
    by_cases hxC : x ∈ Subgroup.centralizer ({a} : Set G)
    · have hxBoth :
          x⁻¹ * a * x ∈ E_subgroup p a ∧
            Group.pRegular p (x⁻¹ * a * x) = a :=
        (conj_inv_mem_E_and_phi_nonzero_iff
          p ha x).mpr hxC
      rcases hxBoth with ⟨hxE, hreg⟩
      rw [dif_pos hxE, if_pos hreg, if_pos hxC]
    · have hxNotBoth :
          ¬ (x⁻¹ * a * x ∈ E_subgroup p a ∧
              Group.pRegular p (x⁻¹ * a * x) = a) :=
        mt (conj_inv_mem_E_and_phi_nonzero_iff
          p ha x).mp hxC
      by_cases hxE : x⁻¹ * a * x ∈ E_subgroup p a
      · have hreg_not :
            Group.pRegular p (x⁻¹ * a * x) ≠ a := by
          intro hreg
          exact hxNotBoth ⟨hxE, hreg⟩
        rw [dif_pos hxE, if_neg hreg_not, if_neg hxC]
      · rw [dif_neg hxE, if_neg hxC]
  have hsum :=
    congrArg
      (fun F : G → k =>
        (Nat.card (E_subgroup p a) : k)⁻¹ * ∑ x : G, F x)
      h_integrand
  rw [hsum]
  rw [Subgroup.sum_ite_mem_centralizer_mul]
  ring_nf

/--
Bernstein's index attached to `a`: the index of the chosen Sylow `p`-subgroup
inside the centralizer of `a`.
-/
noncomputable def bernsteinIndex (x : G) : ℕ :=
  Nat.card (Subgroup.centralizer
    ({x} : Set G)) / Nat.card (PElementary.P_of_Z  p x)

open _root_.Subgroup PElementary in
/--
Evaluation of `f_a` at `a * u`, where `u` is `p`-singular and commutes with
`a`, as a filtered count of conjugates of `u` lying in `P_Z(a)`.
-/
lemma f_a_apply_a_eq_bernsteinIndex
    [CharZero k] [Fintype G]
    {a : G} (ha : IsPRegular p a) :
    f_a (k := k) p a a = (bernsteinIndex p a : k) := by
  rw [f_a_apply_a_closed_form p ha]
  have hE_card : Nat.card (E_subgroup p a) = orderOf a * Nat.card (P_of_Z  p a) := E_card p ha
  have hC_card : Nat.card (centralizer ({a} : Set G)) =
      bernsteinIndex p a * Nat.card (P_of_Z  p a) := by
    have h_dvd : Nat.card (P_of_Z  p a) ∣ Nat.card (centralizer ({a} : Set G)) := by
      rw [PElementary.card_P_of_Z_eq_card_P_in_Z a]
      exact card_subgroup_dvd_card (P_in_Z p a : Subgroup (centralizer ({a} : Set G)))
    rw [bernsteinIndex, Nat.div_mul_cancel h_dvd]
  have h_kE : (Nat.card (E_subgroup p a) : k) =
      (orderOf a : k) * (Nat.card (P_of_Z  p a) : k) := by
    rw [hE_card, Nat.cast_mul]
  have h_kC : (Nat.card (centralizer ({a} : Set G)) : k)
      = (bernsteinIndex  p a : k) * (Nat.card (P_of_Z  p a) : k) := by
    rw [hC_card, Nat.cast_mul]
  rw [h_kE, h_kC]
  have h_ord_ne_zero : (orderOf a : k) ≠ 0 := Nat.cast_ne_zero.mpr (orderOf_pos a).ne'
  have h_P_ne_zero : (Nat.card (P_of_Z  p a) : k) ≠ 0 := Nat.cast_ne_zero.mpr Nat.card_pos.ne'
  calc ((orderOf a : k) * (Nat.card (P_of_Z  p a) : k))⁻¹ * ((bernsteinIndex p a : k) *
          (Nat.card (P_of_Z  p a) : k)) * (orderOf a : k)
    _ = (orderOf a : k)⁻¹ * (Nat.card (P_of_Z  p a) : k)⁻¹ * ((bernsteinIndex p a : k) *
          (Nat.card (P_of_Z  p a) : k)) * (orderOf a : k) := by rw [mul_inv]
    _ = (bernsteinIndex p a : k) * ((Nat.card (P_of_Z  p a) : k)⁻¹ * (Nat.card (P_of_Z  p a) : k))
          * ((orderOf a : k)⁻¹ * (orderOf a : k)) := by ring
    _ = (bernsteinIndex p a : k) * 1 * 1 :=
        by rw [inv_mul_cancel₀ h_P_ne_zero, inv_mul_cancel₀ h_ord_ne_zero]
    _ = (bernsteinIndex p a : k) :=
        by ring

open PElementary in
lemma f_a_apply_self_coprime
    [CharZero k] [Fintype G]
    {a : G} (ha : IsPRegular p a) :
    ∃ n : ℤ,
      f_a (k := k) p a a = (n : k) ∧
        ¬ (p : ℤ) ∣ n := by
  let n : ℕ := bernsteinIndex p a
  refine ⟨(n : ℤ), ?_, ?_⟩
  · rw [f_a_apply_a_eq_bernsteinIndex (k := k) p ha]
    simp [n]
  · rw [Int.ofNat_dvd]
    simpa [n, bernsteinIndex] using
      PElementary.p_not_dvd_cardCentralizer_div_cardP
        (p := p) (x := a)

end EvaluationAtA

section EvaluationAtRegularTimesSingular

/-!
## Evaluation of `f_a` at `a * s`

This section evaluates `f_a` on elements with `p`-regular part `a`.  The
formula is first written as a filtered conjugacy count and then converted into
a fixed-point count on cosets of `P_Z(a)` in the centralizer of `a`.
-/

variable (p : ℕ)
variable {k : Type u} [Field k]
variable {G : Type v} [Group G] [Fact p.Prime]

open Classical PElementary _root_.Subgroup in
/--
Evaluates f_a at x = a * s, reducing the induction sum to a count of elements in C_G(a)
that conjugate s into the Sylow p-subgroup P_Z(a).
-/
lemma f_a_apply_mul_pSingular_eq_sum
    [CharZero k] [Fintype G]
    {a : G} (ha : IsPRegular p a) (s : G) (hu_sing : IsPSingular p s) (hu_comm : Commute a s) :
    f_a (k := k) (p := p) a (a * s) =
    (Nat.card (E_subgroup p a) : k)⁻¹ *
      ((Finset.univ.filter
          (fun x => x ∈ centralizer ({a} : Set G) ∧ x * s * x⁻¹ ∈ P_of_Z p a)).card : k)  *
      (orderOf a : k) := by
  unfold f_a
  rw [ClassFun.ind_apply_eq_inv_mul_sum_mul_inv]
  simp only [Nat.card_eq_fintype_card]
  dsimp [phi_fun]
  have hfa := isOfFinOrder_of_finite a
  have hfs := isOfFinOrder_of_finite s
  have h_sum :
      (∑ x : G, if h : x * (a * s) * x⁻¹ ∈ E_subgroup p a
                then if Group.pRegular p (x * (a * s) * x⁻¹) = a
                then (orderOf a : k) else 0 else 0) =
      ∑ x ∈ Finset.univ.filter
        (fun x => x ∈ centralizer ({a} : Set G) ∧ x * s * x⁻¹ ∈ P_of_Z p a), (orderOf a : k) := by
    rw [Finset.sum_filter]
    apply Finset.sum_congr rfl
    intro x _
    have h_reg :
        Group.pRegular p (x * (a * s) * x⁻¹) = x * a * x⁻¹ := by
      rw [Group.pRegular_conj]
      have h_au : Group.pRegular p (a * s) = a := by
        rw [Group.pRegular_mul_eq_left_of_right_pSingular_commute p hfs hfa hu_sing hu_comm.symm]
        exact Group.pRegular_eq_self_of_isPRegular p hfa ha
      rw [h_au]
    by_cases hxC : x ∈ centralizer ({a} : Set G)
    · have hax : x * a * x⁻¹ = a := by
        rw [mem_centralizer_iff] at hxC
        have h_comm_xa : x * a = a * x := by exact Eq.symm (SemiconjBy.eq (hxC a rfl))
        calc x * a * x⁻¹ = a * x * x⁻¹ := by rw [h_comm_xa]
          _ = a := by group
      have h_reg_eq_a : Group.pRegular p (x * (a * s) * x⁻¹) = a := by rw [h_reg, hax]
      have h_xaux : x * (a * s) * x⁻¹ = a * (x * s * x⁻¹) := by
        calc x * (a * s) * x⁻¹ = (x * a * x⁻¹) * (x * s * x⁻¹) := by group
          _ = a * (x * s * x⁻¹) := by rw [hax]
      have h_E_iff : x * (a * s) * x⁻¹ ∈ E_subgroup p a ↔ x * s * x⁻¹ ∈ P_of_Z p a := by
        rw [h_xaux]
        constructor
        · intro h_in_E
          have ha_inv_in : a⁻¹ ∈ E_subgroup p a :=
              (E_subgroup p a).inv_mem (mem_sup_left (mem_zpowers a))
          have h_mul := (E_subgroup p a).mul_mem ha_inv_in h_in_E
          have h_cancel : a⁻¹ * (a * (x * s * x⁻¹)) = x * s * x⁻¹ := by group
          rw [h_cancel] at h_mul
          let h_elem := associatedSubgroup ha
          have h_sing : IsPSingular p (x * s * x⁻¹) := (IsPSingular.isConj p hu_sing) (by simp)
          let z : E_subgroup p a := ⟨x * s * x⁻¹, h_mul⟩
          have hz_sing : IsPSingular p z := by
              simpa [z] using
                (IsPSingular.subtype_iff
                  (p := p)
                  (H := E_subgroup p a)
                  (x := z)).1 h_sing
          have hz_mem_P : z ∈ h_elem.P := by exact (mem_P_iff_pSingular h_elem).mpr hz_sing
          exact mem_carrier.mp hz_mem_P
        · intro h_in_P
          have h_P_in_E : x * s * x⁻¹ ∈ E_subgroup p a := mem_sup_right h_in_P
          have h_a_in_E : a ∈ E_subgroup p a := mem_sup_left (mem_zpowers a)
          exact (E_subgroup p a).mul_mem h_a_in_E h_P_in_E
      by_cases hP : x * s * x⁻¹ ∈ P_of_Z p a
      · have hE : x * (a * s) * x⁻¹ ∈ E_subgroup p a := h_E_iff.mpr hP
        rw [dif_pos hE, if_pos h_reg_eq_a]
        simp [hxC, hP]
      · have hnE : x * (a * s) * x⁻¹ ∉ E_subgroup p a := fun h => hP (h_E_iff.mp h)
        rw [dif_neg hnE]
        simp [hP]
    · have h_reg_ne_a : Group.pRegular p (x * (a * s) * x⁻¹) ≠ a := by
        intro h_eq
        rw [h_reg] at h_eq
        apply hxC
        rw [mem_centralizer_iff]
        intro y hy
        rw [Set.mem_singleton_iff] at hy
        subst hy
        have h_xa : x * y = y * x := by
          calc x * y = x * y * x⁻¹ * x := by group
            _ = y * x := by rw [h_eq]
        exact Eq.symm h_xa
      by_cases hE : x * (a * s) * x⁻¹ ∈ E_subgroup p a
      · rw [dif_pos hE, if_neg h_reg_ne_a]
        simp [hxC]
      · rw [dif_neg hE]
        simp [hxC]
  rw [h_sum, Finset.sum_const, nsmul_eq_mul, mul_assoc]

open Classical PElementary _root_.Subgroup in
/--
Evaluation of `f_a(a * )` as the number of fixed cosets of `P_Z(a)` in the
centralizer of `a`.
-/
lemma f_a_apply_mul_pSingular_eq_Nfix
    [CharZero k] [Fintype G]
    {a : G} (ha : IsPRegular p a) (s : G) (hu_sing : IsPSingular p s) (hu_comm : Commute a s) :
    f_a (k := k) p a (a * s) =
    (Nat.card { c : ↥(centralizer ({a} : Set G)) ⧸ (P_in_Z p a : Subgroup _) //
      (⟨s, fun y hy => by rcases hy with rfl; exact hu_comm.eq⟩ :
        ↥(centralizer ({a} : Set G))) • c = c } : k) := by
  rw [f_a_apply_mul_pSingular_eq_sum p ha s hu_sing hu_comm]
  let Z_group := centralizer ({a} : Set G)
  let P_Z : Subgroup Z_group := P_in_Z p a
  let s_Z : Z_group := ⟨s, fun y hy => by rcases hy with rfl; exact hu_comm.eq⟩
  have h_set_card :
      (Finset.univ.filter (fun x : G => x ∈ Z_group ∧ x * s * x⁻¹ ∈ P_of_Z p a)).card =
      Nat.card { x : G // x ∈ Z_group ∧ x * s * x⁻¹ ∈ P_of_Z p a } := by
    rw [Nat.card_eq_fintype_card]
    exact (Fintype.card_subtype _).symm
  let e_inv :
    { x : G // x ∈ Z_group ∧ x * s * x⁻¹ ∈ P_of_Z p a } ≃
    { x : G // x ∈ Z_group ∧ x⁻¹ * s * x ∈ P_of_Z p a } :=
  { toFun := fun x => ⟨x.val⁻¹, by
      have hx := x.property
      refine ⟨Subgroup.inv_mem _ hx.1, ?_⟩
      have : (x.val⁻¹)⁻¹ * s * x.val⁻¹ = x.val * s * x.val⁻¹ := by rw [inv_inv]
      rw [this]
      exact hx.2⟩
    invFun := fun x => ⟨x.val⁻¹, by
      have hx := x.property
      refine ⟨Subgroup.inv_mem _ hx.1, ?_⟩
      have : x.val⁻¹ * s * (x.val⁻¹)⁻¹ = x.val⁻¹ * s * x.val := by rw [inv_inv]
      rw [this]
      exact hx.2⟩
    left_inv := fun x => Subtype.ext (inv_inv x.val)
    right_inv := fun x => Subtype.ext (inv_inv x.val) }
  have h_bij :
    Nat.card { x : G // x ∈ Z_group ∧ x * s * x⁻¹ ∈ P_of_Z p a } =
    Nat.card { x : G // x ∈ Z_group ∧ x⁻¹ * s * x ∈ P_of_Z p a } := Nat.card_congr e_inv
  let e_lift :
    { x : G // x ∈ Z_group ∧ x⁻¹ * s * x ∈ P_of_Z p a } ≃
    { x : Z_group // x⁻¹ * s_Z * x ∈ P_Z } :=
  { toFun := fun x =>
      let z_x : Z_group := ⟨x.val, x.property.1⟩
      ⟨z_x, by
        have h_mem := x.property.2
        unfold P_of_Z at h_mem
        rw [Subgroup.mem_map] at h_mem
        rcases h_mem with ⟨w, hw_mem, hw_eq⟩
        have h_eq : z_x⁻¹ * s_Z * z_x = w := by
          ext
          exact hw_eq.symm
        rw [h_eq]
        exact hw_mem⟩
    invFun := fun z =>
      ⟨z.val.val, z.val.property, by
        have h_mem := z.property
        unfold P_of_Z
        rw [Subgroup.mem_map]
        use z.val⁻¹ * s_Z * z.val
        exact ⟨h_mem, rfl⟩⟩
    left_inv := fun x => by ext; rfl
    right_inv := fun z => by ext; rfl }
  have h_card_lift :
      Nat.card { x : G // x ∈ Z_group ∧ x⁻¹ * s * x ∈ P_of_Z p a } =
      Nat.card { x : Z_group // x⁻¹ * s_Z * x ∈ P_Z } :=
    Nat.card_congr e_lift
  have h_equiv := Subgroup.conjMemEquiv_fixedPointsProd P_Z s_Z
  have h_card_prod :
      Nat.card { x : Z_group // x⁻¹ * s_Z * x ∈ P_Z } =
      Nat.card ({ c : Z_group ⧸ P_Z // s_Z • c = c } × P_Z) := Nat.card_congr h_equiv
  have h_card_final :
      ((Finset.univ.filter (fun x : G => x ∈ Z_group ∧ x * s * x⁻¹ ∈ P_of_Z p a)).card : k) =
      (Nat.card { c : Z_group ⧸ P_Z // s_Z • c = c } : k) * (Nat.card P_Z : k) := by
    rw [h_set_card, h_bij, h_card_lift, h_card_prod, Nat.card_prod, Nat.cast_mul]
  rw [h_card_final]
  have hE_card :
      Nat.card (E_subgroup p a) =
        orderOf a * Nat.card (P_of_Z p a) := by
    exact E_card (p := p) (G := G) ha
  have hP_card : Nat.card (P_of_Z p a) = Nat.card P_Z :=
    PElementary.card_P_of_Z_eq_card_P_in_Z a
  have h_kE : (Nat.card (E_subgroup p a) : k) = (orderOf a : k) * (Nat.card P_Z : k) := by
    rw [hE_card, hP_card, Nat.cast_mul]
  have h_ord_ne_zero : (orderOf a : k) ≠ 0 := Nat.cast_ne_zero.mpr (orderOf_pos a).ne'
  have h_P_ne_zero : (Nat.card P_Z : k) ≠ 0 := Nat.cast_ne_zero.mpr Nat.card_pos.ne'
  rw [h_kE]
  calc ((orderOf a : k) * (Nat.card P_Z : k))⁻¹ *
      ((Nat.card { c : Z_group ⧸ P_Z // s_Z • c = c } : k) * (Nat.card P_Z : k)) * (orderOf a : k)
  _ = (orderOf a : k)⁻¹ * (Nat.card P_Z : k)⁻¹ *
      ((Nat.card { c : Z_group ⧸ P_Z // s_Z • c = c } : k) *
      (Nat.card P_Z : k)) * (orderOf a : k) := by rw [mul_inv]
  _ = (Nat.card { c : Z_group ⧸ P_Z // s_Z • c = c } : k) * ((Nat.card P_Z : k)⁻¹ *
        (Nat.card P_Z : k)) * ((orderOf a : k)⁻¹ * (orderOf a : k)) := by ring
  _ = (Nat.card { c : Z_group ⧸ P_Z // s_Z • c = c } : k) * 1 * 1 :=
        by rw [inv_mul_cancel₀ h_P_ne_zero, inv_mul_cancel₀ h_ord_ne_zero]
  _ = (Nat.card { c : Z_group ⧸ P_Z // s_Z • c = c } : k) := by ring

end EvaluationAtRegularTimesSingular

section ZlocalEvaluation

/-!
## The `p`-local value of `f_a(a)`

This final section reinterprets Bernstein's index in the localization `Zlocal p`
and proves that `f_a(a)` is the image of a unit in the `p`-local integers.
-/

variable (p : ℕ)
variable {k : Type u} [CommRing k]
variable {G : Type v} [Group G] [Fact p.Prime]

/--
Index viewed in `ℤ`.
-/
noncomputable def bernsteinIndexZ (x : G) : ℤ :=
  (bernsteinIndex p x : ℤ)

lemma bernsteinIndexZ_mem_intCoprimeSubmonoid [Finite G]
    (x : G) :
    bernsteinIndexZ p x ∈ Zlocal.intCoprimeSubmonoid p := by
  have hp : Nat.Prime p := (Fact.out : Nat.Prime p)
  have hnnot : ¬ p ∣ bernsteinIndex  p x := by
    simpa [bernsteinIndex] using
      (PElementary.p_not_dvd_cardCentralizer_div_cardP  (p := p) x)
  have hcop : Nat.Coprime (bernsteinIndex  p x) p := by
    apply Nat.Coprime.symm
    exact (hp.coprime_iff_not_dvd).2 hnnot
  simpa [bernsteinIndexZ, bernsteinIndex, Zlocal.intCoprimeSubmonoid, hcop]

lemma bernsteinIndexZ_isUnit_in_Zlocal [Finite G]
    (x : G) :
    IsUnit (algebraMap ℤ (Zlocal p) (bernsteinIndexZ  p x)) := by
  have hxmem :
      bernsteinIndexZ p x ∈ Zlocal.intCoprimeSubmonoid p :=
        bernsteinIndexZ_mem_intCoprimeSubmonoid  (p := p) x
  simpa using
    (IsLocalization.map_units
      (R := ℤ) (M := Zlocal.intCoprimeSubmonoid p) (S := Zlocal p)
      (y := ⟨bernsteinIndexZ  p x, hxmem⟩))

/--
f_a(a) evaluates exactly to the image of a unit in the p-local integers.
-/
lemma f_a_apply_a_isUnit_Zlocal
    {k : Type u} [Field k] [CharZero k] [Fintype G]
    {a : G} (ha : IsPRegular p a) :
    ∃ u : (Zlocal p)ˣ, Zlocal.toK (k := k) p (u : Zlocal p) = f_a p a a := by
  have h_eq := f_a_apply_a_eq_bernsteinIndex (k := k) p ha
  have h_unit := bernsteinIndexZ_isUnit_in_Zlocal  p a
  use h_unit.unit
  have h_val : (h_unit.unit : Zlocal p) = algebraMap ℤ (Zlocal p) (bernsteinIndexZ  p a) :=
    h_unit.unit_spec
  rw [h_eq, h_val]
  have h_hom_eval : Zlocal.toK (k := k) p (algebraMap ℤ (Zlocal p) (bernsteinIndexZ  p a))
      = (bernsteinIndexZ  p a : k) := by
    unfold Zlocal.toK
    exact IsLocalization.lift_eq
        (M := Zlocal.intCoprimeSubmonoid p) (g := Int.castRingHom k) _ (bernsteinIndexZ  p a)
  rw [h_hom_eval]
  simp only [bernsteinIndexZ, Int.cast_natCast]

end ZlocalEvaluation

end ClassFun

end Slop
