/-
Copyright (c) 2025 Jack McCarthy. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jack McCarthy
-/
module

public import FLT.Slop.BrauerInduction.LocalToGlobal
public import FLT.Slop.BrauerInduction.Span
public import FLT.Slop.BrauerInduction.Background.Fintype.Basic

/-!
# Projection from `Λ`-coefficients to integral coefficients

This file formalizes Bernstein's Step 2 projection and applies it coefficientwise
to class functions.

The first part proves a general algebra lemma: in a finitely generated free
`ℤ`-module, any primitive element admits a `ℤ`-linear projection to `ℤ` sending
that element to `1`.  Applying this to the coefficient ring `ClassFun.Lambda k G`
gives Bernstein's homomorphism

`ν : Λ → ℤ`

with `ν(1) = 1`.

The second part extends `ν` to a partial coefficient projection `nuExt : k → k`,
which agrees with `ν` on elements of `Λ` and is defined to be `0` outside `Λ`.
This is not a ring homomorphism on all of `k`; its additivity and
`ℤ`-linearity are used only for elements known to lie in `Λ`.

The final part applies `nuExt` coefficientwise in an irreducible-character
basis.  This gives a map `nuStar` on class functions.  The key result is that
`nuStar` sends the global Bernstein span `jGlobal` into the span generated by
characters induced from Brauer-elementary subgroups.  Since `nuStar 1 = 1`,
the local-to-global result `1 ∈ jGlobal` implies
`1 ∈ BrauerSpanChar`.
-/

@[expose] public section

namespace Slop
open Slop

universe u v

namespace BrauerInduction

/--
In a finitely generated free `ℤ`-module, every primitive element admits a
linear projection to `ℤ` sending it to `1`.

Here “primitive” means that if `v = m • x`, then `m` is a unit of `ℤ`.
-/
lemma exists_projection_of_primitive {M : Type*} [AddCommGroup M] [Module ℤ M]
    [Module.Free ℤ M] [Module.Finite ℤ M]
    (v : M) (h_prim : ∀ (m : ℤ) (x : M), m • x = v → IsUnit m) :
    ∃ ν : M →ₗ[ℤ] ℤ, ν v = 1 := by
  let eval_v : (M →ₗ[ℤ] ℤ) →ₗ[ℤ] ℤ := {
    toFun := fun f => f v
    map_add' := fun f g => rfl
    map_smul' := fun c f => rfl
  }
  let I := LinearMap.range eval_v
  haveI : Submodule.IsPrincipal I := inferInstance
  obtain ⟨d, hd⟩ : ∃ d, Submodule.span ℤ {d} = I :=
    ⟨Submodule.IsPrincipal.generator I, Submodule.IsPrincipal.span_singleton_generator I⟩
  let ι := Module.Free.ChooseBasisIndex ℤ M
  letI : Fintype ι := Module.Free.ChooseBasisIndex.fintype ℤ M
  let b := Module.Free.chooseBasis ℤ M
  have h_coord_in : ∀ i, b.coord i v ∈ I := by
    intro i
    exact LinearMap.mem_range.mpr ⟨b.coord i, rfl⟩
  have h_w : ∀ i, ∃ w_i : ℤ, b.coord i v = d * w_i := by
    intro i
    have h1 := h_coord_in i
    rw [← hd] at h1
    have h2 := Submodule.mem_span_singleton.mp h1
    obtain ⟨y, hy⟩ := h2
    use y
    rw [← hy, smul_eq_mul, mul_comm]
  choose w hw using h_w
  let W_repr : ι →₀ ℤ := ∑ i, Finsupp.single i (w i)
  let W := b.repr.symm W_repr
  have h_W_repr_i : ∀ i, W_repr i = w i := by
    intro i
    have h_eval : W_repr i = ∑ j, (Finsupp.single j (w j)) i := by
      exact Finsupp.finsetSum_apply Finset.univ (fun j => Finsupp.single j (w j)) i
    rw [h_eval]
    rw [Finset.sum_eq_single i]
    · exact Finsupp.single_eq_same
    · intro j _ hj
      exact Finsupp.single_eq_of_ne hj.symm
    · intro hi
      exact False.elim (hi (Finset.mem_univ i))
  have h_dW : d • W = v := by
    apply b.repr.injective
    ext i
    have h_lhs : b.repr (d • W) i = d * w i := by
      simp only [map_zsmul, Finsupp.coe_smul, Pi.smul_apply,
        Int.zsmul_eq_mul, mul_eq_mul_left_iff]
      rw [LinearEquiv.apply_symm_apply]
      rw [h_W_repr_i i]
      simp only [true_or]
    rw [h_lhs]
    have h_cw := hw i
    exact h_cw.symm
  have hd_unit : IsUnit d := h_prim d W h_dW
  have h_1_in : (1 : ℤ) ∈ I := by
    rw [← hd, Submodule.mem_span_singleton]
    obtain ⟨u, hu⟩ := hd_unit
    use ↑(u⁻¹)
    rw [← hu, smul_eq_mul]
    exact Units.inv_mul u
  obtain ⟨nu_lin, h_nu_one⟩ := LinearMap.mem_range.mp h_1_in
  use nu_lin
  exact h_nu_one

section LambdaProjection
/-!
## Coefficient projection on class functions

This section defines `nuStar` and proves its basic algebraic properties.
The finite-group assumption enters through the coefficient ring `Λ` and the
projection `nuExt`.
-/

variable {G : Type v} [Group G] [Finite G]
variable {k : Type u} [Field k] [CharZero k]

/--
Bernstein's Lemma 2 for the coefficient ring `Λ`.

There is an additive homomorphism `ν : Λ → ℤ` sending `1` to `1`.
-/
lemma exists_projection
    [Module.Finite ℤ (ClassFun.Lambda k G)] [Module.Free ℤ (ClassFun.Lambda k G)] :
    ∃ ν : (ClassFun.Lambda k G) →+ ℤ, ν 1 = 1 := by
  have h_prim : ∀ (m : ℤ) (x : ClassFun.Lambda k G), m • x = 1 → IsUnit m :=
    ClassFun.Lambda.one_is_primitive (G := G) (k:=k)
  obtain ⟨nu_lin, h_nu_one⟩ := exists_projection_of_primitive (1 : ClassFun.Lambda k G) h_prim
  use nu_lin.toAddMonoidHom
  exact h_nu_one

/--
A chosen Bernstein projection `ν : Λ → ℤ`.
-/
noncomputable def nu
    (k : Type u) [Field k] [CharZero k]
    (G : Type v) [Group G] [Finite G] :
    ClassFun.Lambda k G →+ ℤ := by
  haveI : NeZero (Nat.card G) :=
    ⟨One.natCard_ne_zero_of_finite G⟩
  exact Classical.choose (exists_projection (G := G) (k := k))

@[simp]
lemma nu_zero :
    nu k G 0 = 0 := by
  exact (nu k G).map_zero

lemma nu_one : nu k G 1 = 1 := by
  haveI : NeZero (Nat.card G) := ⟨One.natCard_ne_zero_of_finite G⟩
  exact Classical.choose_spec (exists_projection)

open Classical in
/--
The coefficient projection extended to all of `k` by zero outside `Λ`.

This function is only additive and `ℤ`-linear on inputs known to lie in `Λ`;
it is not intended to be a ring homomorphism on `k`.
-/
noncomputable def nuExt
    (k : Type u) [Field k] [CharZero k]
    (G : Type v) [Group G] [Finite G]
    (x : k) : k :=
  if h : x ∈ ClassFun.Lambda k G then (nu k G ⟨x, h⟩ : k) else 0

@[simp]
lemma nu_ext_one :
    nuExt k G 1 = 1 := by
  have h1 : (1 : k) ∈ ClassFun.Lambda k G := Subring.one_mem _
  unfold nuExt
  rw [dif_pos h1]
  change ((nu k G) (1 : ClassFun.Lambda k G) : k) = 1
  rw [nu_one, Int.cast_one]

@[simp]
lemma nu_ext_zero :
    nuExt k G 0 = 0 := by
  have h0 : (0 : k) ∈ ClassFun.Lambda k G := Subring.zero_mem _
  unfold nuExt
  rw [dif_pos h0]
  change ((nu k G) (0 : ClassFun.Lambda k G) : k) = 0
  rw [nu_zero, Int.cast_zero]

/-- nuExt is additive on Λ -/
@[simp]
lemma nu_ext_add
    {x y : k} (hx : x ∈ ClassFun.Lambda k G) (hy : y ∈ ClassFun.Lambda k G) :
    nuExt k G (x + y) = nuExt k G x + nuExt k G y := by
  have hxy : x + y ∈ ClassFun.Lambda k G := Subring.add_mem _ hx hy
  unfold nuExt
  rw [dif_pos hx, dif_pos hy, dif_pos hxy]
  have h_add := map_add (nu k G) ⟨x, hx⟩ ⟨y, hy⟩
  change (nu k G ⟨x + y, hxy⟩ : k) = (nu k G ⟨x, hx⟩ : k) + (nu k G ⟨y, hy⟩ : k)
  rw [← Int.cast_add]
  congr 1

/-- nuExt preserves integer scalar multiplication on Λ -/
@[simp]
lemma nu_ext_int_mul
    {x : k} (hx : x ∈ ClassFun.Lambda k G) (z : ℤ) :
    nuExt k G ((z : k) * x) = (z : k) * nuExt k G x := by
  have hzx : (z : k) * x ∈ ClassFun.Lambda k G := by
    have h_smul : (z : k) * x = z • x := by exact Eq.symm (zsmul_eq_mul x z)
    rw [h_smul]
    exact zsmul_mem hx z
  unfold nuExt
  rw [dif_pos hx, dif_pos hzx]
  have h_eq : (⟨(z : k) * x, hzx⟩ : ClassFun.Lambda k G) = z • ⟨x, hx⟩ := by
    ext
    exact Eq.symm (zsmul_eq_mul x z)
  rw [h_eq, map_zsmul]
  simp only [Int.zsmul_eq_mul, Int.cast_mul]

/-- nuExt acts as the exact identity on purely integer values. -/
@[simp]
lemma nu_ext_int
    (z : ℤ) : nuExt k G (z : k) = (z : k) := by
  have hz : (z : k) ∈ ClassFun.Lambda k G := by
    have h_smul : (z : k) = z • (1 : k) := by
      calc (z : k) = (z : k) * 1 := (mul_one _).symm
           _ = z • (1 : k) := by exact Eq.symm (zsmul_eq_mul (1 : k) z)
    rw [h_smul]
    exact zsmul_mem (Subring.one_mem _) z
  unfold nuExt
  rw [dif_pos hz]
  have h_eq : (⟨(z : k), hz⟩ : ClassFun.Lambda k G) = z • (1 : ClassFun.Lambda k G) := by
    ext
    calc (z : k) = (z : k) * 1 := (mul_one _).symm
         _ = z • (1 : k) := by exact Eq.symm (zsmul_eq_mul (1 : k) z)
  rw [h_eq, map_zsmul, nu_one (G:=G) (k:=k)]
  simp only [Int.zsmul_eq_mul, mul_one]

end LambdaProjection

section CharacterCoefficientProjection

/-!
## Projection on class-function coefficients

This section fixes an irreducible-character basis and applies `ν` to the
coordinates of a class function.  The resulting map `nuStar` fixes characters of
finite-dimensional representations and sends the global Bernstein span into
`BrauerSpanChar`.
-/

variable {k : Type u} [Field k] [CharZero k]
variable {G : Type v} [Group G]

/--
Apply Bernstein's coefficient projection to the coordinates of a class function
in a fixed irreducible-character basis.
-/
noncomputable def nuStar [Finite G]
    (B : ClassFun.IrrepCharBasis k G) (f : ClassFun k G) : ClassFun k G :=
  B.b.repr.symm
    ((B.b.repr f).mapRange
      (fun a : k => nuExt (k := k) (G := G) a)
      (by simp))

/-- `nuStar` fixes each irreducible-character basis vector. -/
@[simp]
lemma nuStar_basis [Finite G]
    (B : ClassFun.IrrepCharBasis k G) (i : B.ι) :
    nuStar B (B.b i) = B.b i := by
  unfold nuStar
  simp

/--
The coordinates of `nuStar B f` are obtained by applying `nuExt` to the
coordinates of `f`.
-/
@[simp]
lemma repr_nuStar_apply [Finite G]
    (B : ClassFun.IrrepCharBasis k G) (f : ClassFun k G) (i : B.ι) :
    B.b.repr (nuStar B f) i =
      nuExt (k := k) (G := G) (B.b.repr f i) := by
  unfold nuStar
  simp

@[simp]
lemma nuStar_char_basis [Finite G]
    (B : ClassFun.IrrepCharBasis k G) (i : B.ι) :
    nuStar B (ClassFun.character (B.V i)) =
      ClassFun.character (B.V i) := by
  rw [← B.b_eq i]
  simp

@[simp]
lemma nuStar_zero [Finite G]
    (B : ClassFun.IrrepCharBasis k G) :
    nuStar B 0 = 0 := by
  apply B.b.repr.injective
  ext i
  simp

/--
`nuStar` is additive on class functions whose coordinates all lie in `Λ`.
-/
lemma nuStar_add [Finite G]
    (B : ClassFun.IrrepCharBasis k G)
    {f g : ClassFun k G}
    (hf : ClassFun.HasLambdaCoords B f)
    (hg : ClassFun.HasLambdaCoords B g) :
    nuStar B (f + g) = nuStar B f + nuStar B g := by
  apply B.b.repr.injective
  ext i
  rw [repr_nuStar_apply]
  rw [LinearEquiv.map_add]
  change
    nuExt (k := k) (G := G) ((B.b.repr f) i + (B.b.repr g) i)
      =
    (B.b.repr (nuStar B f + nuStar B g)) i
  rw [nu_ext_add (hf i) (hg i)]
  simp

lemma nuStar_smul_char
    {G : Type u} [Group G] [Finite G]
    (B : ClassFun.IrrepCharBasis k G)
    {a : k} (ha : a ∈ ClassFun.Lambda k G)
    (U : FDRep k G) :
    nuStar B (a • ClassFun.character U) =
      nuExt (k := k) (G := G) a • ClassFun.character U := by
  apply B.b.repr.injective
  ext i
  rw [repr_nuStar_apply]
  have hcoord :
      B.b.repr (a • ClassFun.character U) i =
        a * B.b.repr (ClassFun.character U) i := by
    rw [LinearEquiv.map_smul]
    rfl
  rw [hcoord]
  obtain ⟨m, hm⟩ := ClassFun.char_coeffs_int B U i
  rw [hm]
  have hmul : a * (m : k) = (m : k) * a := by ring
  rw [hmul]
  rw [nu_ext_int_mul (k := k) (G := G) ha m]
  rw [LinearEquiv.map_smul]
  simp only [Finsupp.coe_smul, Pi.smul_apply, hm, smul_eq_mul]
  ring

/--
`nuStar` commutes with integral scalar multiplication on class functions whose
coordinates all lie in `Λ`.
-/
lemma nuStar_zsmul [Finite G]
    (B : ClassFun.IrrepCharBasis k G)
    (z : ℤ) {f : ClassFun k G}
    (hf : ClassFun.HasLambdaCoords B f) :
    nuStar B (z • f) = z • nuStar B f := by
  apply B.b.repr.injective
  ext i
  rw [repr_nuStar_apply]
  have hcoord :
      B.b.repr (z • f) i = (z : k) * (B.b.repr f i) := by
    have hz :
        z • f = (z : k) • f :=
      Eq.symm (Int.cast_smul_eq_zsmul k z f)
    rw [hz, LinearEquiv.map_smul]
    rfl
  rw [hcoord]
  rw [nu_ext_int_mul (k := k) (G := G) (hf i) z]
  have hcoord_rhs :
      B.b.repr (z • nuStar B f) i =
        z • (B.b.repr (nuStar B f) i) := by
    have hz :
        z • nuStar B f = (z : k) • nuStar B f :=
      Eq.symm (Int.cast_smul_eq_zsmul k z (nuStar B f))
    rw [hz, LinearEquiv.map_smul]
    change (z : k) * (B.b.repr (nuStar B f) i) =
      z • (B.b.repr (nuStar B f) i)
    exact Eq.symm (zsmul_eq_mul (B.b.repr (nuStar B f) i) z)
  rw [hcoord_rhs, repr_nuStar_apply, zsmul_eq_mul]

/--
`nuStar` fixes the character of every finite-dimensional representation.
-/
lemma nuStar_fixes_char
    {G : Type u} [Group G] [Finite G]
    (B : ClassFun.IrrepCharBasis k G)
    (U : FDRep k G) :
    nuStar B (ClassFun.character U) = ClassFun.character U := by
  apply B.b.repr.injective
  ext i
  rw [repr_nuStar_apply]
  obtain ⟨m, hm⟩ := ClassFun.char_coeffs_int B U i
  rw [hm]
  simp

lemma nuStar_one
    {G : Type u} [Group G] [Finite G]
    (B : ClassFun.IrrepCharBasis k G) :
    nuStar B (1 : ClassFun k G) = 1 := by
  have htriv :
      ClassFun.character (FDRep.trivial k G) = (1 : ClassFun k G) :=
    ClassFun.char_trivial (k := k) (G := G)
  rw [← htriv]
  exact nuStar_fixes_char B (FDRep.trivial k G)

/--
Projection of an induced `Q`-function from a `p`-elementary subgroup lands in
`BrauerSpanChar`.

This is the main bridge between Bernstein's global span `jGlobal` and the
span generated by induced characters from Brauer-elementary subgroups.
-/
lemma nuStar_projects_E
    {G : Type u} [Group G] [Fintype G]
    (B : ClassFun.IrrepCharBasis k G)
    (p : ℕ) [Fact p.Prime]
    (E : Subgroup G) (hE : IsPElementary p E)
    (q : ClassFun k E)
    (hq : q ∈ ClassFun.qSys k G E) :
    ClassFun.HasLambdaCoords B (ClassFun.ind E q) ∧
      nuStar B (ClassFun.ind E q) ∈ BrauerSpanChar (k := k) (G := G) := by
  have h_Q :
      ∃ l : List (FDRep k E × ClassFun.Lambda k G),
        q =
          (l.map fun P =>
            (P.2 : k) • ClassFun.character P.1).sum := by
    have hqR : q ∈ ClassFun.rLambda k G E := hq.1
    unfold ClassFun.rLambda at hqR
    refine Submodule.span_induction
      (p := fun q _ =>
        ∃ l : List (FDRep k E × ClassFun.Lambda k G),
          q =
            (l.map fun P =>
              (P.2 : k) • ClassFun.character P.1).sum)
      ?gen ?zero ?add ?smul hqR
    · rintro χ ⟨W, rfl⟩
      refine ⟨[(W, 1)], ?_⟩
      simp
    · refine ⟨[], ?_⟩
      simp
    · intro q₁ q₂ _ _ hq₁ hq₂
      rcases hq₁ with ⟨l₁, rfl⟩
      rcases hq₂ with ⟨l₂, rfl⟩
      refine ⟨l₁ ++ l₂, ?_⟩
      simp [List.map_append, List.sum_append]
    · intro a q _ hq
      rcases hq with ⟨l, rfl⟩
      refine ⟨l.map fun P => (P.1, a * P.2), ?_⟩
      have scale_list :
          ∀ l : List (FDRep k E × ClassFun.Lambda k G),
            a •
                (l.map fun P =>
                  (P.2 : k) • ClassFun.character P.1).sum
              =
                ((l.map fun P => (P.1, a * P.2)).map fun P =>
                  (P.2 : k) • ClassFun.character P.1).sum := by
        intro l
        induction l with
        | nil =>
            simp
        | cons hd tl ih_tl =>
            simp only [List.map_cons, List.sum_cons]
            have hhead :
                a • ((hd.2 : k) • ClassFun.character hd.1)
                  =
                (((a * hd.2 : ClassFun.Lambda k G) : k) • ClassFun.character hd.1) := by
              change
                (a : k) • ((hd.2 : k) • ClassFun.character hd.1)
                  =
                (((a * hd.2 : ClassFun.Lambda k G) : k) • ClassFun.character hd.1)
              rw [show ((a * hd.2 : ClassFun.Lambda k G) : k) =
                    (a : k) * (hd.2 : k) by rfl]
              rw [mul_smul]
            calc
              a •
                  (((hd.2 : k) • ClassFun.character hd.1)
                    + (tl.map fun P =>
                        (P.2 : k) • ClassFun.character P.1).sum)
                  =
                a • ((hd.2 : k) • ClassFun.character hd.1)
                  + a •
                    (tl.map fun P =>
                      (P.2 : k) • ClassFun.character P.1).sum := by
                    rw [smul_add]
              _ =
                (((a * hd.2 : ClassFun.Lambda k G) : k) • ClassFun.character hd.1)
                  +
                (((tl.map fun P => (P.1, a * P.2)).map fun P =>
                    (P.2 : k) • ClassFun.character P.1).sum) := by
                    rw [hhead, ih_tl]
      simpa using scale_list l
  rcases h_Q with ⟨l, hl⟩
  let qOf : List (FDRep k E × ClassFun.Lambda k G) → ClassFun k E :=
    fun l => (l.map fun P => (P.2 : k) • ClassFun.character P.1).sum
  have H :
      ∀ l,
        ClassFun.HasLambdaCoords B (ClassFun.ind E (qOf l)) ∧
          nuStar B (ClassFun.ind E (qOf l))
            ∈ BrauerSpanChar (k := k) (G := G) := by
    intro l
    induction l with
    | nil =>
        simp only [qOf, List.map_nil, List.sum_nil]
        rw [ClassFun.ind_zero]
        constructor
        · exact ClassFun.HasLambdaCoords.zero B
        · rw [nuStar_zero]
          exact Submodule.zero_mem _
    | cons hd tl ih =>
        simp only [qOf, List.map_cons, List.sum_cons]
        have h_ind_char :
            ClassFun.ind E (ClassFun.character hd.1)
              =
            ClassFun.character (FDRep.ind E hd.1) := by
          exact (ClassFun.char_ind E hd.1).symm
        have h_first_coords :
            ClassFun.HasLambdaCoords B
              (ClassFun.ind E ((hd.2 : k) • ClassFun.character hd.1)) := by
          rw [ClassFun.ind_smul, h_ind_char]
          exact
            ClassFun.HasLambdaCoords.smul B
              hd.2.property
              (ClassFun.HasLambdaCoords.character B (FDRep.ind E hd.1))
        have h_first_mem :
            nuStar B
              (ClassFun.ind E ((hd.2 : k) • ClassFun.character hd.1))
                ∈ BrauerSpanChar (k := k) (G := G) := by
          rw [ClassFun.ind_smul, h_ind_char]
          rw [nuStar_smul_char B hd.2.property (FDRep.ind E hd.1)]
          let z : ℤ :=
            nu k G ⟨(hd.2 : k), hd.2.property⟩
          have hz :
              nuExt (k := k) (G := G) (hd.2 : k) = (z : k) := by
            unfold nuExt
            rw [dif_pos hd.2.property]
          rw [hz, Int.cast_smul_eq_zsmul]
          have h_gen :
              ClassFun.ind E (ClassFun.character hd.1)
                ∈ BrauerSpanChar (k := k) (G := G) := by
            apply Submodule.subset_span
            have hBrauer : IsBrauerElementary E := by
              exact IsBrauerElementary.ofIsPElementary p hE
            exact ⟨E, hBrauer, hd.1, rfl⟩
          rw [h_ind_char] at h_gen
          exact Submodule.smul_mem _ z h_gen
        rw [ClassFun.ind_add]
        constructor
        · exact ClassFun.HasLambdaCoords.add B h_first_coords ih.1
        · rw [nuStar_add B h_first_coords ih.1]
          exact Submodule.add_mem _ h_first_mem ih.2
  have hq_eq : q = qOf l := by
    simpa [qOf] using hl
  rw [hq_eq]
  exact H l

/--
For any fixed irreducible-character basis, `nuStar` sends `jGlobal` into
`BrauerSpanChar`.
-/
lemma nuStar_maps_J_global
    {G : Type u} [Group G] [Fintype G] [_hk : IsAlgClosed k]
    (B : ClassFun.IrrepCharBasis k G)
    {f : ClassFun k G}
    (hf : f ∈ BrauerInduction.jGlobal k G) :
    nuStar B f ∈ BrauerSpanChar (G := G) (k := k) := by
  let P : ClassFun k G → Prop :=
    fun x =>
      ClassFun.HasLambdaCoords B x ∧
        nuStar B x ∈ BrauerSpanChar (G := G) (k := k)
  have h_zero : P 0 := by
    constructor
    · exact ClassFun.HasLambdaCoords.zero B
    · rw [nuStar_zero B]
      exact Submodule.zero_mem _
  have h_add : ∀ x y, P x → P y → P (x + y) := by
    intro x y hx hy
    constructor
    · exact ClassFun.HasLambdaCoords.add B hx.1 hy.1
    · rw [nuStar_add B hx.1 hy.1]
      exact Submodule.add_mem _ hx.2 hy.2
  have H : P f := by
    refine @Submodule.iSup_induction ℤ (ClassFun k G) _ _ _ ℕ
      (fun p => ⨆ (_ : Fact p.Prime), BrauerInduction.J (k := k) (G := G) p)
      P f hf ?prime_case h_zero h_add
    intro p_nat x hx
    refine @Submodule.iSup_induction ℤ (ClassFun k G) _ _ _ (Fact p_nat.Prime)
      (fun _ => BrauerInduction.J (k := k) (G := G) p_nat)
      P x hx ?fact_case h_zero h_add
    intro hp q hq
    refine @Submodule.span_induction ℤ (ClassFun k G) _ _ _ _
      (fun y _ => P y) ?gen ?zero ?add ?zsmul q hq
    · rintro _ ⟨E, hE, q_E, hq_E, rfl⟩
      exact nuStar_projects_E B p_nat E hE q_E hq_E
    · exact h_zero
    · intro q1 q2 _ _ ih1 ih2
      exact h_add q1 q2 ih1 ih2
    · intro z q_base _ ih
      constructor
      · exact ClassFun.HasLambdaCoords.zsmul B z ih.1
      · rw [nuStar_zsmul B z ih.1]
        exact Submodule.smul_mem _ z ih.2
  exact H.2

/--
If `1 ∈ jGlobal`, then `1 ∈ BrauerSpanChar`.

This applies the coefficient projection to the global local-to-global result.
-/
theorem one_mem_BrauerSpanChar_of_one_mem_J_global
    {G : Type u} [Group G] [Fintype G] [IsAlgClosed k]
    (h1 : (1 : ClassFun k G) ∈ BrauerInduction.jGlobal k G) :
    (1 : ClassFun k G) ∈ BrauerSpanChar (G := G) (k := k) := by
  let B := ClassFun.irrepCharBasis (k := k) (G := G)
  rw [← nuStar_one B]
  exact nuStar_maps_J_global (G := G) (k := k) B h1

/--
The constant class function `1` lies in the Brauer-character span.

This is the final projection step in Bernstein's proof.
-/
theorem one_mem_BrauerSpanChar
    {G : Type u} [Group G] [Fintype G] [IsAlgClosed k] :
    (1 : ClassFun k G) ∈ BrauerSpanChar (G := G) (k := k) := by
  exact one_mem_BrauerSpanChar_of_one_mem_J_global
    (BrauerInduction.one_mem_J_global (G := G) (k := k))

end CharacterCoefficientProjection

end BrauerInduction

end Slop
