/-
Copyright (c) 2025 Kevin Buzzard. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kevin Buzzard
-/
module

public import FLT.Data.Hurwitz
public import FLT.Data.QHat
import Mathlib.CategoryTheory.Category.Init
import Mathlib.Tactic.Positivity.Finset

/-!
# Adelic Hurwitz quaternions

Base changes of the Hurwitz integers to `ℚ` and to `ZHat`, providing a
quaternion algebra over the rationals and its profinite completion as
free rank-4 modules over the corresponding base ring.

## Main definitions

* `HurwitzRat`: the rational quaternions `ℚ + ℚi + ℚj + ℚk`.
* `HurwitzHat`: the profinite Hurwitz quaternions, a free rank-4 module
  over `ZHat`.
-/

@[expose] public section

open scoped TensorProduct

/-- The base change of the Hurwitz quaternions to ZHat. -/
noncomputable def HurwitzHat : Type := 𝓞 ⊗[ℤ] ZHat

namespace HurwitzHat

/-- The base change of the Hurwitz quaternions to ZHat. -/
scoped notation "𝓞^" => HurwitzHat

noncomputable instance : Ring 𝓞^ := Algebra.TensorProduct.instRing

end HurwitzHat

/-- The quaternion algebra ℚ + ℚi + ℚj + ℚk. -/
noncomputable def HurwitzRat : Type := ℚ ⊗[ℤ] 𝓞

namespace HurwitzRat

/-- The quaternion algebra ℚ + ℚi + ℚj + ℚk. -/
scoped notation "D" => HurwitzRat

noncomputable instance : Ring D := Algebra.TensorProduct.instRing

end HurwitzRat

open scoped HurwitzRat HurwitzHat

/-- The "profinite Hurwitz quaternions" over the finite adeles of ℚ; a free rank 4 module
generated by 1, i, j, and (1+i+j+k)/2. -/
noncomputable def HurwitzRatHat : Type := D ⊗[ℤ] ZHat

namespace HurwitzRatHat

/-- The "profinite Hurwitz quaternions" over the finite adeles of ℚ; a free rank 4 module
generated by 1, i, j, and (1+i+j+k)/2. -/
scoped notation "D^" => HurwitzRatHat

noncomputable instance : Ring D^ := Algebra.TensorProduct.instRing

/-- The inclusion from D=ℚ+ℚi+ℚj+ℚk to D ⊗ 𝔸, with 𝔸 the finite adeles of ℚ. -/
noncomputable abbrev j₁ : D →ₐ[ℤ] D^ := Algebra.TensorProduct.includeLeft
-- (Algebra.TensorProduct.assoc ℤ ℚ 𝓞 ZHat).symm.trans Algebra.TensorProduct.includeLeft

lemma injective_hRat :
    Function.Injective j₁ := sorry -- flatness

-- this stopped working in 4.29
noncomputable instance : Ring (ℚ ⊗[ℤ] 𝓞^) := Algebra.TensorProduct.instRing

-- this stopped working in 4.29
noncomputable instance : Ring (D ⊗[ℤ] ZHat) := Algebra.TensorProduct.instRing

-- in 4.29 I had to change all three ⊗ in the below to ⊗[ℤ]
/-- The inclusion from the profinite Hurwitz quaternions to to 𝔸+𝔸i+𝔸j+𝔸k,
with 𝔸 the finite adeles of ℚ. -/
noncomputable abbrev j₂ : 𝓞^ →ₐ[ℤ] D^ :=
  ((Algebra.TensorProduct.assoc ℤ ℤ ℤ ℚ 𝓞 ZHat).symm : ℚ ⊗[ℤ] 𝓞^ ≃ₐ[ℤ] D ⊗[ℤ] ZHat).toAlgHom.comp
  (Algebra.TensorProduct.includeRight : 𝓞^ →ₐ[ℤ] ℚ ⊗[ℤ] 𝓞^)

lemma injective_zHat :
    Function.Injective j₂ := sorry -- flatness

/-- Scaling the `𝓞^`-part by `M` cancels the factor `M` in the denominator `N * M`. -/
private lemma j₁_smul_aux (N M : ℕ+) (w : 𝓞^) :
    j₁ ((((N * M : ℕ+) : ℚ)⁻¹) ⊗ₜ 1 : D) * j₂ ((M : ℤ) • w)
      = j₁ (((N : ℚ)⁻¹) ⊗ₜ 1 : D) * j₂ w := by
  have h : ((M : ℤ) • ((((N * M : ℕ+) : ℚ)⁻¹) ⊗ₜ (1 : 𝓞)) : ℚ ⊗[ℤ] 𝓞)
      = (((N : ℚ)⁻¹) ⊗ₜ (1 : 𝓞)) := by
    rw [TensorProduct.smul_tmul', zsmul_eq_mul]
    congr 1
    push_cast
    field_simp
  rw [map_zsmul, mul_smul_comm, ← smul_mul_assoc,
    (map_zsmul j₁ (M : ℤ) _).symm.trans (congrArg j₁ h)]

/-- Elements admitting a canonical form are closed under addition: put the two over the
common denominator `N₁ * N₂`. -/
private lemma canonicalForm_add {z₁ z₂ : D^}
    (h₁ : ∃ (N : ℕ+) (z' : 𝓞^), z₁ = j₁ ((N⁻¹ : ℚ) ⊗ₜ 1 : D) * j₂ z')
    (h₂ : ∃ (N : ℕ+) (z' : 𝓞^), z₂ = j₁ ((N⁻¹ : ℚ) ⊗ₜ 1 : D) * j₂ z') :
    ∃ (N : ℕ+) (z' : 𝓞^), z₁ + z₂ = j₁ ((N⁻¹ : ℚ) ⊗ₜ 1 : D) * j₂ z' := by
  obtain ⟨N₁, w₁, rfl⟩ := h₁
  obtain ⟨N₂, w₂, rfl⟩ := h₂
  refine ⟨N₁ * N₂, (N₂ : ℤ) • w₁ + (N₁ : ℤ) • w₂, ?_⟩
  rw [map_add, mul_add, j₁_smul_aux, mul_comm N₁ N₂, j₁_smul_aux]

-- should I rearrange tensors? Not sure if D^ should be (ℚ ⊗ 𝓞) ⊗ ℤhat or ℚ ⊗ (𝓞 ⊗ Zhat)
lemma canonicalForm (z : D^) : ∃ (N : ℕ+) (z' : 𝓞^), z = j₁ ((N⁻¹ : ℚ) ⊗ₜ 1 : D) * j₂ z' := by
  induction z using TensorProduct.induction_on with
  | zero =>
    refine ⟨1, 0, ?_⟩
    rw [map_zero, mul_zero]
    rfl
  | tmul d x =>
    induction d using TensorProduct.induction_on with
    | zero =>
      refine ⟨1, 0, ?_⟩
      rw [map_zero, mul_zero]
      exact TensorProduct.zero_tmul D x
    | tmul q o =>
      refine ⟨⟨q.den, q.den_pos⟩, (q.num • o) ⊗ₜ x, ?_⟩
      change _ = ((((q.den : ℚ))⁻¹ ⊗ₜ[ℤ] (1 : 𝓞)) ⊗ₜ[ℤ] (1 : ZHat)) *
        (((1 : ℚ) ⊗ₜ[ℤ] (q.num • o)) ⊗ₜ[ℤ] x)
      rw [Algebra.TensorProduct.tmul_mul_tmul, Algebra.TensorProduct.tmul_mul_tmul,
        mul_one, one_mul, one_mul, TensorProduct.tmul_smul, TensorProduct.smul_tmul']
      congr 1
      rw [zsmul_eq_mul, ← div_eq_mul_inv, Rat.num_div_den]
    | add d₁ d₂ hd₁ hd₂ =>
      obtain ⟨N, w, hw⟩ := canonicalForm_add hd₁ hd₂
      exact ⟨N, w, (TensorProduct.add_tmul d₁ d₂ x).trans hw⟩
  | add z₁ z₂ h₁ h₂ => exact canonicalForm_add h₁ h₂

lemma completed_units (z : D^ˣ) : ∃ (u : Dˣ) (v : 𝓞^ˣ), (z : D^) = j₁ u * j₂ v := sorry

end HurwitzRatHat
