/-
# Irreducible ↔ absolutely irreducible, given a 1-dimensional fixed space

This file states (with `sorry`ed proofs) Proposition 1.2 / Theorem 1.3 of the
blueprint "Odd_Rep_Irreducible" (July 6, 2026), together with all the
supporting lemmas from the blueprint:

* `OddRep.exists_smul_eq_of_commute`        — Lemma 1.4  (`End_G(V) = k`)
* `OddRep.adjoinRange_eq_top`               — Lemma 1.5  (Jacobson density: `A = End_k(V)`)
* `OddRep.adjoinRange_baseChange_eq_top`    — Lemma 1.6  (base change of `A = End_k(V)`)
* `OddRep.smul_tmul_mem_range_iff`          — Fact 1.1   (`l·e ∩ V = k·e` inside `V_l`)
* `OddRep.isIrreducible_of_adjoinRange_eq_top` — step (iv) of the blueprint
* `OddRep.isIrreducible_of_baseChange`      — descent of irreducibility (easy direction)
* `OddRep.isIrreducible_iff_isAbsolutelyIrreducible` — Proposition 1.2 / Theorem 1.3

Conventions:
* Representations are `Representation k G V := G →* (V →ₗ[k] V)` as in Mathlib.
* Irreducibility is Mathlib's `Representation.IsIrreducible`, defined as
  `IsSimpleOrder (Subrepresentation ρ)`.  The notion of a "`G`-invariant
  subspace" is Mathlib's `Subrepresentation` structure: a `Submodule` together
  with the invariance field `apply_mem_toSubmodule : ρ g v ∈ toSubmodule` for
  `v ∈ toSubmodule`.  The lemma `OddRep.isIrreducible_iff_forall` unpacks
  `Representation.IsIrreducible` into the elementary statement "`V ≠ 0` and every
  invariant subspace is `⊥` or `⊤`", which is what most proofs below use.
* "Absolutely irreducible" is defined here as: the base change to
  `AlgebraicClosure k` is irreducible.  (The blueprint's proof in fact shows
  irreducibility after base change to *any* field extension `l/k`; this is
  recorded separately as
  `OddRep.isIrreducible_baseChange_of_finrank_fixedSpace_eq_one`.)
-/

module

import Mathlib

open scoped TensorProduct

open Module

namespace OddRep

variable {k : Type*} [Field k]
variable {G : Type*} [Monoid G]
variable {V : Type*} [AddCommGroup V] [Module k V]

/-! ## Definitions -/

/-- The fixed subspace `V^g = {v : ρ(g) v = v}` of a single group element. -/
def fixedSpace (ρ : Representation k G V) (g : G) : Submodule k V :=
  LinearMap.ker (ρ g - LinearMap.id)

/-- Base change of a representation along a field extension `l/k`:
`G` acts on `l ⊗[k] V` by `1 ⊗ ρ(g)`. -/
noncomputable def baseChange (l : Type*) [Field l] [Algebra k l]
    (ρ : Representation k G V) : Representation l G (l ⊗[k] V) where
  toFun g := (ρ g).baseChange l
  map_one' := by
    change (ρ 1).baseChange l = 1
    have h1 : ρ 1 = LinearMap.id := by rw [map_one]; rfl
    rw [h1, LinearMap.baseChange_id]
    rfl
  map_mul' := fun g h => by
    change (ρ (g * h)).baseChange l = (ρ g).baseChange l * (ρ h).baseChange l
    have h1 : ρ (g * h) = (ρ g).comp (ρ h) := by rw [map_mul]; rfl
    rw [h1, LinearMap.baseChange_comp]
    rfl

/-- The `k`-subalgebra `A ⊆ End_k(V)` generated by the image of `ρ`. -/
def adjoinRange (ρ : Representation k G V) : Subalgebra k (Module.End k V) :=
  Algebra.adjoin k (Set.range ρ)

/-- A representation is absolutely irreducible if it remains irreducible after
base change to an algebraic closure of `k`. -/
def IsAbsolutelyIrreducible (ρ : Representation k G V) : Prop :=
  (baseChange (AlgebraicClosure k) ρ).IsIrreducible

variable (ρ : Representation k G V)

/-! ## Unpacking Mathlib's `Representation.IsIrreducible`

`Representation.IsIrreducible ρ` is by definition `IsSimpleOrder (Subrepresentation ρ)`.
The following lemma re-expresses it as the elementary statement that `V ≠ 0` and
every `G`-invariant subspace of `V` is either `⊥` or `⊤`, where invariance is
`∀ g, ∀ v ∈ W, ρ g v ∈ W` (the defining condition of a `Subrepresentation`). -/
lemma isIrreducible_iff_forall :
    ρ.IsIrreducible ↔
      Nontrivial V ∧
        ∀ W : Submodule k V, (∀ g : G, ∀ v ∈ W, ρ g v ∈ W) → W = ⊥ ∨ W = ⊤ := by
  constructor
  · intro hirr
    haveI := hirr
    refine ⟨?_, ?_⟩
    · -- `V` is nontrivial because `⊥ ≠ ⊤` in the (simple) lattice of subrepresentations.
      exact (Submodule.nontrivial_iff k).mp
        (nontrivial_of_ne (⊥ : Submodule k V) ⊤
          (fun e => IsSimpleOrder.bot_ne_top (α := Subrepresentation ρ)
            (Subrepresentation.toSubmodule_injective
              (show (⊥ : Subrepresentation ρ).toSubmodule = (⊤ : Subrepresentation ρ).toSubmodule
                from e))))
    · -- An invariant subspace `W` is a subrepresentation, hence `⊥` or `⊤`.
      intro W hW
      rcases eq_bot_or_eq_top (⟨W, fun g v hv => hW g v hv⟩ : Subrepresentation ρ) with hb | ht
      · exact Or.inl (congrArg Subrepresentation.toSubmodule hb)
      · exact Or.inr (congrArg Subrepresentation.toSubmodule ht)
  · rintro ⟨hnt, hforall⟩
    haveI : Nontrivial V := hnt
    haveI : Nontrivial (Submodule k V) := (Submodule.nontrivial_iff k).mpr hnt
    refine
      { toNontrivial := ⟨⊥, ⊤, ?_⟩
        eq_bot_or_eq_top := ?_ }
    · -- `⊥ ≠ ⊤` as subrepresentations, since the underlying submodules differ.
      exact fun e => bot_ne_top (α := Submodule k V) (congrArg Subrepresentation.toSubmodule e)
    · -- Every subrepresentation `s` has invariant underlying submodule, so it is `⊥` or `⊤`.
      intro s
      rcases hforall s.toSubmodule (fun g v hv => s.apply_mem_toSubmodule g hv) with hb | ht
      · exact Or.inl (Subrepresentation.toSubmodule_injective hb)
      · exact Or.inr (Subrepresentation.toSubmodule_injective ht)

/-! ## Fact 1.1 : `l·e ∩ V = k·e` inside `V_l` -/

/-- **Fact 1.1.** If `e ≠ 0` in `V`, then for `c : l`, the element `c ⊗ e` of
`l ⊗[k] V` lies in the image of the canonical map `V → l ⊗[k] V`, `v ↦ 1 ⊗ v`,
if and only if `c` comes from `k`. -/
lemma smul_tmul_mem_range_iff (l : Type*) [Field l] [Algebra k l]
    {e : V} (he : e ≠ 0) (c : l) :
    c ⊗ₜ[k] e ∈ LinearMap.range (TensorProduct.mk k l V 1) ↔
      ∃ a : k, algebraMap k l a = c := by
  constructor
  · -- Forward: if `c ⊗ₜ e = 1 ⊗ₜ w`, apply `id ⊗ φ` for a functional `φ` with `φ e = 1`.
    rintro ⟨w, hw⟩
    -- `hw : 1 ⊗ₜ w = c ⊗ₜ e`
    obtain ⟨φ, hφ⟩ := Module.Projective.exists_dual_eq_one k he
    -- `ψ : l ⊗[k] V → l`, `x ⊗ₜ v ↦ φ v • x`.
    set ψ : l ⊗[k] V →ₗ[k] l :=
      (TensorProduct.rid k l).toLinearMap ∘ₗ LinearMap.lTensor l φ with hψ
    refine ⟨φ w, ?_⟩
    have key := congrArg ψ hw
    simp only [hψ, LinearMap.coe_comp, Function.comp_apply, TensorProduct.mk_apply,
      LinearMap.lTensor_tmul, LinearEquiv.coe_coe, TensorProduct.rid_tmul] at key
    -- `key : φ w • (1 : l) = φ e • c`
    rw [hφ, one_smul] at key
    rw [Algebra.algebraMap_eq_smul_one]
    exact key
  · -- Reverse: `algebraMap k l a ⊗ₜ e = 1 ⊗ₜ (a • e)`.
    rintro ⟨a, rfl⟩
    refine ⟨a • e, ?_⟩
    rw [TensorProduct.mk_apply, TensorProduct.tmul_smul, TensorProduct.smul_tmul',
      Algebra.algebraMap_eq_smul_one]

/-! ## Lemma 1.4 : `End_G(V) = k` -/

/-- **Lemma 1.4.** If `ρ` is irreducible and some `g : G` has a one-dimensional
fixed subspace, then every `G`-equivariant endomorphism of `V` is scalar. -/
lemma exists_smul_eq_of_commute
    (hirr : ρ.IsIrreducible)
    {g : G} (hg : finrank k (fixedSpace ρ g) = 1)
    (T : Module.End k V) (hT : ∀ h : G, Commute (ρ h) T) :
    ∃ μ : k, T = μ • (1 : Module.End k V) := by
  obtain ⟨-, hsub⟩ := (isIrreducible_iff_forall ρ).mp hirr
  -- Membership in the fixed space, in applied form.
  have hfix : ∀ v : V, v ∈ fixedSpace ρ g ↔ ρ g v = v := fun v => by
    simp [fixedSpace, LinearMap.mem_ker, LinearMap.sub_apply, LinearMap.id_apply,
      sub_eq_zero]
  -- `T` preserves the fixed space, because it commutes with `ρ g`.
  have hTfix : ∀ v ∈ fixedSpace ρ g, T v ∈ fixedSpace ρ g := by
    intro v hv
    rw [hfix] at hv ⊢
    have hc := LinearMap.congr_fun (hT g) v
    simp only [Module.End.mul_apply] at hc
    -- hc : ρ g (T v) = T (ρ g v)
    rw [hc, hv]
  -- Pick a nonzero vector spanning the one-dimensional fixed space.
  rw [finrank_eq_one_iff'] at hg
  obtain ⟨v, hv0, hspan⟩ := hg
  have hv0' : (v : V) ≠ 0 := fun h => hv0 (Subtype.ext h)
  -- `T v` lies in the fixed space, hence is a multiple `μ • v` of `v`.
  obtain ⟨μ, hμ⟩ := hspan ⟨T (v : V), hTfix (v : V) v.2⟩
  have hμ' : μ • (v : V) = T (v : V) := by
    have h1 := congrArg Subtype.val hμ
    simpa using h1
  refine ⟨μ, ?_⟩
  -- The kernel of `T - μ` is `G`-invariant ...
  have hKinv : ∀ h : G, ∀ w ∈ LinearMap.ker (T - μ • (1 : Module.End k V)),
      ρ h w ∈ LinearMap.ker (T - μ • (1 : Module.End k V)) := by
    intro h w hw
    rw [LinearMap.mem_ker] at hw ⊢
    have hc := LinearMap.congr_fun (hT h) w
    simp only [Module.End.mul_apply] at hc
    -- hc : ρ h (T w) = T (ρ h w)
    simp only [LinearMap.sub_apply, LinearMap.smul_apply, Module.End.one_apply] at hw ⊢
    -- hw : T w - μ • w = 0 ; goal : T (ρ h w) - μ • ρ h w = 0
    rw [← hc, ← map_smul, ← map_sub, hw, map_zero]
  -- ... and contains the nonzero vector `v`, hence equals `⊤` by irreducibility.
  have hvK : (v : V) ∈ LinearMap.ker (T - μ • (1 : Module.End k V)) := by
    rw [LinearMap.mem_ker]
    simp only [LinearMap.sub_apply, LinearMap.smul_apply, Module.End.one_apply]
    rw [← hμ']
    exact sub_self _
  rcases hsub _ hKinv with hbot | htop
  · exfalso
    rw [hbot] at hvK
    exact hv0' (by simpa using hvK)
  · -- the kernel is everything, so `T = μ • 1`
    refine LinearMap.ext fun w => ?_
    have hw : w ∈ LinearMap.ker (T - μ • (1 : Module.End k V)) := by
      rw [htop]; exact Submodule.mem_top
    rw [LinearMap.mem_ker] at hw
    simp only [LinearMap.sub_apply, LinearMap.smul_apply, Module.End.one_apply] at hw
    simpa [sub_eq_zero] using hw

/-! ## Lemma 1.5 : Jacobson density, `A = End_k(V)` -/

/-- **Lemma 1.5.** Let `A ⊆ End_k(V)` be the `k`-algebra generated by `ρ(G)`.
If `V` is finite-dimensional, `ρ` is irreducible, and every `G`-equivariant
endomorphism of `V` is scalar, then `A = End_k(V)`. -/
lemma adjoinRange_eq_top [FiniteDimensional k V]
    (hirr : ρ.IsIrreducible)
    (hEnd : ∀ T : Module.End k V, (∀ h : G, Commute (ρ h) T) →
      ∃ μ : k, T = μ • (1 : Module.End k V)) :
    adjoinRange ρ = ⊤ := by
  obtain ⟨hnt, hsub⟩ := (isIrreducible_iff_forall ρ).mp hirr
  haveI : Nontrivial V := hnt
  set A := adjoinRange ρ
  have hρmem : ∀ g : G, ρ g ∈ A := fun g => Algebra.subset_adjoin ⟨g, rfl⟩
  haveI : IsScalarTower k A V := ⟨fun _ _ _ => rfl⟩
  -- `V` is a simple (hence semisimple) `A`-module: an `A`-submodule is a
  -- `G`-invariant `k`-subspace, so irreducibility applies.
  haveI : IsSimpleModule A V := by
    haveI := (Submodule.nontrivial_iff A).mpr ‹Nontrivial V›
    rw [isSimpleModule_iff]
    refine ⟨fun W => ?_⟩
    have hW : ∀ g : G, ∀ v ∈ W.restrictScalars k, ρ g v ∈ W.restrictScalars k :=
      fun g v hv => W.smul_mem ⟨ρ g, hρmem g⟩ hv
    simpa only [Submodule.restrictScalars_eq_bot_iff, Submodule.restrictScalars_eq_top_iff]
      using hsub _ hW
  -- Every `A`-linear endomorphism of `V` is a `k`-scalar (uses `hEnd`).
  have hEnd' : ∀ f : Module.End A V, ∃ μ : k, ∀ v : V, f v = μ • v := by
    intro f
    let fk : Module.End k V :=
      { toFun := f, map_add' := f.map_add
        map_smul' := fun μ v => by
          have h := f.map_smul (algebraMap k A μ) v
          rw [algebraMap_smul, algebraMap_smul] at h
          exact h }
    have hcomm : ∀ h : G, Commute (ρ h) fk := fun h =>
      LinearMap.ext fun v => (f.map_smul (⟨ρ h, hρmem h⟩ : A) v).symm
    obtain ⟨μ, hμ⟩ := hEnd fk hcomm
    refine ⟨μ, fun v => ?_⟩
    change fk v = μ • v
    have h := LinearMap.congr_fun hμ v
    rw [LinearMap.smul_apply, Module.End.one_apply] at h
    exact h
  -- Jacobson density on a finite `k`-spanning set of `V`.
  obtain ⟨s, hs⟩ := Module.Finite.fg_top (R := k) (M := V)
  rw [eq_top_iff]
  rintro T -
  let T' : Module.End (Module.End A V) V :=
    { toFun := T, map_add' := T.map_add
      map_smul' := fun g v => by
        obtain ⟨μ, hμ⟩ := hEnd' g
        change T (g v) = g (T v)
        rw [hμ, hμ, T.map_smul] }
  obtain ⟨a, ha⟩ := jacobson_density T' s
  have haT : T = (a : Module.End k V) := LinearMap.ext_on hs fun x hx => ha x hx
  exact haT ▸ a.2

/-! ## Lemma 1.6 : base change of `A = End_k(V)` -/

/-- **Lemma 1.6.** If the `k`-algebra generated by `ρ(G)` is all of `End_k(V)`,
then after base change along any field extension `l/k`, the `l`-algebra
generated by `(ρ.baseChange l)(G)` is all of `End_l(l ⊗[k] V)`. -/
lemma adjoinRange_baseChange_eq_top [FiniteDimensional k V]
    (l : Type*) [Field l] [Algebra k l]
    (h : adjoinRange ρ = ⊤) :
    adjoinRange (baseChange l ρ) = ⊤ := by
  classical
  -- `E : End_k V →ₐ[k] End_l (l ⊗ V)`, `T ↦ T.baseChange l` (base change of endomorphisms).
  set E : Module.End k V →ₐ[k] Module.End l (l ⊗[k] V) :=
    Module.End.baseChangeHom k l V with hE
  have hEapp : ∀ T : Module.End k V, E T = LinearMap.baseChange l T := fun T => rfl
  -- The generators base change correctly: `(baseChange l ρ) g = E (ρ g)`.
  have hgen : ∀ g : G, baseChange l ρ g = E (ρ g) := fun g => by rw [hEapp]; rfl
  -- Step 1 : since `A = End_k V = ⊤`, every `E T` lies in `B := adjoinRange (baseChange l ρ)`.
  have hrange : ∀ T : Module.End k V, E T ∈ adjoinRange (baseChange l ρ) := by
    have hmap : (adjoinRange ρ).map E ≤
        Subalgebra.restrictScalars k (adjoinRange (baseChange l ρ)) := by
      rw [adjoinRange, ← Algebra.adjoin_image]
      apply Algebra.adjoin_le
      rintro _ ⟨_, ⟨g, rfl⟩, rfl⟩
      simp only [SetLike.mem_coe, Subalgebra.mem_restrictScalars]
      rw [← hgen g]
      exact Algebra.subset_adjoin (Set.mem_range_self g)
    intro T
    have hTmem : E T ∈ (adjoinRange ρ).map E :=
      Subalgebra.mem_map.mpr ⟨T, by rw [h]; exact Algebra.mem_top, rfl⟩
    have := hmap hTmem
    rwa [Subalgebra.mem_restrictScalars] at this
  -- Step 2 : the images `E (b.end ij)` of the matrix-unit basis of `End_k V` are a basis of
  -- `End_l (l ⊗ V)`, so `E` has `l`-dense image; combined with Step 1 this forces `B = ⊤`.
  set ι := Module.Free.ChooseBasisIndex k V with hι
  set b : Basis ι k V := Module.Free.chooseBasis k V with hb
  set bl : Basis ι l (l ⊗[k] V) := Algebra.TensorProduct.basis l b with hbl
  have hsub : Set.range ⇑bl.end ⊆ Set.range ⇑E := by
    rintro _ ⟨ij, rfl⟩
    exact ⟨b.end ij, by rw [hEapp]; exact b.baseChange_end (A := l) ij⟩
  have hspan : Submodule.span l (Set.range ⇑E) = ⊤ := by
    rw [eq_top_iff, ← bl.end.span_eq]
    exact Submodule.span_mono hsub
  -- Conclude.
  rw [eq_top_iff]
  intro x _
  have hxspan : x ∈ Submodule.span l (Set.range ⇑E) := by rw [hspan]; exact Submodule.mem_top
  have hle : Submodule.span l (Set.range ⇑E) ≤
      Subalgebra.toSubmodule (adjoinRange (baseChange l ρ)) := by
    rw [Submodule.span_le]
    rintro _ ⟨T, rfl⟩
    exact hrange T
  exact hle hxspan

/-! ## Step (iv) : fullness of `A` implies irreducibility -/

/-- If the algebra generated by `ρ(G)` is all of `End_k(V)` (and `V ≠ 0`), then
`ρ` is irreducible: any nonzero invariant subspace `W` contains, for `0 ≠ w ∈ W`
and any `v`, an element `T w = v` with `T ∈ A`, hence `W = ⊤`. -/
lemma isIrreducible_of_adjoinRange_eq_top [Nontrivial V]
    (h : adjoinRange ρ = ⊤) :
    ρ.IsIrreducible := by
  refine (isIrreducible_iff_forall ρ).mpr ⟨inferInstance, fun W hW => ?_⟩
  -- `W` is stable under the whole algebra generated by `ρ(G)` ...
  have hWA : ∀ T : Module.End k V, T ∈ adjoinRange ρ → ∀ w ∈ W, T w ∈ W := by
    intro T hT
    have hT' : T ∈ Algebra.adjoin k (Set.range ⇑ρ) := hT
    clear hT
    induction hT' using Algebra.adjoin_induction with
    | mem x hx =>
        obtain ⟨g, rfl⟩ := hx
        exact hW g
    | algebraMap r =>
        intro w hw
        have h1 : (algebraMap k (Module.End k V) r) w = r • w := by
          simp [Module.algebraMap_end_apply]
        rw [h1]
        exact W.smul_mem r hw
    | add x y _ _ ihx ihy =>
        intro w hw
        rw [LinearMap.add_apply]
        exact W.add_mem (ihx w hw) (ihy w hw)
    | mul x y _ _ ihx ihy =>
        intro w hw
        rw [Module.End.mul_apply]
        exact ihx _ (ihy w hw)
  -- ... hence under every endomorphism of `V`, since the algebra is everything.
  have hWall : ∀ T : Module.End k V, ∀ w ∈ W, T w ∈ W := fun T =>
    hWA T (by rw [h]; exact Algebra.mem_top)
  rcases eq_or_ne W ⊥ with hbot | hne
  · exact Or.inl hbot
  · right
    obtain ⟨w, hwW, hw0⟩ := (Submodule.ne_bot_iff W).mp hne
    rw [Submodule.eq_top_iff']
    intro v
    -- Choose a linear functional not vanishing on `w`.
    obtain ⟨φ, hφ0⟩ : ∃ φ : Module.Dual k V, φ w ≠ 0 := by
      by_contra hall
      push Not at hall
      apply hw0
      rw [← Module.forall_dual_apply_eq_zero_iff k]
      exact hall
    -- The endomorphism `x ↦ ((φ w)⁻¹ * φ x) • v` maps `w` to `v`, and it
    -- preserves `W`, so `v ∈ W`.
    have hTw : (((φ w)⁻¹ • φ).smulRight v) w = v := by
      simp [LinearMap.smulRight_apply, LinearMap.smul_apply, smul_eq_mul,
        inv_mul_cancel₀ hφ0]
    have h2 := hWall (((φ w)⁻¹ • φ).smulRight v) w hwW
    rwa [hTw] at h2

/-! ## Descent of irreducibility (the easy direction) -/

/-- If the base change of `ρ` along some field extension `l/k` is irreducible,
then `ρ` itself is irreducible (an invariant subspace `W ⊊ V` gives rise to the
invariant subspace `l ⊗[k] W ⊊ l ⊗[k] V`). -/
lemma isIrreducible_of_baseChange (l : Type*) [Field l] [Algebra k l]
    (h : (baseChange l ρ).IsIrreducible) :
    ρ.IsIrreducible := by
  obtain ⟨hntl, hsubl⟩ := (isIrreducible_iff_forall (baseChange l ρ)).mp h
  refine (isIrreducible_iff_forall ρ).mpr ⟨?_, ?_⟩
  · -- `Nontrivial V` : otherwise `l ⊗[k] V` would be trivial, contradicting `hntl`.
    by_contra hV
    rw [not_nontrivial_iff_subsingleton] at hV
    haveI : Subsingleton V := hV
    haveI : Subsingleton (l ⊗[k] V) := by
      refine ⟨fun a b => ?_⟩
      have hz : ∀ x : l ⊗[k] V, x = 0 := fun x => by
        induction x using TensorProduct.induction_on with
        | zero => rfl
        | tmul a v => rw [Subsingleton.elim v (0 : V), TensorProduct.tmul_zero]
        | add a b ha hb => rw [ha, hb, add_zero]
      rw [hz a, hz b]
    exact not_nontrivial_iff_subsingleton.mpr inferInstance hntl
  · -- Any invariant `W` gives an invariant `l ⊗[k] W`, which is `⊥`/`⊤` by `hsubl`; descend.
    intro W hW
    have hinv : ∀ g : G, ∀ x ∈ W.baseChange l, (baseChange l ρ) g x ∈ W.baseChange l := by
      intro g x hx
      change LinearMap.baseChange l (ρ g) x ∈ W.baseChange l
      rw [Submodule.baseChange_eq_span] at hx
      induction hx using Submodule.span_induction with
      | mem y hy =>
        obtain ⟨w, hw, rfl⟩ := hy
        simp only [TensorProduct.mk_apply, LinearMap.baseChange_tmul]
        exact Submodule.tmul_mem_baseChange_of_mem 1 (hW g w hw)
      | zero => rw [map_zero]; exact Submodule.zero_mem _
      | add a b _ _ ha hb => rw [map_add]; exact Submodule.add_mem _ ha hb
      | smul c a _ ha => rw [map_smul]; exact Submodule.smul_mem _ c ha
    rcases hsubl (W.baseChange l) hinv with hb | ht
    · exact Or.inl <| Submodule.baseChange_injective (A := l)
        (hb.trans (Submodule.baseChange_bot (R := k) (M := V) (A := l)).symm)
    · exact Or.inr <| Submodule.baseChange_injective (A := l)
        (ht.trans (Submodule.baseChange_top (R := k) (M := V) (A := l)).symm)

/-! ## Main results -/

/-- The quantitative version of the hard direction: under the hypotheses of
Theorem 1.3, the base change of `ρ` to *any* field extension `l/k` is
irreducible. -/
theorem isIrreducible_baseChange_of_finrank_fixedSpace_eq_one
    [FiniteDimensional k V]
    (l : Type*) [Field l] [Algebra k l]
    (hirr : ρ.IsIrreducible)
    {g : G} (hg : finrank k (fixedSpace ρ g) = 1) :
    (baseChange l ρ).IsIrreducible := by
  -- Lemma 1.4 : every `G`-equivariant endomorphism of `V` is a scalar.
  have hEnd : ∀ T : Module.End k V, (∀ h : G, Commute (ρ h) T) →
      ∃ μ : k, T = μ • (1 : Module.End k V) :=
    fun T hT => exists_smul_eq_of_commute ρ hirr hg T hT
  -- Lemma 1.5 : the `k`-algebra generated by `ρ(G)` is all of `End_k V`.
  have hA : adjoinRange ρ = ⊤ := adjoinRange_eq_top ρ hirr hEnd
  -- Lemma 1.6 : this stays true after base change to `l`.
  have hAbc : adjoinRange (baseChange l ρ) = ⊤ := adjoinRange_baseChange_eq_top ρ l hA
  -- `l ⊗[k] V` is nontrivial : a nonzero `v ∈ V` gives a nonzero `1 ⊗ v`.
  haveI : Nontrivial V := ((isIrreducible_iff_forall ρ).mp hirr).1
  obtain ⟨v, hv0⟩ := exists_ne (0 : V)
  obtain ⟨φ, hφ⟩ := Module.Projective.exists_dual_eq_one k hv0
  have hne : (1 : l) ⊗ₜ[k] v ≠ 0 := by
    intro hzero
    have hcontra := congrArg
      (fun t => (TensorProduct.rid k l).toLinearMap (LinearMap.lTensor l φ t)) hzero
    simp only [LinearMap.lTensor_tmul, LinearEquiv.coe_coe, TensorProduct.rid_tmul, hφ,
      one_smul, map_zero] at hcontra
    exact one_ne_zero hcontra
  haveI : Nontrivial (l ⊗[k] V) := nontrivial_of_ne _ _ hne
  -- Step (iv) : fullness of the algebra forces irreducibility.
  exact isIrreducible_of_adjoinRange_eq_top (baseChange l ρ) hAbc

/-- **Proposition 1.2 / Theorem 1.3.** Let `V` be a finite-dimensional vector
space over `k` and `ρ : G →* GL(V)` a representation.  If some `g : G` has a
one-dimensional fixed subspace `V^g`, then `V` is irreducible if and only if it
is absolutely irreducible. -/
theorem isIrreducible_iff_isAbsolutelyIrreducible_slop
    [FiniteDimensional k V]
    {g : G} (hg : finrank k (fixedSpace ρ g) = 1) :
    ρ.IsIrreducible ↔ IsAbsolutelyIrreducible ρ := by
  unfold IsAbsolutelyIrreducible
  constructor
  · -- hard direction: irreducible ⇒ irreducible after base change to `k̄`
    intro hirr
    exact isIrreducible_baseChange_of_finrank_fixedSpace_eq_one ρ
      (AlgebraicClosure k) hirr hg
  · -- easy direction: irreducibility descends along `k → k̄`
    intro habs
    exact isIrreducible_of_baseChange ρ (AlgebraicClosure k) habs

end OddRep
