/-
Copyright (c) 2026 Kevin Buzzard. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Michael Stoll
-/
module

public import Mathlib.RingTheory.AdjoinRoot
public import Mathlib.Algebra.Polynomial.Eval.Irreducible
public import Mathlib.RingTheory.Polynomial.GaussLemma
public import Mathlib.RingTheory.DiscreteValuationRing.TFAE
public import Mathlib.RingTheory.LocalRing.ResidueField.Basic
public import Mathlib.FieldTheory.PrimitiveElement
public import Mathlib.FieldTheory.SeparableDegree
public import Mathlib.LinearAlgebra.Dimension.StrongRankCondition
public import Mathlib.Algebra.QuadraticDiscriminant

/-!
# Unramified quadratic extensions of a discrete valuation ring

A separable quadratic extension `k'` of the residue field `k` of a discrete valuation ring `R`
(with fraction field `K`) lifts to an *unramified* quadratic extension `L/K`: writing `k'` as
`k[X]/(p̄)` for a monic separable irreducible quadratic `p̄`, we lift `p̄` to a monic `P ∈ R[X]` and
set `L = K[X]/(P)`. The integral extension `S = R[X]/(P)` is again a discrete valuation ring, with
`S/πS ≅ k[X]/(p̄) = k'` — so its maximal ideal is generated by a uniformizer `π` of `R`
(ramification index `1`) and its residue field is `k'`.

## Main statement

* `exists_unramified_quadraticExtension_of_residueField`

This is the local-field input to
`WeierstrassCurve.exists_quadraticTwist_hasSplitMultiplicativeReduction`.
-/

@[expose] public section

universe u

open IsLocalRing Polynomial IntermediateField

namespace Polynomial

/-- A polynomial of degree at most two is `C (coeff 2) · X² + C (coeff 1) · X + C (coeff 0)`. -/
theorem eq_quadratic_of_natDegree_le_two {R : Type*} [Semiring R] {p : R[X]}
    (h : p.natDegree ≤ 2) :
    p = C (p.coeff 2) * X ^ 2 + C (p.coeff 1) * X + C (p.coeff 0) := by
  conv_lhs => rw [p.as_sum_range' 3 (by omega)]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, zero_add,
    ← C_mul_X_pow_eq_monomial, pow_zero, mul_one, pow_one]
  abel

/-- A quadratic polynomial `a X² + b X + c` (with `a ≠ 0`) over a field is separable exactly when
its discriminant `b² - 4 a c` is nonzero. The `←` direction holds in every characteristic and is a
Bézout identity: `(P')² - 4 a · P = C (b² - 4 a c)`, so a nonzero (hence invertible) discriminant
exhibits `P` and `P'` as coprime. The `→` direction argues that if the discriminant vanishes then
`P ∣ (P')²`, forcing the coprimality witness `P` to be a unit, contradicting `deg P = 2`. -/
theorem separable_quadratic_iff {k : Type*} [Field k] {a b c : k} (ha : a ≠ 0) :
    (C a * X ^ 2 + C b * X + C c).Separable ↔ b ^ 2 - 4 * a * c ≠ 0 := by
  set P := C a * X ^ 2 + C b * X + C c with hP
  have hDexp : derivative P = 2 * C a * X + C b := by
    rw [hP]
    simp only [derivative_add, derivative_mul, derivative_C, derivative_X_pow, derivative_X,
      zero_mul, zero_add, add_zero, mul_one, Nat.cast_ofNat, map_ofNat]
    ring
  have hid : (derivative P) ^ 2 - 4 * C a * P = C (b ^ 2 - 4 * a * c) := by
    rw [hDexp, hP]
    simp only [map_sub, map_mul, map_pow, map_ofNat]
    ring
  constructor
  · intro hsep hdisc
    rw [hdisc, map_zero] at hid
    have hdvd : P ∣ (derivative P) ^ 2 := ⟨4 * C a, by linear_combination hid⟩
    have hunit : IsUnit P :=
      ((separable_def P).mp hsep).pow_right.isUnit_of_dvd' dvd_rfl hdvd
    exact not_isUnit_of_natDegree_pos P (by rw [hP, natDegree_quadratic ha]; norm_num) hunit
  · intro hdisc
    rw [separable_def]
    have hdinv : C (b ^ 2 - 4 * a * c)⁻¹ * C (b ^ 2 - 4 * a * c) = 1 := by
      rw [← C_mul, inv_mul_cancel₀ hdisc, C_1]
    refine ⟨-(C (b ^ 2 - 4 * a * c)⁻¹ * 4 * C a),
      C (b ^ 2 - 4 * a * c)⁻¹ * derivative P, ?_⟩
    linear_combination C (b ^ 2 - 4 * a * c)⁻¹ * hid + hdinv

/-- A quadratic `a X² + b X + c` (`a ≠ 0`) over a field splits exactly when it has a root: a root
splits off a linear factor, leaving a linear cofactor which also splits. This is the
characteristic-free core of the split criterion. -/
theorem splits_quadratic_iff_exists_root {k : Type*} [Field k] {a b c : k} (ha : a ≠ 0) :
    (C a * X ^ 2 + C b * X + C c).Splits ↔ ∃ x, a * x ^ 2 + b * x + c = 0 := by
  set p := C a * X ^ 2 + C b * X + C c with hp
  have hdeg : p.natDegree = 2 := natDegree_quadratic ha
  have hp0 : p ≠ 0 := fun h => by rw [h, natDegree_zero] at hdeg; exact two_ne_zero hdeg.symm
  constructor
  · intro hs
    obtain ⟨x, hx⟩ := hs.exists_eval_eq_zero (by simp [degree_eq_natDegree hp0, hdeg])
    rw [hp] at hx
    simp only [eval_add, eval_mul, eval_C, eval_pow, eval_X] at hx
    exact ⟨x, hx⟩
  · rintro ⟨x, hx⟩
    have hroot : p.IsRoot x := by
      rw [hp, IsRoot]
      simp only [eval_add, eval_mul, eval_C, eval_pow, eval_X]
      linear_combination hx
    obtain ⟨q, hq⟩ := dvd_iff_isRoot.mpr hroot
    have hq0 : q ≠ 0 := fun h => hp0 (by rw [hq, h, mul_zero])
    have hqdeg : q.natDegree = 1 := by
      have h2 := hdeg
      rw [hq, natDegree_mul (X_sub_C_ne_zero x) hq0, natDegree_X_sub_C] at h2
      omega
    rw [hq]
    exact (Splits.of_natDegree_le_one (natDegree_X_sub_C x).le).mul
      (Splits.of_natDegree_le_one hqdeg.le)

/-- Over a field of characteristic `≠ 2`, a quadratic `a X² + b X + c` (with `a ≠ 0`) *splits*
exactly when its discriminant `b² - 4 a c` is a square: it splits iff it has a root
(`splits_quadratic_iff_exists_root`), and completing the square
(`discrim_eq_sq_of_quadratic_eq_zero` / `exists_quadratic_eq_zero`) matches roots with square roots
of the discriminant. This is the split-multiplicative-reduction criterion; compare
`separable_quadratic_iff` (separable ↔ discriminant nonzero). -/
theorem splits_quadratic_iff {k : Type*} [Field k] [NeZero (2 : k)] {a b c : k} (ha : a ≠ 0) :
    (C a * X ^ 2 + C b * X + C c).Splits ↔ IsSquare (discrim a b c) := by
  rw [splits_quadratic_iff_exists_root ha]
  constructor
  · rintro ⟨x, hx⟩
    exact ⟨2 * a * x + b, by rw [discrim_eq_sq_of_quadratic_eq_zero (a := a) (b := b) (c := c)
      (x := x) (by linear_combination hx)]; ring⟩
  · rintro ⟨s, hs⟩
    obtain ⟨x, hx⟩ := exists_quadratic_eq_zero ha ⟨s, by rw [hs]⟩
    exact ⟨x, by linear_combination hx⟩

/-- Over a field of characteristic `2`, a *separable* quadratic `a X² + b X + c` (`a, b ≠ 0`)
splits exactly when its Artin–Schreier invariant `a c / b²` lies in the image of `z ↦ z² + z`,
written division-free as `∃ z, b² (z² + z) = a c`. (Substitute `z = a x / b` in a root `x`.) In
residue characteristic `2` this replaces the square-class criterion `splits_quadratic_iff`, since
there `b² - 4 a c = b²`, so separability already forces `b ≠ 0`. -/
theorem splits_quadratic_iff_of_two_eq_zero {k : Type*} [Field k] (h2 : (2 : k) = 0)
    {a b c : k} (ha : a ≠ 0) (hb : b ≠ 0) :
    (C a * X ^ 2 + C b * X + C c).Splits ↔ ∃ z, b ^ 2 * (z ^ 2 + z) = a * c := by
  rw [splits_quadratic_iff_exists_root ha]
  constructor
  · rintro ⟨x, hx⟩
    refine ⟨a * x / b, ?_⟩
    field_simp
    linear_combination hx - c * h2
  · rintro ⟨z, hz⟩
    refine ⟨b * z / a, ?_⟩
    field_simp
    linear_combination hz + a * c * h2

end Polynomial

variable {R : Type u} [CommRing R] [IsDomain R] [IsDiscreteValuationRing R]
variable {K : Type u} [Field K] [Algebra R K] [IsFractionRing R K]

omit [IsFractionRing R K] in
/-- A monic quadratic over a discrete valuation ring `R` whose reduction to the residue field is
separable stays separable over the fraction field `K`: the discriminant `c₁² - 4 c₀` has nonzero
residue (`separable_quadratic_iff`), hence is a unit of the local ring `R`
(`IsLocalRing.notMem_maximalIdeal`), hence nonzero in `K`. This is the polynomial input that makes
the lifted extension `K[X]/(p)` separable; the residue-degree=`[L:K]` genuinely missing input is
instead the fraction-field statement `IsFractionRing`. -/
theorem Polynomial.Monic.separable_map_algebraMap_of_separable_residue {p : R[X]}
    (hmonic : p.Monic) (hp : p.natDegree = 2)
    (hsep : (p.map (residue R)).Separable) : (p.map (algebraMap R K)).Separable := by
  set c₀ := p.coeff 0 with hc₀
  set c₁ := p.coeff 1 with hc₁
  set c₂ := p.coeff 2 with hc₂
  have hc₂1 : c₂ = 1 := by rw [hc₂, ← hp]; exact hmonic.coeff_natDegree
  -- `p.map φ = C (φ c₂) X² + C (φ c₁) X + C (φ c₀)` for any ring hom `φ` out of `R`.
  have key : ∀ {k : Type u} [Field k] (φ : R →+* k),
      p.map φ = C (φ c₂) * X ^ 2 + C (φ c₁) * X + C (φ c₀) := fun {k} _ φ => by
    rw [eq_quadratic_of_natDegree_le_two (natDegree_map_le.trans hp.le)]
    simp only [coeff_map, hc₀, hc₁, hc₂]
  -- The discriminant `c₁² - 4 c₂ c₀` has nonzero residue, so is a unit of the local ring `R`.
  rw [key (residue R), separable_quadratic_iff (by rw [hc₂1, map_one]; exact one_ne_zero)] at hsep
  have hδ : residue R (c₁ ^ 2 - 4 * c₂ * c₀) ≠ 0 := by
    rw [map_sub, map_mul, map_mul, map_pow, map_ofNat]; exact hsep
  have hunit : IsUnit (c₁ ^ 2 - 4 * c₂ * c₀) :=
    notMem_maximalIdeal.mp fun hmem => hδ ((residue_eq_zero_iff _).mpr hmem)
  -- Hence the discriminant of `p.map (algebraMap R K)` is nonzero, so the map is separable.
  rw [key (algebraMap R K), separable_quadratic_iff (by rw [hc₂1, map_one]; exact one_ne_zero),
    ← map_pow, ← map_ofNat (algebraMap R K) 4, ← map_mul, ← map_mul, ← map_sub]
  exact (hunit.map (algebraMap R K)).ne_zero

/-- The simple extension `F[X]/(q)` by a root of an irreducible separable polynomial is separable:
the root is separable (its minimal polynomial is `q` up to a unit) and generates the extension. -/
theorem AdjoinRoot.isSeparable_of_separable {F : Type*} [Field F] {q : F[X]} [Fact (Irreducible q)]
    (hq : q.Separable) : Algebra.IsSeparable F (AdjoinRoot q) := by
  have hq0 : q ≠ 0 := (Fact.out (p := Irreducible q)).ne_zero
  have hroot : IsSeparable F (AdjoinRoot.root q) := by
    simp only [IsSeparable, AdjoinRoot.minpoly_root hq0]
    exact hq.mul_unit (isUnit_C.mpr (isUnit_iff_ne_zero.mpr
      (inv_ne_zero (leadingCoeff_ne_zero.mpr hq0))))
  have htop : IntermediateField.adjoin F {AdjoinRoot.root q} = ⊤ :=
    IntermediateField.adjoin_eq_top_of_algebra (hS := AdjoinRoot.adjoinRoot_eq_top)
  have : Algebra.IsSeparable F (⊤ : IntermediateField F (AdjoinRoot q)) := by
    rw [← htop]
    exact (IntermediateField.isSeparable_adjoin_simple_iff_isSeparable _ _).mpr hroot
  exact AlgEquiv.Algebra.isSeparable IntermediateField.topEquiv

/-- The simple extension `F[X]/(q)` by a root of an irreducible quadratic is quadratic. -/
theorem AdjoinRoot.isQuadraticExtension {F : Type*} [Field F] {q : F[X]} [Fact (Irreducible q)]
    (hq : q.natDegree = 2) : Algebra.IsQuadraticExtension F (AdjoinRoot q) :=
  ⟨by rw [PowerBasis.finrank (AdjoinRoot.powerBasis (Fact.out (p := Irreducible q)).ne_zero),
    AdjoinRoot.powerBasis_dim]; exact hq⟩

open IsLocalRing in
/-- For a monic `P` over a discrete valuation ring `R` whose reduction is irreducible over the
residue field, `S = R[X]/(P)` is again a discrete valuation ring, *unramified* over `R`: its maximal
ideal is `𝔪_R · S` (residue field `(residue R)[X]/(P̄)`), so `R → S` is a local homomorphism. -/
theorem AdjoinRoot.isDiscreteValuationRing_of_irreducible_map_residue
    {P : R[X]} [IsDomain (AdjoinRoot P)] (hPm : P.Monic) (hP0 : P.degree ≠ 0)
    (hirr : Irreducible (P.map (residue R))) :
    ((maximalIdeal R).map (algebraMap R (AdjoinRoot P))).IsMaximal ∧
      IsDiscreteValuationRing (AdjoinRoot P) ∧ IsLocalHom (algebraMap R (AdjoinRoot P)) := by
  have : Fact (Irreducible (P.map (residue R))) := ⟨hirr⟩
  have : Module.Free R (AdjoinRoot P) := hPm.free_adjoinRoot
  have : Module.Finite R (AdjoinRoot P) :=
    Module.Finite.of_basis (AdjoinRoot.powerBasis' hPm).basis
  have : Algebra.IsIntegral R (AdjoinRoot P) := Algebra.IsIntegral.of_finite R _
  have hmS_max : ((maximalIdeal R).map (algebraMap R (AdjoinRoot P))).IsMaximal := by
    rw [AdjoinRoot.algebraMap_eq]
    exact Ideal.Quotient.maximal_of_isField _
      ((AdjoinRoot.quotAdjoinRootEquivQuotPolynomialQuot (maximalIdeal R) P).toMulEquiv.isField
        (Field.toIsField (AdjoinRoot (P.map (residue R)))))
  have : IsLocalRing (AdjoinRoot P) := IsLocalRing.of_unique_max_ideal
    ⟨(maximalIdeal R).map (algebraMap R (AdjoinRoot P)), hmS_max, fun M hM => by
      have hc : (M.comap (algebraMap R (AdjoinRoot P))).IsMaximal :=
        Ideal.isMaximal_comap_of_isIntegral_of_isMaximal M
      have hle : (maximalIdeal R).map (algebraMap R (AdjoinRoot P)) ≤ M := by
        rw [← IsLocalRing.eq_maximalIdeal hc]; exact Ideal.map_comap_le
      exact (hmS_max.eq_of_le hM.ne_top hle).symm⟩
  have hmaxS : maximalIdeal (AdjoinRoot P) = (maximalIdeal R).map (algebraMap R (AdjoinRoot P)) :=
    (IsLocalRing.eq_maximalIdeal hmS_max).symm
  have hinj : Function.Injective (algebraMap R (AdjoinRoot P)) := by
    rw [AdjoinRoot.algebraMap_eq]; exact AdjoinRoot.of.injective_of_degree_ne_zero hP0
  have hSnotfield : ¬ IsField (AdjoinRoot P) := fun hf => IsDiscreteValuationRing.not_a_field R (by
    have h0 : maximalIdeal (AdjoinRoot P) = ⊥ := IsLocalRing.isField_iff_maximalIdeal_eq.mp hf
    rw [hmaxS, Ideal.map_eq_bot_iff_le_ker,
      (RingHom.injective_iff_ker_eq_bot _).mp hinj, le_bot_iff] at h0
    exact h0)
  have hSprin : (maximalIdeal (AdjoinRoot P)).IsPrincipal := by
    obtain ⟨ϖ, hϖ⟩ := (IsPrincipalIdealRing.principal (maximalIdeal R)).principal
    exact ⟨⟨algebraMap R (AdjoinRoot P) ϖ, by
      rw [hmaxS, hϖ, Ideal.map_span, Set.image_singleton]⟩⟩
  have : IsDiscreteValuationRing (AdjoinRoot P) :=
    ((IsDiscreteValuationRing.TFAE (AdjoinRoot P) hSnotfield).out 4 0).mp hSprin
  exact ⟨hmS_max, inferInstance,
    ((local_hom_TFAE (algebraMap R (AdjoinRoot P))).out 2 0).mp (le_of_eq hmaxS.symm)⟩

open IsLocalRing in
/-- `L = K[X]/(P·K) = Frac(S)` for `S = R[X]/(P)` a discrete valuation ring: `algebraMap S L` is
injective (its kernel is a prime of the DVR `S`, and it does not kill a uniformizer), and every
`z = mk (P·K) g` clears its `K`-denominators (`integerNormalization`) to a multiple in the image of
`S`. The hypothesis `hmap` records that `algebraMap S L` reduces `mk P` to `mk (P·K) ∘ map`. -/
theorem AdjoinRoot.isFractionRing_map {P : R[X]} (hP0 : P.degree ≠ 0)
    [IsDomain (AdjoinRoot P)] [IsDiscreteValuationRing (AdjoinRoot P)]
    [Fact (Irreducible (P.map (algebraMap R K)))]
    [Algebra (AdjoinRoot P) (AdjoinRoot (P.map (algebraMap R K)))]
    [IsScalarTower R (AdjoinRoot P) (AdjoinRoot (P.map (algebraMap R K)))]
    (hmaxS : maximalIdeal (AdjoinRoot P) = (maximalIdeal R).map (algebraMap R (AdjoinRoot P)))
    (hmap : (algebraMap (AdjoinRoot P) (AdjoinRoot (P.map (algebraMap R K)))).comp (AdjoinRoot.mk P)
      = (AdjoinRoot.mk (P.map (algebraMap R K))).comp (Polynomial.mapRingHom (algebraMap R K))) :
    IsFractionRing (AdjoinRoot P) (AdjoinRoot (P.map (algebraMap R K))) := by
  set S := AdjoinRoot P with hSdef
  set pK := P.map (algebraMap R K) with hpK
  set L := AdjoinRoot pK with hLdef
  have hinj : Function.Injective (algebraMap R S) := by
    rw [AdjoinRoot.algebraMap_eq]; exact AdjoinRoot.of.injective_of_degree_ne_zero hP0
  have hRL_inj : Function.Injective (algebraMap R L) := by
    rw [IsScalarTower.algebraMap_eq R K L]
    exact (algebraMap K L).injective.comp (IsFractionRing.injective R K)
  have hSL_inj : Function.Injective (algebraMap S L) := by
    rw [RingHom.injective_iff_ker_eq_bot]
    by_contra hne
    have : (RingHom.ker (algebraMap S L)).IsPrime := RingHom.ker_isPrime _
    have hmax : (RingHom.ker (algebraMap S L)).IsMaximal :=
      Ideal.IsPrime.isMaximal inferInstance hne
    have hker : RingHom.ker (algebraMap S L) = maximalIdeal S := IsLocalRing.eq_maximalIdeal hmax
    have hmR : maximalIdeal R ≠ ⊥ := IsDiscreteValuationRing.not_a_field R
    obtain ⟨ϖ, hϖmem, hϖ0⟩ : ∃ x ∈ maximalIdeal R, x ≠ 0 := by
      by_contra hc
      simp only [not_exists, not_and, not_ne_iff] at hc
      exact hmR ((Submodule.eq_bot_iff _).mpr hc)
    have hmem : algebraMap R S ϖ ∈ RingHom.ker (algebraMap S L) := by
      rw [hker, hmaxS]; exact Ideal.mem_map_of_mem _ hϖmem
    rw [RingHom.mem_ker, ← IsScalarTower.algebraMap_apply R S L] at hmem
    exact hϖ0 (hRL_inj (by rw [hmem, map_zero]))
  refine (_root_.isLocalization_iff (nonZeroDivisors S) L).mpr ⟨fun y => ?_, fun z => ?_,
    fun {x y} h => ⟨1, by rw [hSL_inj h]⟩⟩
  · exact isUnit_iff_ne_zero.mpr fun h =>
      nonZeroDivisors.ne_zero y.2 (hSL_inj (by rw [h, map_zero]))
  · obtain ⟨g, rfl⟩ := AdjoinRoot.mk_surjective (g := pK) z
    obtain ⟨b, hbmem, hb⟩ := IsLocalization.integerNormalization_spec (nonZeroDivisors R) g
    have hbne : algebraMap R S b ∈ nonZeroDivisors S :=
      mem_nonZeroDivisors_of_ne_zero fun h =>
        nonZeroDivisors.ne_zero hbmem (hinj (by rw [h, map_zero]))
    refine ⟨⟨AdjoinRoot.mk P (IsLocalization.integerNormalization (nonZeroDivisors R) g),
      ⟨algebraMap R S b, hbne⟩⟩, ?_⟩
    have hR := RingHom.congr_fun hmap
      (IsLocalization.integerNormalization (nonZeroDivisors R) g)
    rw [RingHom.comp_apply, RingHom.comp_apply, Polynomial.coe_mapRingHom, hb] at hR
    have hkey : algebraMap S L (algebraMap R S b)
        = AdjoinRoot.mk pK (Polynomial.C (algebraMap R K b)) := by
      rw [← IsScalarTower.algebraMap_apply R S L, IsScalarTower.algebraMap_apply R K L,
        AdjoinRoot.algebraMap_eq, ← AdjoinRoot.mk_C]
    have hsmul : b • g = Polynomial.C (algebraMap R K b) * g := by
      rw [Algebra.smul_def, IsScalarTower.algebraMap_apply R K (Polynomial K),
        Polynomial.algebraMap_eq]
    rw [hR, hkey, hsmul, ← map_mul, mul_comm]

/-- **Unramified lifting.** A separable quadratic extension `k'` of the residue field of a discrete
valuation ring `R` lifts to an unramified quadratic extension `L` of its fraction field `K`: there
is a separable quadratic extension `L/K` and a discrete valuation ring `S` with fraction field `L`,
containing `R` via a local homomorphism, whose residue field is `k'`. (The residue degree being
`2 = [L : K]` forces ramification index `1`.) -/
theorem exists_unramified_quadraticExtension_of_residueField
    (k' : Type u) [Field k'] [Algebra (ResidueField R) k']
    [Algebra.IsQuadraticExtension (ResidueField R) k']
    [Algebra.IsSeparable (ResidueField R) k'] :
    ∃ (L : Type u) (_ : Field L) (_ : Algebra K L) (_ : Algebra.IsQuadraticExtension K L)
      (_ : Algebra.IsSeparable K L) (_ : Algebra R L) (_ : IsScalarTower R K L) (S : Type u)
      (_ : CommRing S) (_ : IsDomain S) (_ : IsDiscreteValuationRing S) (_ : Algebra R S)
      (_ : Module.Finite R S) (_ : Algebra S L) (_ : IsScalarTower R S L) (_ : IsFractionRing S L)
      (_ : IsLocalHom (algebraMap R S)),
      Nonempty (ResidueField S ≃ₐ[ResidueField R] k') := by
  classical
  -- A power basis of `k'/k` gives a monic separable irreducible quadratic `pbar` over `k`, with
  -- `k' ≅ k[X]/(pbar)`.
  letI : FiniteDimensional (ResidueField R) k' :=
    .of_finrank_eq_succ (Algebra.IsQuadraticExtension.finrank_eq_two (ResidueField R) k')
  set pb := Field.powerBasisOfFiniteOfSeparable (ResidueField R) k' with hpb
  have hint : IsIntegral (ResidueField R) pb.gen := Algebra.IsIntegral.isIntegral pb.gen
  set pbar := minpoly (ResidueField R) pb.gen with hpbar
  have hpbar_monic : pbar.Monic := minpoly.monic hint
  have hpbar_deg : pbar.natDegree = 2 := by
    rw [hpbar, pb.natDegree_minpoly, ← pb.finrank]
    exact Algebra.IsQuadraticExtension.finrank_eq_two (ResidueField R) k'
  have hpbar_sep : pbar.Separable := Algebra.IsSeparable.isSeparable (ResidueField R) pb.gen
  have hk'_equiv : AdjoinRoot pbar ≃ₐ[ResidueField R] k' :=
    AdjoinRoot.equiv' pbar pb (by rw [AdjoinRoot.aeval_eq, AdjoinRoot.mk_self]) (minpoly.aeval _ _)
  -- Lift `pbar` to a monic quadratic `P` over `R`; irreducible over `R`, hence over `K`.
  obtain ⟨P0, hP0⟩ := Polynomial.map_surjective (residue R) Ideal.Quotient.mk_surjective pbar
  obtain ⟨P, hP_map, hP_deg, hP_monic⟩ :=
    Polynomial.lifts_and_natDegree_eq_and_monic (p := pbar) ⟨P0, hP0⟩ hpbar_monic
  rw [hpbar_deg] at hP_deg
  have hP_redirr : Irreducible (P.map (residue R)) := by rw [hP_map]; exact minpoly.irreducible hint
  have hP_irr : Irreducible P :=
    Polynomial.Monic.irreducible_of_irreducible_map (residue R) P hP_monic hP_redirr
  have hPdeg : P.degree ≠ 0 := by
    rw [Polynomial.degree_eq_natDegree hP_monic.ne_zero, hP_deg]; decide
  set pK := P.map (algebraMap R K) with hpK
  have : Fact (Irreducible pK) :=
    ⟨(Polynomial.Monic.irreducible_iff_irreducible_map_fraction_map (K := K) hP_monic).mp hP_irr⟩
  set L := AdjoinRoot pK with hL
  set S := AdjoinRoot P with hS
  have hSdom : IsDomain S := AdjoinRoot.isDomain_of_prime
    (UniqueFactorizationMonoid.irreducible_iff_prime.mp hP_irr)
  have : Module.Finite R S := Module.Finite.of_basis (AdjoinRoot.powerBasis' hP_monic).basis
  -- `S = R[X]/(P)` is a discrete valuation ring, unramified over `R` (`isDiscreteValuationRing_…`).
  obtain ⟨hmS_max, hSdvr, hSlocalhom⟩ :=
    AdjoinRoot.isDiscreteValuationRing_of_irreducible_map_residue hP_monic hPdeg hP_redirr
  have hmaxS : maximalIdeal S = (maximalIdeal R).map (algebraMap R S) :=
    (IsLocalRing.eq_maximalIdeal hmS_max).symm
  -- `L = K[X]/(pK)` is a separable quadratic extension of `K`.
  have : Algebra.IsQuadraticExtension K L :=
    AdjoinRoot.isQuadraticExtension (by rw [hpK, hP_monic.natDegree_map]; exact hP_deg)
  have : Algebra.IsSeparable K L := AdjoinRoot.isSeparable_of_separable
    (hP_monic.separable_map_algebraMap_of_separable_residue hP_deg
      (by rw [hP_map]; exact hpbar_sep))
  have : IsScalarTower R K L := inferInstance
  -- The `R`-algebra map `S → L` (reduction of `mk P` along `R → K`), tower `R → S → L`.
  letI : Algebra S L := (AdjoinRoot.map (algebraMap R K) P pK hpK.dvd).toAlgebra
  have : IsScalarTower R S L := IsScalarTower.of_algebraMap_eq fun r => by
    rw [RingHom.algebraMap_toAlgebra, AdjoinRoot.algebraMap_eq (f := P), AdjoinRoot.map_of,
      AdjoinRoot.algebraMap_eq']
    rfl
  have hmap_mk : (algebraMap S L).comp (AdjoinRoot.mk P)
      = (AdjoinRoot.mk pK).comp (Polynomial.mapRingHom (algebraMap R K)) := by
    refine Polynomial.ringHom_ext (fun r => ?_) ?_
    · rw [RingHom.comp_apply, RingHom.comp_apply, AdjoinRoot.mk_C, RingHom.algebraMap_toAlgebra,
        AdjoinRoot.map_of, Polynomial.coe_mapRingHom, Polynomial.map_C, AdjoinRoot.mk_C]
    · rw [RingHom.comp_apply, RingHom.comp_apply, ← AdjoinRoot.root, RingHom.algebraMap_toAlgebra,
        AdjoinRoot.map_root, Polynomial.coe_mapRingHom, Polynomial.map_X, ← AdjoinRoot.root]
  -- `L = Frac S` (`isFractionRing_map`).
  have : IsFractionRing S L := AdjoinRoot.isFractionRing_map hPdeg hmaxS hmap_mk
  -- Residue field: `S/mS ≅ (residue R)[X]/(pbar) ≅ k'`. Build it as `R`-algebra equivs (which carry
  -- their `commutes`), then lift the base ring to `ResidueField R` (`extendScalarsOfSurjective`).
  letI : Algebra R k' := ((algebraMap (ResidueField R) k').comp (residue R)).toAlgebra
  have : IsScalarTower R (ResidueField R) k' := .of_algebraMap_eq fun _ => rfl
  have e : ResidueField S ≃ₐ[R] k' :=
    (Ideal.quotientEquivAlgOfEq R hmaxS).trans
      ((AdjoinRoot.quotEquivQuotMap P (maximalIdeal R)).trans
        ((Ideal.quotientEquivAlgOfEq R (congrArg (fun q => Ideal.span {q}) hP_map)).trans
          (hk'_equiv.restrictScalars R)))
  exact ⟨L, inferInstance, inferInstance, inferInstance, inferInstance, inferInstance,
    inferInstance, S, inferInstance, inferInstance, inferInstance, inferInstance, inferInstance,
    inferInstance, inferInstance, inferInstance, inferInstance,
    ⟨e.extendScalarsOfSurjective residue_surjective⟩⟩
