import FLT.Slop.DimensionTheorem.Defs

/-!
# `dim R = δ(R)`

The Krull dimension of a Noetherian local ring equals the minimal number of
generators of an ideal of definition (an `𝔪`-primary ideal) — the equivalence
(1) ↔ (3) of the dimension theorem (Stacks Project, tag 00KQ).

Both inequalities are assembled from Krull's height theorem and its converse,
which are already in Mathlib (`Mathlib/RingTheory/Ideal/KrullsHeightTheorem.lean`,
He–Jiang–Merten–Wang–Yang–Zhang, 2025):

* `dim R ≤ δ(R)` (`ringKrullDim_le_minGenPrimary`): if `I` is an ideal of
  definition then `𝔪` is minimal over `I` (`maximalIdeal_mem_minimalPrimes`),
  so Krull's height theorem
  (`Ideal.height_le_spanRank_toENat_of_mem_minimalPrimes`) bounds
  `dim R = height 𝔪` by the number of generators of `I`.
* `δ(R) ≤ dim R` (`minGenPrimary_le_ringKrullDim`): the converse of the height
  theorem (`Ideal.exists_spanRank_eq_and_height_eq`) produces `J ≤ 𝔪`
  generated by `height 𝔪` elements with `height J = height 𝔪`. Every minimal
  prime of `J` then has height `dim R`, hence equals `𝔪`, so `J.radical = 𝔪`:
  `J` is a *system of parameters* for `R`.

The classical proof of the second inequality constructs a system of parameters
by prime avoidance (Atiyah–Macdonald, Ch. 11); here that content is packaged
inside Mathlib's `exists_spanRank_eq_and_height_eq`.

## Main result

* `DimensionTheorem.ringKrullDim_eq_minGenPrimary` :
  `ringKrullDim R = δ(R)` for `R` Noetherian local.
-/

namespace DimensionTheorem

open IsLocalRing

variable (R : Type*) [CommRing R] [IsLocalRing R] [IsNoetherianRing R]

omit [IsNoetherianRing R] in
/-- If `I` has radical `𝔪`, then `𝔪` is minimal over `I`. -/
lemma maximalIdeal_mem_minimalPrimes {I : Ideal R}
    (h : I.radical = maximalIdeal R) : maximalIdeal R ∈ I.minimalPrimes := by
  rw [← Ideal.radical_minimalPrimes, h, Ideal.minimalPrimes_eq_subsingleton_self]
  exact Set.mem_singleton _

/-- **Dimension theorem, easy inequality**: `dim R ≤ δ(R)`, from Krull's height
theorem. -/
theorem ringKrullDim_le_minGenPrimary :
    ringKrullDim R ≤ (minGenPrimary R : WithBot ℕ∞) := by
  -- The defining set of `minGenPrimary` is nonempty: `𝔪` itself is a witness.
  have hne : {k | ∃ I : Ideal R, I.radical = maximalIdeal R ∧ I.spanFinrank = k}.Nonempty :=
    ⟨(maximalIdeal R).spanFinrank, maximalIdeal R,
      (maximalIdeal.isMaximal R).isPrime.radical, rfl⟩
  obtain ⟨I, hIrad, hIk⟩ :
      ∃ I : Ideal R, I.radical = maximalIdeal R ∧ I.spanFinrank = minGenPrimary R :=
    Nat.sInf_mem hne
  -- Krull's height theorem applied to `𝔪 ∈ I.minimalPrimes`.
  have h1 : (maximalIdeal R).height ≤ (I.spanFinrank : ℕ∞) := by
    have h := Ideal.height_le_spanRank_toENat_of_mem_minimalPrimes I _
      (maximalIdeal_mem_minimalPrimes R hIrad)
    rwa [Submodule.fg_iff_spanRank_eq_spanFinrank.mpr (IsNoetherian.noetherian I),
      map_natCast] at h
  calc ringKrullDim R = ((maximalIdeal R).height : WithBot ℕ∞) :=
        (maximalIdeal_height_eq_ringKrullDim).symm
    _ ≤ ((I.spanFinrank : ℕ∞) : WithBot ℕ∞) := WithBot.coe_le_coe.mpr h1
    _ = (minGenPrimary R : WithBot ℕ∞) := by rw [hIk]; norm_cast

/-- **Dimension theorem, converse inequality**: `δ(R) ≤ dim R`; there exists a
system of parameters, i.e. an `𝔪`-primary ideal generated by `dim R` elements. -/
theorem minGenPrimary_le_ringKrullDim :
    (minGenPrimary R : WithBot ℕ∞) ≤ ringKrullDim R := by
  have hmne : maximalIdeal R ≠ ⊤ := (maximalIdeal.isMaximal R).ne_top
  -- Converse of Krull's height theorem: `J ≤ 𝔪` spanned by `ht 𝔪` elements
  -- with `ht J = ht 𝔪`.
  obtain ⟨J, hJle, hJrank, hJheight⟩ :=
    Ideal.exists_spanRank_eq_and_height_eq (maximalIdeal R) hmne
  have hJne : J ≠ ⊤ := fun h => hmne (top_le_iff.mp (h ▸ hJle))
  -- `ht 𝔪 = J.spanFinrank` (as elements of `ℕ∞`), since `J` is finitely generated.
  have hfr : (maximalIdeal R).height = (J.spanFinrank : ℕ∞) :=
    Cardinal.ofENat_eq_nat.mp
      (by rw [← hJrank, Submodule.fg_iff_spanRank_eq_spanFinrank.mpr
        (IsNoetherian.noetherian J)])
  -- Every minimal prime of `J` equals `𝔪`, since its height is at least `ht J = ht 𝔪`.
  have hall : ∀ p ∈ J.minimalPrimes, p = maximalIdeal R := by
    intro p hp
    haveI := hp.isPrime
    have h1 : J.height ≤ p.height := by
      rw [Ideal.height_eq_inf_minimalPrimes]
      exact iInf₂_le p hp
    have h2 : (maximalIdeal R).height ≤ p.height := hJheight ▸ h1
    exact Ideal.eq_of_le_of_height_le p (le_maximalIdeal Ideal.IsPrime.ne_top') h2
  -- Hence `J.radical = 𝔪`, i.e. `J` is an ideal of definition.
  have hrad : J.radical = maximalIdeal R := by
    obtain ⟨p, hp⟩ := Ideal.nonempty_minimalPrimes hJne
    rw [← Ideal.sInf_minimalPrimes,
      Set.eq_singleton_iff_unique_mem.mpr ⟨hall p hp ▸ hp, hall⟩, sInf_singleton]
  -- Conclude: `δ(R) ≤ J.spanFinrank = ht 𝔪 = dim R`.
  have hle : minGenPrimary R ≤ J.spanFinrank := Nat.sInf_le ⟨J, hrad, rfl⟩
  calc (minGenPrimary R : WithBot ℕ∞) ≤ (J.spanFinrank : WithBot ℕ∞) := by
        exact_mod_cast hle
    _ = ((maximalIdeal R).height : WithBot ℕ∞) := by rw [hfr]; norm_cast
    _ = ringKrullDim R := maximalIdeal_height_eq_ringKrullDim

/-- `dim R = δ(R)` for a Noetherian local ring. -/
theorem ringKrullDim_eq_minGenPrimary :
    ringKrullDim R = (minGenPrimary R : WithBot ℕ∞) :=
  le_antisymm (ringKrullDim_le_minGenPrimary R) (minGenPrimary_le_ringKrullDim R)

end DimensionTheorem
